### ISSUE TITLE
Service crashes in production, staging and testing environments 

### ISSUE THREAD

**Issue by BannerwiseMZL** [Opteo/google-ads-api#100]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

We've implemented this module in one of our node apps. While developing the feature we encountered absolutely 0 issues. Today I've deployed the service using NGIX and Kubernetes and I was surprised to see that the service breaks when creating a new GoogleAdsApi. The service exits with the following message.

2020-02-07T06:51:14: PM2 log: App name:gads-api-bannerwise id:1 disconnected
2020-02-07T06:51:14: PM2 log: App [gads-api-bannerwise:1] exited with code [0] via signal [SIGKILL]

 Are there any requirements that I might have overlooked like node version or anything else?

**Comment by avermeil** [comment]
I'm closing this for now. We've tried running it in kubernetes, and it seems to work fine. Feel free to re-open if anything else comes up!

**Comment by kritzware** [comment]
We're using the docker image `node:12-alpine` as our base image on Kubernetes. Seems to run fine in our cluster.
