### ISSUE TITLE
AdGroupAd Update: Argument mismatch in makeUnaryRequest

### ISSUE THREAD

**Issue by panoshalios** [Opteo/google-ads-api#103]
### I'm submitting a ...
-   [x] bug report

### Summary
It seems that there is a bug when trying to update an AdGroupAd. It finally fails with "Argument mismatch in makeUnaryRequest".

The code I use to update an expanded_text_ad:
```
const adGroupAd = {
      resource_name: `customers/${customerId}/adGroupAds/${adGroupId}`,
      ad: {
        expanded_text_ad: {
          headline_part1: 'NEW TEST HEADLINE',
        }
      }
};
// adsManager is just a wrapper
const adUpdate = await adsManager.customer.adGroupAds.update(adGroupAd); 
```

### Other information
I have traced the error and found out that **makeUnaryRequest** gets called with **undefined 'metadata, options and callback params** but I am unsure why since I am unfamiliar with both gRPC and the google-ads-api service.js libraries.

_Nodejs version -- v13.10.1
Google-ads-api version -- v3.5.1_

I have included the call stack below.
![image](https://user-images.githubusercontent.com/20459032/76427420-f0985680-63b4-11ea-8074-7d525d7a2c86.png)

**Comment by avermeil** [comment]
Hi @panoshalios  -- This should be fixed in `5.2.2`.
