### ISSUE TITLE
no returning of video_quartile_X_rate on Video resource via Query

### ISSUE THREAD

**Issue by Flintlozk** [Opteo/google-ads-api#104]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary
Already check on Google Ads Dashboard, there have a Data on video_quartile
I have tried this query and got no result of video_quartile
```txt
    SELECT
        metrics.video_quartile_100_rate,
        metrics.video_quartile_25_rate,
        metrics.video_quartile_50_rate,
        metrics.video_quartile_75_rate,
        metrics.video_views,
        video.title
    FROM
        video
    WHERE
        segments.date DURING TODAY
```

Returning Result
```js
[
 {
    metrics: { video_view_rate: 0.5193905817174516 },
    video: {
      resource_name: 'customers/xxxx/videos/xxxxxx',
      title: 'XXXXXX'
    }
  }
]
```

**Comment by kritzware** [comment]
See my response on the original issue for this bug: https://github.com/Opteo/google-ads-api/issues/99

I'm going to close this for now since it's a duplicate.
