### ISSUE TITLE
Sync the examples

### ISSUE THREAD

**Issue by Zikoel** [Opteo/google-ads-api#107]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [X] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary
On the readme there is a link to some [examples](https://github.com/Opteo/google-ads-api/tree/561e5b4782a3a184c920d04aefdbc6e7547f0ae4/examples) but due the fact that these examples are inside a branch is not easy understand if they are sync with the actual version of the library.

Is possible to merge the that branch or move the examples on the actual version so that the users can be confident that the examples are working with the last version of the library ?

**Comment by kritzware** [comment]
Hi @Zikoel, we're planning to release an up to date collection of examples with the release of Google Ads API v3.

**Comment by Midnight-Conqueror** [comment]
Hi @Zikoel We have added more examples in v3.6.0, let us know if you would like more

**Comment by Zikoel** [comment]
Thank you guys for your job!
