### ISSUE TITLE
How to Add User to UserList

### ISSUE THREAD

**Issue by dyllandry** [Opteo/google-ads-api#112]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

I can't figure out how to add a user to a user list.

I'm still trying to read the [Google Ads Api documentation](https://developers.google.com/google-ads/api/docs/remarketing/overview) to see if I'm misunderstanding the intended workflow with remarketing.

### Other information

I can at the least create the user list:
```javascript
async createUserList() {
    const mutation = await this.customer.userLists.create({
        name: '<USERLIST_NAME>',
        membership_life_span: 60,
        membership_status: enums.UserListMembershipStatus.OPEN,
        basic_user_list: {
            actions: [{
                remarketing_action: '<REMARKETING_ACTION_RESOURCE_NAME>',
            }]
        }
    })
    console.log(`created userlist ${mutation.results[0]}`)
    return mutation.results[0]
}
```

**Comment by kritzware** [comment]
I haven't experimented much with user lists, but from a quick glance this code seems like it should be fine. Are there any errors when running it?

**Comment by dyllandry** [comment]
Creating the user list works, there are no errors.
But I'm trying to do is add a user to the user list so I can remarket to them. That's what I am having trouble figuring out. I am not even sure if this is how it's supposed to work, it just seemed intuitive that this was how it would work.

**Comment by Ka6utack** [comment]
> Creating the user list works, there are no errors.
> But I'm trying to do is add a user to the user list so I can remarket to them. That's what I am having trouble figuring out. I am not even sure if this is how it's supposed to work, it just seemed intuitive that this was how it would work.
> And thanks for the response 👍 , sorry for my late reply.
I have the same trouble . have you solved your problem? `Adwords Api` have `mutateMembers` function, but i did not find it in `google ads api beta`. cry...

**Comment by dyllandry** [comment]
@Ka6utack No, i have no solution yet. I'm putting off the problem until it becomes a priority again at work.
