### ISSUE TITLE
Custom Interest support in atomic mutations?

### ISSUE THREAD

**Issue by projectyang** [Opteo/google-ads-api#116]
### I'm submitting a ...

-   [x] bug report
-   [x] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

Trying to CREATE the following entity:

> {
>       type: 3,
>       name: 'test',
>       description: 'test2',
>       members: [{ member_type: 2, parameter: 'dog' }],
>       _resource: 'CustomInterest',
>     }

I'll get a 

> op[operation_set_method] is not a function

error when creating it in the batch method (e.g. getCustomer().mutateResources()). Is CustomInterests supported for atomic mutations? 

I poked around in the code for google-ads-node, and noticed that the MutateOperations interface doesn't have a reference to it yet.

**Comment by WillCooter** [comment]
This is now supported in the latest version.
