### ISSUE TITLE
Deleting custom interests does not work

### ISSUE THREAD

**Issue by projectyang** [Opteo/google-ads-api#118]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

Following the example code:

`await customer.customInterests.delete(resourceId)
`

The following error occurs: 
`operation.setRemove is not a function`

**Comment by kritzware** [comment]
Hi @projectyang, looking at the official Google Ads API docs, it looks like the `CustomInterest` service doesn't support the `remove` operation; only `create` and `update`.

We'll make sure this method is removed in our upcoming upgrade.

Ref: https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.services#google.ads.googleads.v3.services.CustomInterestOperation

**Comment by projectyang** [comment]
Ah, gotcha! Thanks for the clarification.
