### ISSUE TITLE
Ad type issue

### ISSUE THREAD

**Issue by AshwanthMadhav** [Opteo/google-ads-api#120]
Here in the link [https://opteo.com/dev/google-ads-api/#ad](Ad) ,Type 7 is SHOPPING_SMART_AD.

But when pulling data using NPM, getting expanded_dynamic_search_ad object with type 7 ?

**Comment by avermeil** [comment]
This looks like the same problem as https://github.com/Opteo/google-ads-api/issues/78.

We'll fix the docs when we regenerate for the next version. In the meantime, we recommend you use the `enums` export, which is always corrrect :)

**Comment by avermeil** [comment]
This is now fixed.
