### ISSUE TITLE
All metrics are not returning in reports api

### ISSUE THREAD

**Issue by imhassan** [Opteo/google-ads-api#124]
I want to get all metrics that I have supplied in 'metric' array. But I am only getting 'impressions', 'clicks', 'conversions' in response. If there is no metric then atleast I should get empty data array against the metrics. Anything that I am doing wrong Please help
```
const adGroupMetrics = await customer.report({
                entity: 'ad_group',
                attributes: ['ad_group.id', 'ad_group.name', 'ad_group.status', ],
               metrics: ['metrics.content_impression_share','metrics.average_cost', 'metrics.impressions', 'metrics.clicks', 'metrics.conversions', 'metrics.video_quartile_25_rate', 'metrics.video_quartile_50_rate', 'metrics.video_quartile_75_rate', 'metrics.video_quartile_100_rate', 'metrics.active_view_impressions', 'metrics.active_view_measurable_impressions'],
                segments: ['segments.date'],
                from_date: '2019-01-01',
                limit: 10,
            })
```

Response

```
[{ ad_group:
     { resource_name: 'customers/#####',
       id: 556,
       name: 'programmatic ad ',
       status: 2 },
    metrics:
     { active_view_impressions: 0,
       active_view_measurable_impressions: 0,
       clicks: 0,
       conversions: 0,
       impressions: 0 },
    segments: { date: '2020-01-20' } } ]
```

**Comment by kritzware** [comment]
What [type](https://developers.google.com/google-ads/api/reference/rpc/v3/AdTypeEnum.AdType) is the ad? It's possible these metrics aren't available for that entity. The metrics you're specifying may also depend on Google Analytics being connected to your Google Ads account.

**Comment by imhassan** [comment]
Mostly are type=2 (text ad). I am not event getting 'metrics.average_cost'.

**Comment by WillCooter** [comment]
This should be resolved in the latest version. If not then please let us know.
