### ISSUE TITLE
Targeting Idea Service

### ISSUE THREAD

**Issue by motiejuss** [Opteo/google-ads-api#125]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

Hi. What would be the equivalent here of using the Targeting Idea Service?
https://developers.google.com/adwords/api/docs/guides/targeting-idea-service

**Comment by kritzware** [comment]
> The Keyword Planner in the Google Ads UI proposes new keyword ideas based on your existing keywords and website.

The naming conventions in the new Google Ads UI should match the service name in the Google Ads API. I believe what you're looking for is the [KeywordPlanService](https://developers.google.com/google-ads/api/reference/rpc/v3/KeywordPlanService). For use with this library, [see our own docs here](https://opteo.com/dev/google-ads-api/#keywordplan).

**Comment by Batuhan-Akkaya** [comment]
@kritzware Hi
According to the [link](https://opteo.com/dev/google-ads-api/#keywordplan), the keyword-plan object does not get a seed field. I could not figure out how to send the request according to the Google documentation.
Could you please provide a simple example? (For example, bring keywords related to the site foo.bar)
Thanks

**Comment by doverradio** [comment]
Also I'm looking for a way to send random keywords as a request to Google's API and get the Keyword Planner results.  Any solution?
