### ISSUE TITLE
Mutate resource response order

### ISSUE THREAD

**Issue by Zikoel** [Opteo/google-ads-api#126]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X] question about how to use this project

### Summary
I need to update/create a certain amount of various resource atomically, I can do that  with `CustomerInstance.mutateResources` method. Can I assume that the returned response about the new created resources is in the same order of the array of object that I have passed to the method?

I ask that because I need to match the new created resources with other application objects and I can't see at the moment another way to match the chained objects.

**Comment by avermeil** [comment]
Hi @Zikoel !

We don't re-order what we get back from the Google servers. You can ask googleadsapi-support@google.com for confirmation, but I think it's safe to assume that they return the resources in the order that you specified them.

**Comment by Zikoel** [comment]
Thank you for the information, I will investigate more with google support! Do you know a best practice to do that? Sound strange to me that this is not a common problem...

**Comment by Zikoel** [comment]
I explored a bit the official adwords-api google group and seems that is confirmed that the order is preserved, so that we can safely re-conciliate the internal app ids with the remote ones rely on the mutations order.

If someone can find a better solutions I will be happy to hear that.
