### ISSUE TITLE
Is there a way to run keywords-performance-report?

### ISSUE THREAD

**Issue by eliotik** [Opteo/google-ads-api#127]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X] question about how to use this project

### Summary

In python script I used google's lib to run reports and one of queries was:
```python
query = """SELECT Id FROM KEYWORDS_PERFORMANCE_REPORT
                    WHERE Status NOT_IN [REMOVED]
                    AND IsNegative IN [FALSE, TRUE]
                    AND AdGroupStatus NOT_IN [REMOVED]
                    AND CampaignStatus NOT_IN [REMOVED]"""
```
I checked this example: https://github.com/Opteo/google-ads-api/blob/master/examples/reporting/get_keyword_stats.js
But still cannot find a way to fetch keywords and negative keywords altogether.

### Other information

Report doc: https://developers.google.com/adwords/api/docs/appendix/reports/keywords-performance-report

**Comment by eliotik** [comment]
Missed to explain, I need to collect stats on accounts:
- amount of campaigns
- amount of ads
- amount of keywords
Current flow is:
list nested clients under master account:
```js
      const nestedClients = await mcc.customerClients.list({
        constraints: [
          {
            key: "customer_client.hidden",
            op: "=",
            val: false
          }
        ]
      });
```
then create adwords clients per each item from previous step:
```js
        const nestedCustomerClient = createCustomerClient(
          customer_client.client_customer.split("/")[1]
        );
```
run report to get more info about nested account:
```js
        const nestedAccounts = await nestedCustomerClient.report({
          entity: "customer",
          attributes: [
            "customer.id",
            "customer.manager",
            "customer.resource_name",
            "customer.descriptive_name",
            "customer.currency_code",
            "customer.time_zone"
          ]
        });
```
recieve all campaings under nested customer account:
```js
          const campaigns = await nestedCustomerClient.report({
            entity: "campaign",
            attributes: ["campaign.id", "campaign.status", "campaign.resource_name"],
            constraints: [
              {
                key: "campaign.status",
                op: "IN",
                val: [enums.CampaignStatus.ENABLED, enums.CampaignStatus.PAUSED]
              }
            ]
          });
```
then using stream report get ads:
```js
          const adsGenerator = nestedCustomerClient.reportStream({
            entity: "ad_group_ad",
            attributes: ["ad_group_ad.ad.id"],
            constraints: [
              {
                key: "ad_group_ad.status",
                op: "!=",
                val: enums.AdGroupAdStatus.REMOVED
              },
              {
                key: "ad_group.status",
                op: "!=",
                val: enums.AdGroupStatus.REMOVED
              },
              {
                key: "campaign.status",
                op: "!=",
                val: enums.CampaignStatus.REMOVED
              }
            ]
          });

          let ads = 0;
          for await (const item of adsGenerator) {
            ++ads;
          }
```
and finally get keywords amount by running this:
```js
          const keywordsGenerator = nestedCustomerClient.reportStream({
            entity: "keyword_view",
            attributes: ["ad_group.id"],
            constraints: [
              {
                key: "ad_group.status",
                op: "!=",
                val: enums.AdGroupStatus.REMOVED
              },
              {
                key: "campaign.status",
                op: "!=",
                val: enums.CampaignStatus.REMOVED
              },
              {
                key: "ad_group_criterion.status",
                op: "!=",
                val: enums.AdGroupCriterionStatus.REMOVED
              }
            ]
          });

          let keywords = 0;
          for await (const item of keywordsGenerator) {
            ++keywords;
          }
```

First of all I fill the flow became. overcomplicated - probably I'm missing some part on how to correctly use this library.
Second is it is very slow. We have some accounts with millions of ads and millions of keywords and for such accounts, logic above, can work for 1h+ per account.
We have more than 20 large accounts, and I cannot imagine this script to work for 20+ hours.

Any advise on this will be greatly appreciated.
Thank you.

**Comment by eliotik** [comment]
Hi, after reading google docs api references:
https://developers.google.com/google-ads/api/reference/rpc/v3/SearchGoogleAdsRequest
and 
https://developers.google.com/google-ads/api/reference/rpc/v3/SearchGoogleAdsStreamRequest
I see that in these two types in grpc have next fields:
> SearchGoogleAdsStreamRequest :: summary_row_setting
and
> SearchGoogleAdsRequest :: validate_only
> SearchGoogleAdsRequest :: return_total_results_count
> SearchGoogleAdsRequest :: summary_row_setting
I checked code here:
https://github.com/Opteo/google-ads-node/blob/f75f719c77742f23b94005f320fb1f0b14c673e9/src/lib/resources.ts#L5177
and here:
https://github.com/Opteo/google-ads-node/blob/f75f719c77742f23b94005f320fb1f0b14c673e9/src/lib/resources.ts#L5397
And see that these interfaces have options mentioned above.
But unfortunately code here:
https://github.com/Opteo/google-ads-api/blob/46fc5e98b9fcf6e72be635c5b2649be433d3ba59/src/services/service.ts#L284
doesn't use any of these options.
I posted links to only `.report` function related code, but other code parts also do not use these options.

I checked with google support and they confirmed me if we need to fetch only resulting row of summary for query - we need to pass `summary_row_setting`.

I did a quick test locally and tried to pass that option and got error: 
> Can not return summary row if request did not select any metrics field.
I added metrics and had next code:
```js
await nestedCustomerClient.report({
            entity: "ad_group_ad",
            attributes: ["ad_group_ad.ad.id"],
            metrics: ['metrics.clicks'],
            constraints: [
              {
                key: "ad_group_ad.status",
                op: "!=",
                val: enums.AdGroupAdStatus.REMOVED
              },
              {
                key: "ad_group.status",
                op: "!=",
                val: enums.AdGroupStatus.REMOVED
              },
              {
                key: "campaign.status",
                op: "!=",
                val: enums.CampaignStatus.REMOVED
              }
            ],
            summary_row_setting: 4
          });
```
no error, but return result is empty array.
will see what I'm missing, maybe instead of returning response.resultsList in case summary_row_setting provided I need to return from response something different, will check latter.

But for now it's clear that some functionality is missing from library.
Is it possible to add it?
Thanks.

**Comment by eliotik** [comment]
Sorry for confusion, issue title is now not related to my previous comment.
Should I update title and description?
Main issue is that few important options are missing from Request Settings object, with this options you can do dry requests without mutations, request total amount of items without fetching everything and count what was fetched.

**Comment by kritzware** [comment]
No worries, feel free to make some new issues for individual feature requests if you want!

I know for a fact that we don't currently support the `summary_row_setting` field, and it's probably something we should implement. It's already possible with google-ads-node, so it's just a question of setting it up in this library.

> you can do dry requests without mutations

This should already be possible with `validate_only` right? All supported mutate methods should have this option available.

**Comment by eliotik** [comment]
Hi @kritzware , thank you for your reply.
You are right, all mutate methods have validate_only option, my bad here.
I checked with `google-ads-node` and yes it's possible to use `summary_row_setting`, so would be great to support it in `google-ads-api` too.

**Comment by kritzware** [comment]
A PR is now open for adding support for the Summary Row Setting https://github.com/Opteo/google-ads-api/pull/134

**Comment by eliotik** [comment]
@kritzware wonderful news :bow:

**Comment by kritzware** [comment]
Summary row is now supported in 3.7.0 🎉

**Comment by eliotik** [comment]
@kritzware 🤗🎉
