### ISSUE TITLE
remaining account total budget

### ISSUE THREAD

**Issue by sogangCSmaster** [Opteo/google-ads-api#133]
Hello..
Can I get account's total remaining budget?

Thx..

**Comment by kritzware** [comment]
Hi @sogangCSmaster, it looks like you want the [Account Budget](https://developers.google.com/google-ads/api/fields/v3/account_budget) report, specifically the field `account_budget.amount_served_micros`.

**Comment by sogangCSmaster** [comment]
thank you!!!
