### ISSUE TITLE
google ads api v4 support?

### ISSUE THREAD

**Issue by mnikitas** [Opteo/google-ads-api#147]
### I'm submitting a ...

-   [x] feature request

### Summary

Are there any plans to support v4 https://developers.google.com/google-ads/api/docs/release-notes ?

**Comment by kritzware** [comment]
Hi @mnikitas, we're going to start work on this by at least this week or next 👍

**Comment by kritzware** [comment]
[V4 is now available to use!](https://www.npmjs.com/package/google-ads-api) You'll need to upgrade `google-ads-api` to `v4.0.0` 🎉

**Comment by mnikitas** [comment]
Just updated to 4.0.0 but could not find the new service ThirdPartyAppAnalyticsLinkService. Its not exported in customer.d.ts.

**Comment by Midnight-Conqueror** [comment]
@mnikitas thanks for spotting that, somehow in our error we seemed to have forgotten to add them in, whoops! We will release a fix very shortly
