### ISSUE TITLE
GenerateKeywordIdeas ?

### ISSUE THREAD

**Issue by wbelk** [Opteo/google-ads-api#149]
Is there a way to access[ KeywordPlanIdeaService. GenerateKeywordIdeas](https://developers.google.com/google-ads/api/reference/rpc/v4/KeywordPlanIdeaService#generatekeywordideas) ?

I've been trying a few different combinations like `await customer.keywordPlanIdeaService.generateKeywordIdeas(options)` similar to `await customer.keywordPlans.generateForecastMetrics(kPlanId)` but can't quite find it.

I'm sure I'm doing something dumb...

**Comment by kritzware** [comment]
Not at all, it looks like this service hasn't been implemented in this library. I'm working on a small PR to make this available 👍

**Comment by wbelk** [comment]
Thank you!

**Comment by SebastianEdwards** [comment]
@wbelk any idea when this may be available? Would be awesome to be able to use these APIs with a TypeScript-friendly library. No rush though - love your work!

**Comment by kritzware** [comment]
> No rush though - love your work!

Thanks @SebastianEdwards 👍 

I've been a bit delayed with this PR, but will get back to it soon.

**Comment by rveitch** [comment]
Any idea on the status of this? Thanks!!!

**Comment by WillCooter** [comment]
This is now resolved in the latest version.
