### ISSUE TITLE
Atomic Mutations

### ISSUE THREAD

**Issue by jafaircl** [Opteo/google-ads-api#15]
The REST API has a way to create multiple objects atomically in a single request by using temporary IDs. That way, if one of the requests fails, they all fail and you won't have to go back and delete the ones that worked to maintain consistency. One example is creating campaign budgets and campaigns at the same time. The request would look something like this:

```javascript
// POST /v1/customer/123456789/googleAds:mutate

mutate_operations: [
  {
    campaign_budget_operation: {
      create: { name: "test budget", resource_name: "customers/123456789/campaignBudgets/-1" }
    },
    campaign_operation: {
      create: { name: "test campaign", campaign_budget: "customers/123456789/campaignBudgets/-1", resource_name: "customers/123456789/campaigns/-2" }
    }
  },
  ...etc
]
```

I don't know that there's a way to handle such a request in gRPC. But, it might not be a terrible idea to expose a mutate method that allows raw mutations such as this that otherwise wouldn't be possible. Would you be open to having such a method in the new API?

**Comment by kritzware** [comment]
Hi @jafaircl,

I'm going to do some tests and see if this is possible with gRPC. On the API method, this is definitely something we might consider (depending on the possibilities with gRPC).

**Comment by avermeil** [comment]
Merged in -- will release a new minor version shortly.
