### ISSUE TITLE
Start script failure when installing google-ads-api in a ReactJS application

### ISSUE THREAD

**Issue by Gw1p** [Opteo/google-ads-api#156]
### I'm submitting a ...

[**X** ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

Running `npm install --save google-ads-api` to install the new 4.0.1 version followed by `npm run start` appears to cause the start script to fail (react 16.13.1). 

The error: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`.

### Other information

Stack trace:
```
<--- Last few GCs --->

[17252:000001A0CAC2DEC0]   145502 ms: Mark-sweep 1359.5 (1425.7) -> 1359.3 (1426.2) MB, 2690.1 / 0.0 ms  (average mu = 0.105, current mu = 0.004) allocation failure scavenge might not succeed
[17252:000001A0CAC2DEC0]   147820 ms: Mark-sweep 1359.9 (1426.2) -> 1359.7 (1426.7) MB, 2315.3 / 0.0 ms  (average mu = 0.057, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000003059985C5C1]
    1: StubFrame [pc: 000003059984EA81]
Security context: 0x026f52a9e6e9 <JSObject>
    2: replace [0000026F52A905E9](this=0x03268b6ed8d1 <String[111]: C:\<path_to_project>\node_modules\google-ads-node\build\protos\compiled-resources.js>,0x036e9a1ecfd1 <JSRegExp <String[2]: \\>>,0x01b4a2ab2409 <String[1]: />)
    3: mark [0000034338CC35B1] [C:\Users\anton\React\advertize\a...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF66B85DD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF66B838886 node::MakeCallback+4534
 3: 00007FF66B839200 node_module_register+2032
 4: 00007FF66BB530DE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF66BB5300F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF66BD39804 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF66BD307E6 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF66BD2EE3C v8::internal::ScavengeJob::operator=+17980
 9: 00007FF66BD37B87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF66BD37C06 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF66BE61EA7 v8::internal::Factory::NewFillerObject+55
12: 00007FF66BEDF096 v8::internal::operator<<+73494
13: 000003059985C5C1
```

package.json dependencies:
```
"@auth0/auth0-react": "^1.0.0",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/pickers": "^3.2.10",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "axios": "^0.19.2",
    "formik": "^2.1.5",
    "google-ads-api": "^4.0.1",
    "history": "^5.0.0",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-feather": "^2.0.8",
    "react-helmet": "^6.1.0",
    "react-particles-js": "^3.3.0",
    "react-perfect-scrollbar": "^1.5.8",
    "react-quill": "^1.3.5",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "redux": "^4.0.5",
    "yup": "^0.29.1"
```

**Comment by kritzware** [comment]
Hi @Gw1p, I'm not able to recreate this issue. In a new project, `npm install google-ads-api` works fine for me.

The library is quite large because of the compiled protocol buffers (something which we're thinking about reducing soon), but it shouldn't cause Node to run out of memory. What are the specs on your machine? What node version are you running?

Also, from looking at the `package.json` dependencies you listed it seems like you're trying to install this library in a front-end project. That probably won't work, unless you have some kind of SSR setup, as this library is designed to be run in a back-end Node environment.

**Comment by Gw1p** [comment]
@kritzware you are correct. Installing the package on a server with Node seems to work perfectly fine. It is when installing it to a ReactJS application that the issue arises. I was trying to do the latter to quickly test some requests directly to the Google Ads API while the backend was being sorted out.

Will provide more details on what exactly was causing the issue shortly, in case anyone else runs into the same problem.

**Comment by habdenscrimen** [comment]
I have the same problem. The error occurs on the client initialization:
```ts
const client = new GoogleAdsApi({
  client_id: ``,
  client_secret: ``,
  developer_token: ``,
})
```
