### ISSUE TITLE
Problem fetching ad groups using library v4

### ISSUE THREAD

**Issue by markoffk** [Opteo/google-ads-api#157]
Hello.

After upgrading to your v4 lib I noticed adGroup.list() returns always empty list.
Rolling back to v3 solved issue.

Can you check what happened?

Thanks!

BR, Vlad

**Comment by kritzware** [comment]
Hi @markoffk, thanks for making an issue.

I was only able to recreate this issue when using a test account, which has no metrics. When switching back to an account with metrics, `adGroups.list()` appears to work as usual.

Are you running this on a test account? Does the account have metrics (that could also mean >0 impressions)?

**Comment by markoffk** [comment]
Hi, @kritzware.
I am using normal account (with Basic access) and it has metrics. I would ad that campaigns.list() and adGroupAds.list() returning data. Thats why adGroup.list() returning no data looks strange.

Do you want some debug info from my side?

BR, Vlad

**Comment by markoffk** [comment]
Hi again.
To show more obvious comparison, let me paste this code:

`
const res1 = await this.getGoogleAdsApiCustomer(refreshToken, customerId).report({
            entity: 'ad_group',
            attributes: ['ad_group.id'],
            metrics: [
                'metrics.impressions',
            ],
            constraints: { 'campaign.id': campaignRemoteId },
        });
        console.log('res1', res1);

        const res2 = await this.getGoogleAdsApiCustomer(refreshToken, customerId).adGroups.list({
            constraints: [
                {
                    key: 'campaign.id',
                    op: '=',
                    val: campaignRemoteId,
                },
            ],
        });
        console.log('res2', res2);
`

And the output is:
`
res1 [
  {
    ad_group: {
      resource_name: 'customers/8497700244/adGroups/103494585005',
      id: 103494585005
    },
    metrics: { impressions: 0 }
  }
]
res2 []
`

Did you change something in v4 that aplies certain limitations on impressions?

Thanks

**Comment by kritzware** [comment]
Thanks for those snippets, and I don't believe we made any changes like that. It's always possible Google changed something without declaring it in the release notes, which does happen sometimes. I'll see if I can find any other issues.

In general we'd recommend not using `list` or `get` in production though, instead use the `report` method.

**Comment by markoffk** [comment]
It looks like I found our reason why adGroups.list was returning empty data.
As I understood - adGroups.list use .report underhood and passes all available attributes to .report to obtain as much details as possible in response.
I checked typing definition I just manually passed all fields to report:

`.report({
            entity: 'ad_group',
            attributes: [
                'ad_group.id',
                'ad_group.ad_rotation_mode',
                'ad_group.base_ad_group',
                'ad_group.campaign',
                'ad_group.cpc_bid_micros',
                'ad_group.cpm_bid_micros',
                'ad_group.cpv_bid_micros',
                'ad_group.display_custom_bid_dimension',
                'ad_group.effective_target_cpa_micros',
                'ad_group.effective_target_cpa_source',
                'ad_group.effective_target_roas',
                'ad_group.effective_target_roas_source',
                'ad_group.explorer_auto_optimizer_setting.opt_in',
                'ad_group.final_url_suffix',
                'ad_group.id',
                'ad_group.labels',
                'ad_group.name',
                'ad_group.percent_cpc_bid_micros',
                'ad_group.resource_name',
                'ad_group.status',
                'ad_group.target_cpa_micros',
                'ad_group.target_cpm_micros',
                'ad_group.target_roas',
                'ad_group.targeting_setting.target_restrictions',
                'ad_group.tracking_url_template',
                'ad_group.type',
                'ad_group.url_custom_parameters',
                'bidding_strategy.campaign_count',
                'bidding_strategy.enhanced_cpc',
                'bidding_strategy.id',
                'bidding_strategy.name',
                'bidding_strategy.non_removed_campaign_count',
                'bidding_strategy.resource_name',
                'bidding_strategy.status',
                'bidding_strategy.target_cpa.cpc_bid_ceiling_micros',
                'bidding_strategy.target_cpa.cpc_bid_floor_micros',
                'bidding_strategy.target_cpa.target_cpa_micros',
                'bidding_strategy.target_impression_share.cpc_bid_ceiling_micros',
                'bidding_strategy.target_impression_share.location',
                'bidding_strategy.target_impression_share.location_fraction_micros',
                'bidding_strategy.target_roas.cpc_bid_ceiling_micros',
                'bidding_strategy.target_roas.cpc_bid_floor_micros',
                'bidding_strategy.target_roas.target_roas',
                'bidding_strategy.target_spend.cpc_bid_ceiling_micros',
                'bidding_strategy.target_spend.target_spend_micros',
                'bidding_strategy.type',
                'campaign.ad_serving_optimization_status',
                'campaign.advertising_channel_sub_type',
                'campaign.advertising_channel_type',
                'campaign.app_campaign_setting.app_id',
                'campaign.app_campaign_setting.app_store',
                'campaign.app_campaign_setting.bidding_strategy_goal_type',
                'campaign.base_campaign',
                'campaign.bidding_strategy',
                'campaign.bidding_strategy_type',
                'campaign.campaign_budget',
                'campaign.commission.commission_rate_micros',
                'campaign.dynamic_search_ads_setting.domain_name',
                'campaign.dynamic_search_ads_setting.feeds',
                'campaign.dynamic_search_ads_setting.language_code',
                'campaign.dynamic_search_ads_setting.use_supplied_urls_only',
                'campaign.end_date',
                'campaign.experiment_type',
                'campaign.final_url_suffix',
                'campaign.frequency_caps',
                'campaign.geo_target_type_setting.negative_geo_target_type',
                'campaign.geo_target_type_setting.positive_geo_target_type',
                'campaign.hotel_setting.hotel_center_id',
                'campaign.id',
                'campaign.labels',
                'campaign.local_campaign_setting.location_source_type',
                'campaign.manual_cpc.enhanced_cpc_enabled',
                'campaign.manual_cpm',
                'campaign.manual_cpv',
                'campaign.maximize_conversion_value.target_roas',
                'campaign.maximize_conversions',
                'campaign.name',
                'campaign.network_settings.target_content_network',
                'campaign.network_settings.target_google_search',
                'campaign.network_settings.target_partner_search_network',
                'campaign.network_settings.target_search_network',
                'campaign.optimization_goal_setting.optimization_goal_types',
                'campaign.optimization_score',
                'campaign.payment_mode',
                'campaign.percent_cpc.cpc_bid_ceiling_micros',
                'campaign.percent_cpc.enhanced_cpc_enabled',
                'campaign.real_time_bidding_setting.opt_in',
                'campaign.resource_name',
                'campaign.selective_optimization.conversion_actions',
                'campaign.serving_status',
                'campaign.shopping_setting.campaign_priority',
                'campaign.shopping_setting.enable_local',
                'campaign.shopping_setting.merchant_id',
                'campaign.shopping_setting.sales_country',
                'campaign.start_date',
                'campaign.status',
                'campaign.target_cpa.cpc_bid_ceiling_micros',
                'campaign.target_cpa.cpc_bid_floor_micros',
                'campaign.target_cpa.target_cpa_micros',
                'campaign.target_cpm',
                'campaign.target_impression_share.cpc_bid_ceiling_micros',
                'campaign.target_impression_share.location',
                'campaign.target_impression_share.location_fraction_micros',
                'campaign.target_roas.cpc_bid_ceiling_micros',
                'campaign.target_roas.cpc_bid_floor_micros',
                'campaign.target_roas.target_roas',
                'campaign.target_spend.cpc_bid_ceiling_micros',
                'campaign.target_spend.target_spend_micros',
                'campaign.targeting_setting.target_restrictions',
                'campaign.tracking_setting.tracking_url',
                'campaign.tracking_url_template',
                'campaign.url_custom_parameters',
                'campaign.vanity_pharma.vanity_pharma_display_url_mode',
                'campaign.vanity_pharma.vanity_pharma_text',
                'campaign.video_brand_safety_suitability',
                'customer.auto_tagging_enabled',
                'customer.call_reporting_setting.call_conversion_action',
                'customer.call_reporting_setting.call_conversion_reporting_enabled',
                'customer.call_reporting_setting.call_reporting_enabled',
                'customer.conversion_tracking_setting.conversion_tracking_id',
                'customer.conversion_tracking_setting.cross_account_conversion_tracking_id',
                'customer.currency_code',
                'customer.descriptive_name',
                'customer.final_url_suffix',
                'customer.has_partners_badge',
                'customer.id',
                'customer.manager',
                'customer.optimization_score',
                'customer.pay_per_conversion_eligibility_failure_reasons',
                'customer.remarketing_setting.google_global_site_tag',
                'customer.resource_name',
                'customer.test_account',
                'customer.time_zone',
                'customer.tracking_url_template',
            ],
            constraints: { 'campaign.id': campaignRemoteId },
        })`

And also got empty data. Then I started to remove certain fields - and voila. I got data again. It looks like the reason are these fields:
`'bidding_strategy.campaign_count',
                'bidding_strategy.enhanced_cpc',
                'bidding_strategy.id',
                'bidding_strategy.name',
                'bidding_strategy.non_removed_campaign_count',
                'bidding_strategy.resource_name',
                'bidding_strategy.status',
                'bidding_strategy.target_cpa.cpc_bid_ceiling_micros',
                'bidding_strategy.target_cpa.cpc_bid_floor_micros',
                'bidding_strategy.target_cpa.target_cpa_micros',
                'bidding_strategy.target_impression_share.cpc_bid_ceiling_micros',
                'bidding_strategy.target_impression_share.location',
                'bidding_strategy.target_impression_share.location_fraction_micros',
                'bidding_strategy.target_roas.cpc_bid_ceiling_micros',
                'bidding_strategy.target_roas.cpc_bid_floor_micros',
                'bidding_strategy.target_roas.target_roas',
                'bidding_strategy.target_spend.cpc_bid_ceiling_micros',
                'bidding_strategy.target_spend.target_spend_micros',
                'bidding_strategy.type',`

When you attach bidding_strategy fields - api returns empty data

BR, Vlad

**Comment by Vishwajeet-Saini** [comment]
Any updates on this?

**Comment by kritzware** [comment]
Can you check this still occurs in the latest release of this library?
