### ISSUE TITLE
Large numbers in API response

### ISSUE THREAD

**Issue by basimkhajwal** [Opteo/google-ads-api#158]
### I'm submitting a ...

-   [X] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

Runnign `customer.report` on certain metrics occasionally (but consistently for the same user / query) results in a large, unexpected value for the metric.

I can't tell yet whether this is an error with the underlying API itself or with any parsing that is happening with this library. Has anyone experienced this kind of error?

### Other information

![api_error](https://user-images.githubusercontent.com/5825236/89126704-c0765f00-d4df-11ea-8264-714e5deee4a9.jpeg)

A screenshot of the raw data returned from `customer.report`, the `cost_per_conversion` metric is incorrect in this example.

**Comment by kritzware** [comment]
Hi @basimkhajwal, money values in the Google Ads API are represented as _micro units_. This is how they're sent over when making a request, and we do no additional parsing to them. As an example, $1 in micro units would  be returned from the API as `1000000`. This is also why the metric for spend is called `cost_micros`, and not simply `cost`.

We provide two helper methods in this library for quickly converting micro units:
```js
import { fromMicros, toMicros } from "google-ads-api"

fromMicros(1000000) // 1
toMicros(1) // 1000000
```

**Comment by basimkhajwal** [comment]
Ah, that explains it. Thanks.
