### ISSUE TITLE
listAccessibleCustomer returning objects instead of strings

### ISSUE THREAD

**Issue by felpsio** [Opteo/google-ads-api#159]
### I'm submitting a ...

-   [X ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

When using the function `listAccessibleCustomer` it's returning an array of objects instead of an array of strings.

### Other information

Here's my code:

```
import { GoogleAdsApi, types, enums } from 'google-ads-api'

async function getAllAcounts() {
        const client = new GoogleAdsApi({
        client_id: CLIENT_ID,
        client_secret: CLIENT_SECRET,
        developer_token: DEVELOPER_TOKEN,
      });

     const data = await client.listAccessibleCustomers({refresh_token: token.refresh_token})
    console.info(data)
}
```

value of data:
```
 [
    {
      '0': '2',
      '1': '7',
      '2': '0',
      '3': '6',
      '4': '9',
      '5': '4',
      '6': '1',
      '7': '4',
      '8': '7',
      '9': '6'
   }
]
```
expected:
```
[
  '2706941476',
]
```

version of the library: `^4.0.1`

**Comment by nitendra-yadav** [comment]
Yes, this needs to fixed. I am also facing this issue in older version also. I need to join this objects values like this Object.values(acc).join("") to form a customer_id and then I using it.

**Comment by JaredDahlke** [comment]
expanded on @nitendra-yadav 's solution a bit to format it:

```
const accessibleCustomers = await client.listAccessibleCustomers({
			refresh_token: refreshToken
		})
	
		let formattedCustomers = accessibleCustomers.map((cust) => {
			return Object.values(cust).join('')
		})
```

**Comment by kritzware** [comment]
This is now supported in the latest version. Let us know if you have any more issues.
