### ISSUE TITLE
Upgrade Google Ads to v5

### ISSUE THREAD

**Issue by kritzware** [Opteo/google-ads-api#164]
### I'm submitting a ...

-   [ ] bug report
-   [x] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary
This is an issue for any discussion around the latest v5 release of the Google Ads API. The change notes can be found here: https://developers.google.com/google-ads/api/docs/release-notes

### Other information
We'll start work on this upgrade shortly

**Comment by markoffk** [comment]
Hi. Any news on v5? Thanks!

**Comment by kritzware** [comment]
Hi @markoffk, as v6 is likely to be released next week we'll be holding off on v5 and upgrading straight to v6 when available.

**Comment by nnajdova-git** [comment]
Any updates on v6?

**Comment by kritzware** [comment]
We're working closely with Google for our V6 update, and will have some exciting stuff to share soon 👍

**Comment by kritzware** [comment]
V6.1 of the Google Ads API is now supported in the latest release of this library 🎉
