### ISSUE TITLE
Does customer.customerClients.list() recurse?

### ISSUE THREAD

**Issue by d4ncer** [Opteo/google-ads-api#165]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

I'm interested in fetching all the leaf accounts in an account hierarchy composed of multiple levels of MCC (Managed) accounts. If my top-level accounts (accesed via `listAccessibleAccounts`) are a mix of individual & MCC (Managed) accounts, is it sufficient for me to call `customer.customerClients.list()` at the top level? Or do I need to recurse through the tree?

**Comment by kritzware** [comment]
The latest release of this library no longer supports the `list` method. You should instead use `customer.report`, and we don't perform any type of recursive API calls internally, so you'll need to handle this yourself.
