### ISSUE TITLE
Create a campaign for Video ad (YouTube)

### ISSUE THREAD

**Issue by sunildarji811** [Opteo/google-ads-api#167]
-   [x] bug report
-   [x] feature request
 
When I create a campaign with "youtube" type, it throws me error like "A mutate action is not allowed on this campaign, from this client."

For any other type I can able to create a Campaign but for Video(YouTube) it fails with above error.

How do I solve this?

**Comment by markoffk** [comment]
@sunildarji811 I think GoolgeAds beta API do not support video campaigns yet

**Comment by sunildarji811** [comment]
As Google not supported Video Ads via API yet. closing this down.
