### ISSUE TITLE
Using with service accounts

### ISSUE THREAD

**Issue by BrunoQuaresma** [Opteo/google-ads-api#169]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

Is that possible to use this library using a service account instead of the regular OAuth2 flow?

**Comment by lushu** [comment]
Not likely, Google Ads requires OAuth2. See: https://developers.google.com/google-ads/api/docs/oauth/overview

**Comment by cwohlman** [comment]
Actually I'm pretty certain you can use a service account anywhere you can use OAuth, basically you get a very (forever?) long lived refresh token. Don't know remember where the docs are for that though.

**Comment by alessandro-aglietti** [comment]
@BrunoQuaresma you'll find a working solution here https://github.com/Opteo/google-ads-api/pull/199!

**Comment by kritzware** [comment]
At Opteo we don't use this authentication method so we do not currently support it. However we are aware that this is a desired feature so we will be looking into it in the future.
