### ISSUE TITLE
Get campaign cost by day to display it in a chart

### ISSUE THREAD

**Issue by BrunoQuaresma** [Opteo/google-ads-api#170]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary
I have to read the cost of a campaign over time but the API is returning only the consolidated values. Is that possible to get this data by day to display it in a chart?

**Comment by kritzware** [comment]
Yes, what you're looking for is segments! See here https://developers.google.com/google-ads/api/docs/reporting/segmentation

Using this library, you can specify multiple segments with the `report` method:
```js
customer.report({
    entity: 'campaign',
    metrics: ['metrics.cost_micros'],
    segments: ['segments.date'],
    from_date: '2020-01-01',
    to_date: '2020-04-01',
})
```

Or as `segments.[segment]` with the `query` method:
```js
customer.query(`
    SELECT metrics.cost_micros, segments.date
    FROM campaign
`)
```
