### ISSUE TITLE
Location targeting by radius

### ISSUE THREAD

**Issue by mnikitas** [Opteo/google-ads-api#173]
### I'm submitting a ...

-   [X] feature request

### Summary

I could not find how to select a specific place, address or coordinates and set radius for location targeting.

**Comment by WillCooter** [comment]
To create a regular targeted location you can run:
```ts
await customer.campaignCriteria.create({
    campaign: 'customers/12345/campaigns/45667890',
    location: {
        geo_target_constant: 'geoTargetConstants/20343', // Wales
    },
    negative: false,
    type: enums.CriterionType.LOCATION,
    status: enums.CampaignCriterionStatus.ENABLED,
})
```
To create a radial target you can run:
```ts
await customer.campaignCriteria.create({
    campaign: 'customers/12345/campaigns/45667890',,
    proximity: {
        address: {
            city_name: 'Manchester',
        },
        radius: 10,
        radius_units: enums.ProximityRadiusUnits.MILES,
    },
    negative: false,
    type: enums.CriterionType.PROXIMITY,
    status: enums.CampaignCriterionStatus.ENABLED,
})
```
Under the `proximity` key you can use the following keys to specify the central point of a radial location:
 - `address.city_name`
 - `address.country_code`
 - `address.postal_code`
 - `address.province_code`
 - `address.province_name`
 - `address.street_address`
 - `geo_point.latitude_in_micro_degrees`
 - `geo_point.longitude_in_micro_degrees`
