### ISSUE TITLE
Update Bidding Strategy for Campaign

### ISSUE THREAD

**Issue by bilalakbar** [Opteo/google-ads-api#176]
### I'm submitting a ...
  - [ ] bug report
  - [ ] feature request
  - [ ] question about the decisions made in the repository
  - [x] question about how to use this project
  
This is the code that I am using to create a Campaign

```
// assuming all required properties
const campaign = {};
campaign.target_spend = {
    cpc_bid_ceiling_micros: 1000000
};

const response = await customer.campaigns.create(campaign);
```
It creates the campaign and in response I do have a campaign whose bidding strategy is **target_spend**

```
{
  "resource_name": "customers/9999999999/campaigns/1111111111",
  "bidding_strategy_type": 9,
  "id": 9999999999,
  "name": "Campaign Name",
  "status": 3
} 
```
Now, I want to change this bidding strategy to Maximize Conversions. As per [API Docs](https://developers.google.com/google-ads/api/reference/rpc/v4/Campaign#bidding_strategy), I just have to specify **maximize_conversions** property of type [MaximizeConversions](https://developers.google.com/google-ads/api/reference/rpc/v4/MaximizeConversions).

But MaximizeConversions type has no property. I am not sure what value I have to set it in update object.

I have tried it like below, that did not work.

```
const campaign = {
     "resource_name": "customers/9999999999/campaigns/1111111111",
    "maximize_conversions": ""
};
const response = await customer.campaigns.update(campaign);

```

How to set the **maximize_conversions** property in update object ?

**Comment by kritzware** [comment]
Hi @bilalakbar, thanks for providing such a detailed question!

I've just looked into this and have managed to get it working by using an empty object `{}` for `maximize_conversions`. It's an empty object as no fields are specified by Google for this resource, as seen here: https://developers.google.com/google-ads/api/reference/rpc/v4/MaximizeConversions

I strongly recommend using Typescript if possible so you can make use of our types, which helps a lot with these kind of issues. Here is my working example (for creating a campaign, but update should work the same way):
```ts
import { types } from "google-ads-api"

const conv: types.MaximizeConversions = {}

const campaign: types.Campaign = {
    name: 'New campaign',
    advertising_channel_type: enums.AdvertisingChannelType.SEARCH,
    campaign_budget: 'customers/123/campaignBudgets/123',
    maximize_conversions: conv,
}

// remove validate_only if you want to actually do the mutation
await customer.campaigns.create(campaign, { validate_only: true })
```

**Comment by bilalakbar** [comment]
Thank you for reply. 

Yes, I am using TypeScript and have the available type hints. But as mentioned in the issue, the problem occurs during update.
Using empty object for maximize_conversions throws the following error. Create campaign works fine for me too. But I have to use **target_spent** when creating campaign and then update it to use **maximize_conversions** sometime later.

```
request: {
[Node]     customerId: '9960086105',
[Node]     operationsList: [ [Object] ],
[Node]     partialFailure: false,
[Node]     validateOnly: false
[Node]   },
[Node]   request_id: 'hketCC8gH3fAgAKCj18jQQ',
[Node]   location: 'operations[0]',
[Node]   failure: Error: 3 INVALID_ARGUMENT: Cannot use empty field mask in update operation.
```
This is the sample code that I use for updating a campaign.

```
export const updateCampaign = async (id: number | string, campaign: Campaign) => {
    const result = await customUserMetaModel.findOne({ userId: id as number });
    const customer = getCustomerObj(result, oGoogleAdsApi);

    campaign.maximize_conversions = {};

    const response = await customer.campaigns.update(campaign);

    return response;
};
```

**Comment by bilalakbar** [comment]
On further investigation, I found out that above error occurs, if I try to update only the **bidding_strategy**. If I add some other field like campaign **name** for update, then API call succeeds campaign name gets updated but no affect on **bidding_strategy**. I guess there is some issue with field mask or the generated field mask is empty when I specify **bidding_strategy** to 
`campaign.maximize_conversions = {};`

I cannot dig more in to this issue at the moment. So, I used this operation via REST API and it is working fine for me.

Feel free to close this issue or let me know if you need any more information.

Thank you for the help.

**Comment by jstoeffler** [comment]
I'm having the same problem, I'm trying to change the bidding strategy type of a campaign from `BiddingStrategyType.TARGET_CPA` to `BiddingStrategyType.MAXIMIZE_CONVERSIONS`


First I tried like this: 

      {
          resource_name: my_resource_name,
          bidding_strategy_type: enums.BiddingStrategyType.MAXIMIZE_CONVERSIONS,
      };

and it didn't work. Then I found this issue and I tried adding the `maximize_conversions` field:

      {
          resource_name: my_resource_name,
          bidding_strategy_type: enums.BiddingStrategyType.MAXIMIZE_CONVERSIONS,
          maximize_conversions: {},
      };

but that still doesn't work.
Like @bilalakbar updating the name works.

I would be very thankful of any input on this topic.

**Comment by kritzware** [comment]
Does this still happen in the latest release of this library? Please let us know and re-open this issue if so.

**Comment by oranavrahamiironsrc** [comment]
this issue still happening.
