### ISSUE TITLE
client.listAccessibleCustomers returns ill-formatted data

### ISSUE THREAD

**Issue by raulrene** [Opteo/google-ads-api#178]
### I'm submitting a ...

-   [x] bug report

### Summary

After upgrading from 3.7 to 4.0.2 the `client.listAccessibleCustomers` method returns the customer list values in a strange manner. Each customer is an object with key/value pairs, and you have to join the values together to get the customer ID.

Sample result:
```
[{
    "0": "5",
    "1": "4",
    "2": "5",
    "3": "2",
    "4": "6",
    "5": "2",
    "6": "5",
    "7": "4",
    "8": "7",
    "9": "4"
}]
``` 

This should be: `['5452625474']`

**Comment by JaredDahlke** [comment]
same here, implemented this to format it:
```
const accessibleCustomers = await client.listAccessibleCustomers({
			refresh_token: refreshToken
		})
	
		let formattedCustomers = accessibleCustomers.map((cust) => {
			return Object.values(cust).join('')
		})
```

**Comment by kritzware** [comment]
This should now be resolved in the latest version of this library! Let us know if you have any other issues.
