### ISSUE TITLE
Field 'resource_name' cannot be modified by 'CREATE' operation when trying to create label

### ISSUE THREAD

**Issue by akhtariev** [Opteo/google-ads-api#182]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

Hi! I am trying to create a label as well as CampaignLabel using `mutateResources`. As a result, I am creating a label using reference in the `resource_name` this way:
```
            toMutate.push({
                _resource: 'Label',
                _operation: 'create',
                resource_name: `customers/${customer.cid}/labels/${-10}`,
                name: result.label,
                text_label: { background_color: '#e993eb', description: '' }
            });
```

However, `mutateResources` call fails with the following error: `Field 'resource_name' cannot be modified by 'CREATE' operation.`

CampaingBudget, Campaign, AdGroup and Ad can all be created successfully in my project by utilizing references in recource_name and calling `mutateResources` function

Thanks!

**Comment by kritzware** [comment]
Hi @akhtariev, as far as I can tell this error is valid. The field `resource_name` of type `Label` ([according to the Google Ads API docs](https://developers.google.com/google-ads/api/fields/v5/label#label.resource_name)) is immutable, and here you're trying to set it. The resource name should be retrieved after creation, as it's created on the Google side.

For assigning labels to a campaign, these docs have some insight: https://developers.google.com/google-ads/api/docs/reporting/labels
