### ISSUE TITLE
Label creation via mutate recources (follow-up)

### ISSUE THREAD

**Issue by akhtariev** [Opteo/google-ads-api#183]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

Hi @kritzware ! 

This is a follow-up to [this question](https://github.com/Opteo/google-ads-api/issues/182) . I don't think I have the permissions to comment, thus, the new issue.

Isn't negative `recource_name`  in the context of `mutate resources` just a temporary resource id that is used for assigning labels to other entities such as campaigns?

Here's an example from Opteo's API using the campaign budgets but I think it should be the same with labels. Note that normally, the budget's recource_name is also immutable :
```
const response = await customer.mutateResources([
    // Create new budget
    {
        _resource: 'CampaignBudget',
        _operation: 'create',
        resource_name: 'customers/123/campaignBudgets/-1',
        name: 'My new budget',
        amount_micros: 3000000,
        explicitly_shared: true,
    },
    // Update campaign to use new budget
    {
        _resource: 'Campaign',
        _operation: 'update',
        resource_name: 'customers/123/campaigns/456',
        campaign_budget: 'customers/123/campaignBudgets/-1', // Reference to budget above
    },
    // Delete old budget
    {
        _resource: 'CampaignBudget',
        _operation: 'delete',
        resource_name: 'customers/123/campaignBudgets/123123',
    },
])
```

Thank you!

**Comment by kritzware** [comment]
Does this error still occur in the latest release of this library? The format of `mutateResources` has changed slightly, so make sure to check the README first.
