### ISSUE TITLE
Lazy Loading modules during runtime

### ISSUE THREAD

**Issue by thekip** [Opteo/google-ads-api#184]
### I'm submitting a ...

-   [ ] bug report
-   [x] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

The library is designed this way that no matter do we use something or not everything loaded synchronously during import this library. This might be OK for environments where node has only one cold start during long period of time, but unacceptable for serverless approach where cold starts happened a lot of time, for example, Google Cloud functions / Firebase functions. 

Small example: 

```typescript
    logMemoryFootPrint('before load');
    console.time('load google-ads-api');

    require('google-ads-node');

    console.timeEnd('load google-ads-api');
    logMemoryFootPrint('after load');
```

>  before load 26.63 MB
>  load google-ads-api: 1552.818ms
>  after load 78.95 MB

50mb of RAM just for one library and 1.5 sec added to a cold start. 

### Proposed Solution

Let's take a look on this module https://github.com/Opteo/google-ads-api/blob/master/src/customer.ts

It starts from long lists of imports where import almost everything:

```typescript
import CampaignService from './services/campaign'
import CampaignBudgetService from './services/campaign_budget'
import AdGroupService from './services/ad_group'
import AccountBudgetProposalService from './services/account_budget_proposal'
...
```

And then all services initialized and assigned to a prop inside Customer instance:

```typescript
{
        /* Services */
        campaigns: new CampaignService(cid, client, throttler, 'CampaignService'),
        campaignBudgets: new CampaignBudgetService(cid, client, throttler, 'CampaignBudgetService'),
        adGroups: new AdGroupService(cid, client, throttler, 'AdGroupService'),
        accountBudgetProposals: new AccountBudgetProposalService(
            cid,
            client,
            throttler,
            'AccountBudgetProposalService'
        ),
        accountBudgets: new AccountBudgetService(cid, client, throttler, 'AccountBudgetService'),
}
```

A better approach would be to import and initialize during access to a specific property: 

```typescript
// here we are import only types for static checking
import CampaignService from './services/campaign'; 
    
{
      get campaigns() {
        // do actual import here
        const campaignService: CampaignService = require('./services/campaign').default;
        // probably need some memoization here, to return existing instance instead of creating a new one on each invocation
        return new campaignService(cid, client, throttler, 'CampaignService');
      }
 }
```

**Comment by avermeil** [comment]
Hi @thekip -- This is something we've been very interested in setting up, but we haven't had time to properly explore. We also feel the pain of slow startup times in our development workflow...

I'm not totally sure how to untangle the startup time of the static TS types/enums (which cannot be deferred, I think) vs the startup time of the services, which could totally be deferred.

I would more than welcome any PRs reducing the sheer amount of JS we load upfront!

**Comment by thekip** [comment]
Could you elaborate a bit on that? 

> I'm not totally sure how to untangle the startup time of the static TS types/enums (which cannot be deferred, I think) vs the startup time of the services, which could totally be deferred.

Maybe I will come up with some solution to this problem.

**Comment by kritzware** [comment]
The startup time should now be very quick in the latest release of this library, and we were inspired by your proposed solution, thanks!
