### ISSUE TITLE
Memory usage with many grpc client instances

### ISSUE THREAD

**Issue by papirosko** [Opteo/google-ads-api#185]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary
Hi. I have about 10 000 customers, and i want to fetch their metrics periodically. 

```
...
   constructor(conf) {
        this.api = new GoogleAdsApi({
            client_id: conf.adwords.clientId,
            client_secret: conf.adwords.clientSecret,
            developer_token: conf.adwords.developerToken,
        });
   }
...
   heavilyUsedMethod() {
            const client = this.api.Customer({
                customer_account_id: "...",
                login_customer_id: "...",
                refresh_token: this.refreshToken,
            });
            ...
   }
```

The questions are about grpc client: 
- should I close used client? If yes, then how? Seems, that `grpc.close(client)` affects all other instances (do they share single `$channel`)
- should I cache client instances per customer?

Seems like having too much clients leads to huge memory usage: (6GB after 4 hours with caching client instances). 

Running node 12.19 with `--max-old-space-size=4096`

**Comment by papirosko** [comment]
found simular question: https://github.com/grpc/grpc-node/issues/686

**Comment by kritzware** [comment]
Does this still occur in the latest release of this library? Please re-open if so.
