### ISSUE TITLE
adGroupBidModifiers Resource issue

### ISSUE THREAD

**Issue by sonh1230** [Opteo/google-ads-api#186]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

This is my code that follows your example
`await customer.adGroupBidModifiers.delete('customers/xxxxxxxxxx/adGroupBidModifiers/xxxxxxxxxxxx~30002');`
but, it creates error message 'Error: 3 INVALID_ARGUMENT: Resource was not found.'

**Comment by sogangCSmaster** [comment]
Deleting adgroupCriteria has simillar issue

`
customer.adGroupCriteria.delete(resource_name);
Error: Resource was not found.
`
