### ISSUE TITLE
Add users to crm_based audience

### ISSUE THREAD

**Issue by zselinger** [Opteo/google-ads-api#192]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

Hello. I've been trying for several hours now but failing to add records with hashed email addresses to the update method of the userLists service. I just can't figure out how the update object needs to look like.

Also, I'm confused about whether to use OfflineUserDataJob for this and how to even do it. 

Btw, using the create() method I was able to create that same audience I'm trying to update. 

Any guidance would be appreciated. Thank you.

**Comment by kritzware** [comment]
Can you provide more details on this or some code samples of what you're attempting to run? Please re-open if this issue is still persisting.

**Comment by zselinger** [comment]
Hi @kritzware. Thanks for coming back to me. Basically, I'm not seeing OfflineUserDataJobService in your documentation and I wonder if I can use it. 

I can easily create and update CRM based  audiences with your package and that's great. But I need to add emails to these audiences and that's where I'm stuck.
