### ISSUE TITLE
Confusion over upload of click conversion

### ISSUE THREAD

**Issue by ImmanuelKannan** [Opteo/google-ads-api#193]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X] question about how to use this project

Hi, I have a question regarding the library. The changelog mentions that "Uploading click & call conversions" is a feature that is not yet supported, however the documentation mentions a method called uploadClickConversions. So I'd just like to check if the feature is indeed available? I've attached pictures of the changelog and documentation.

![Screenshot 2021-01-05 at 11 09 13 AM](https://user-images.githubusercontent.com/12892230/103602437-fc0dcd00-4f46-11eb-9e4f-77295d9ec725.png)

![Screenshot 2021-01-05 at 11 11 52 AM](https://user-images.githubusercontent.com/12892230/103602443-fe702700-4f46-11eb-9411-2eae9450cf95.png)

Thanks very much!
Immanuel

**Comment by kritzware** [comment]
This is now supported in the latest release. Let us know if you have any other issues.
