### ISSUE TITLE
Using webpack

### ISSUE THREAD

**Issue by alex25784** [Opteo/google-ads-api#194]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X] question about how to use this project

### Summary
When I am trying to use webpack in order to build my project and use it on AWS Lambda, I am getting a lot of warnings related to _Critical dependency_ of  ./node_modules/grpc.
As I can understand this is related to dynamic importing, I might be wrong.
As a result, the bundled file is very large (above 4MB) and when zipping it and using it on the Lambda i am getting the following error when the Lambda is triggered: `"package.json does not exist at /package.json"`

### Other information
AWS Lambda node version: 12.x

**Stack trace:** 
`  
        Error: package.json does not exist at /package.json,
        at Object.exports.find (/var/task/webpack:/node_modules/node-pre-gyp/lib/pre-binding.js:18:1),
        at Object.<anonymous> (/var/task/webpack:/node_modules/grpc/src/grpc_extension.js:29:1),
        at Object.<anonymous> (/var/task/index.js:40079:30),
        at __webpack_require__ (/var/task/webpack:/webpack/bootstrap:19:1),
        at Object.<anonymous> (/var/task/webpack:/node_modules/grpc/src/client_interceptors.js:144:12),
        at __webpack_require__ (/var/task/webpack:/webpack/bootstrap:19:1),
        at Object.<anonymous> (/var/task/webpack:/node_modules/grpc/src/client.js:35:27),
        at __webpack_require__ (/var/task/webpack:/webpack/bootstrap:19:1),
        at Object.<anonymous> (/var/task/webpack:/node_modules/grpc/index.js:27:14),
        at Object.<anonymous> (/var/task/index.js:2460:30)
`

**Webpack Warnings:**
`
WARNING in ./node_modules/bytebuffer/dist/bytebuffer-node.js 29:38-55
Module not found: Error: Can't resolve 'memcpy' in '/Users/aportnoy/Development/tmp/console/server2/node_modules/bytebuffer/dist'
 @ ./node_modules/protobufjs/dist/protobuf.js
 @ ./node_modules/grpc/index.js 121:19-40
 @ ./node_modules/google-ads-node/build/index.js 19:13-28
 @ ./node_modules/google-ads-api/build/grpc.js 12:26-52
 @ ./node_modules/google-ads-api/build/client.js 19:31-48
 @ ./node_modules/google-ads-api/build/index.js 14:33-52
 @ ./src/index.ts 1:0-46 6:20-32

WARNING in ./node_modules/google-ads-node/node_modules/import-fresh/index.js 28:8-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/google-ads-node/node_modules/cosmiconfig/dist/loaders.js 6:20-43
 @ ./node_modules/google-ads-node/node_modules/cosmiconfig/dist/index.js 6:16-36
 @ ./node_modules/google-ads-node/build/lib/client.js 26:38-60
 @ ./node_modules/google-ads-node/build/index.js 14:13-36
 @ ./node_modules/google-ads-api/build/grpc.js 12:26-52
 @ ./node_modules/google-ads-api/build/client.js 19:31-48
 @ ./node_modules/google-ads-api/build/index.js 14:33-52
 @ ./src/index.ts 1:0-46 6:20-32

WARNING in ./node_modules/grpc/src/grpc_extension.js 32:12-33
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/grpc/index.js 35:11-42
 @ ./node_modules/google-ads-node/build/index.js 19:13-28
 @ ./node_modules/google-ads-api/build/grpc.js 12:26-52
 @ ./node_modules/google-ads-api/build/client.js 19:31-48
 @ ./node_modules/google-ads-api/build/index.js 14:33-52
 @ ./src/index.ts 1:0-46 6:20-32

WARNING in ./node_modules/node-pre-gyp/lib/pre-binding.js 20:22-48
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/grpc/src/grpc_extension.js 26:13-52
 @ ./node_modules/grpc/index.js 35:11-42
 @ ./node_modules/google-ads-node/build/index.js 19:13-28
 @ ./node_modules/google-ads-api/build/grpc.js 12:26-52
 @ ./node_modules/google-ads-api/build/client.js 19:31-48
 @ ./node_modules/google-ads-api/build/index.js 14:33-52
 @ ./src/index.ts 1:0-46 6:20-32

WARNING in ./node_modules/node-pre-gyp/lib/util/versioning.js 17:20-67
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/node-pre-gyp/lib/pre-binding.js 3:17-53
 @ ./node_modules/grpc/src/grpc_extension.js 26:13-52
 @ ./node_modules/grpc/index.js 35:11-42
 @ ./node_modules/google-ads-node/build/index.js 19:13-28
 @ ./node_modules/google-ads-api/build/grpc.js 12:26-52
 @ ./node_modules/google-ads-api/build/client.js 19:31-48
 @ ./node_modules/google-ads-api/build/index.js 14:33-52
 @ ./src/index.ts 1:0-46 6:20-32
`

**webpack.config.js:**
`const path = require("path")
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin")

module.exports = {
  mode: "production",
  entry: "./src/index.ts",
  resolve: {
    extensions: [".js", ".jsx", ".json", ".ts", ".tsx"],
  },
  output: {
    libraryTarget: "commonjs",
    path: path.join(__dirname, "dist"),
    filename: "index.js",
  },
  target: "node",
  module: {
    rules: [
      {
        // Include ts, tsx, js, and jsx files.
        test: /\.(ts|js)x?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: "cache-loader",
            options: {
              cacheDirectory: path.resolve(".webpackCache"),
            },
          },
          "babel-loader",
        ],
      },
    ],
  },
  plugins: [new ForkTsCheckerWebpackPlugin()],
}`

**package.json:**
`
"devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-typescript": "^7.12.7",
    "babel-loader": "^8.2.2",
    "cache-loader": "^4.1.0",
    "fork-ts-checker-webpack-plugin": "^6.1.0",
    "google-ads-api": "^4.0.3",
    "typescript": "^4.1.3",
    "webpack": "^5.12.3",
    "webpack-cli": "^4.3.1"
  },`

**Comment by mabranon** [comment]
We are not building on lambda and are seeing this issue as well.

**Comment by arditti** [comment]
I'm facing the same issue (webpack for lambda), at the moment I ditched webpack due to this issue

**Comment by kritzware** [comment]
We no longer use grpc but instead the recommended grpc-js library. Unfortunately the package size can't be reduced that much as the Google Ads API uses a massive amount of protos. I believe other client libraries face similar issues.
