### ISSUE TITLE
Upgrade Google Ads to v6

### ISSUE THREAD

**Issue by rado196** [Opteo/google-ads-api#195]
Upgrade Google Ads to v6

**Comment by kritzware** [comment]
Hi @rado196, we're working on this currently! 🆗

**Comment by rosslavery** [comment]
Just wanted to chime in and offer any help in getting this done.

Sunset for Ads API v4 is June 2021 which is getting a little too close for comfort :)

**Comment by kritzware** [comment]
Hi @rosslavery, we appreciate your offer very much.

We're in fact very close to finishing the V6 branch, which isn't published on this repo yet as we originally started working on it under NDA with Google. We'll publish the branch soon, and will have definitely released v6 long before June!

One exciting feature I can reveal about this new version is that it will support everything from the Google Ads API, including some of the highly requested services which we previously didn't support that well, such as the ConversionUploadService or the KeywordPlanIdeaService.

**Comment by kritzware** [comment]
V6.1 is now available in the latest release of this library! 🎉
