### ISSUE TITLE
MediaFiles Creation OAuth 2 access token Error

### ISSUE THREAD

**Issue by amineinaloo** [Opteo/google-ads-api#197]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

I want to add video ad by api ,base of docs before that i should create a mediaFiles and use it's source_name in video ad creation but i'm missing somthing and getting error:
Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
i have user 'OAuth 2 access token' but there is nowhere to set it in api.
### Other information

        const mediaFile = {
            type: enums.MediaType.VIDEO,
            video: {
                youtube_video_id: '########'
            }
        }
        customer.mediaFiles.create(mediaFile);

please help me with that.i'm stuck on it.

**Comment by cwohlman** [comment]
I believe you need to supply a refresh token when you create the customer

```js
const client = new GoogleAdsApi({
  client_id: clientId,
  client_secret: clientSecret,
  developer_token: adwordsDeveloperToken,
});

const customer = client.Customer({
  customer_account_id: accountId,
  refresh_token: refresh_token, // <-- here
});
```
