### ISSUE TITLE
feed_item.policy_infos TS interface doesn't match API response

### ISSUE THREAD

**Issue by rosslavery** [Opteo/google-ads-api#198]
### I'm submitting a ...

-   [x] bug report

### Summary

In V3 -> V4, `FeedItem` `policy_topic_entries` was seemingly renamed to `policy_topic_entries_list` on Google's side (?). TS interfaces in the library still reflect the old name, while some of the docs display correctly, and others are incorrect.

I'd make a PR but I suspect much of this is auto-generated and not human-generated.

### Details

**FeedItem Interface - Incorrect:**
```
export interface FeedItem {
    // ...other props
    policy_infos?: {
        placeholder_type_enum?: PlaceholderType;
        feed_mapping_resource_name?: string;
        review_status?: PolicyReviewStatus;
        approval_status?: PolicyApprovalStatus;
        policy_topic_entries?: PolicyTopicEntry[];
        validation_status?: FeedItemValidationStatus;
        validation_errors?: undefined[];
        quality_approval_status?: FeedItemQualityApprovalStatus;
        quality_disapproval_reasons?: FeedItemQualityDisapprovalReason[];
    }[];
}
```

**Docs Page - Incorrect (List of Props for FeedItem)**
![image](https://user-images.githubusercontent.com/656884/106187205-4adc0a80-6173-11eb-91f3-1ce19aeeb4ec.png)

**Docs Page - Correct (Example Response on right pane)**

```
const feed_item = {
  // ... other props
  policy_infos: [
    {
      // ... other props
      policy_topic_entries_list: []
    },
  ]
}
```

**API Response - Correct**:
![image](https://user-images.githubusercontent.com/656884/106187655-e79ea800-6173-11eb-95a7-e82ae171eba1.png)

**Comment by kritzware** [comment]
Thanks for reporting this! It should be fixed in the new version and will match the official docs (which seems to not include the `_list` part in >v6) which we'll be released soon 👍

**Comment by kritzware** [comment]
The latest release of this library should resolve this issue!
