### ISSUE TITLE
How to use optimization_goal_setting

### ISSUE THREAD

**Issue by arditti** [Opteo/google-ads-api#200]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X] question about how to use this project

### Summary

Google Ads UI give you the ability to set "Campaign Goal". the options are: "Sales" / "Leads" / "Website Traffic" /  "Brand Awarenesses".

Looking into the library documents and code, I assume the i control this section using `optimization_goal_setting` key on the campaign level object.

I could find any docs or code which explain how to use this feature.

Is this feature supported? thanks.

**Comment by kritzware** [comment]
This would be best asked over at the official Google Ads API forums. Once you know more about this Google Ads UI setting, it should be clearer how to do it with our library.
