### ISSUE TITLE
Is this query a GET or SEARCH request in the API?

### ISSUE THREAD

**Issue by obto** [Opteo/google-ads-api#204]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [x] question about how to use this project

### Summary

When running the report below, does this library create a [GET](https://developers.google.com/google-ads/api/docs/best-practices/quotas#get_requests) request or a [SEARCH](https://developers.google.com/google-ads/api/docs/best-practices/quotas#search_requests) request?

Hoping its a SEARCH request so my developer token isn't limited to the 1000 req/day that GET requests have.

Thanks!

```javascript
let ad_group_ads_results = await customer.report({
  entity: 'ad_group_ad',
  attributes: [
    'ad.id',
    'ad.expanded_text_ad.description',
    'ad.expanded_text_ad.description2',
    'ad.expanded_text_ad.headline_part1',
    'ad.expanded_text_ad.headline_part2',
    'ad.expanded_text_ad.headline_part3',
    'ad.expanded_text_ad.path1',
    'ad.expanded_text_ad.path2',
    'ad.expanded_text_ad.path2',
    'segments.date',
  ],
  metrics: [],
  order_by: 'segments.date',
  sort_order: 'DESC',
  limit: 100,
});
```

**Comment by Zikoel** [comment]
The `report` method will be traduced in a `GET` if you want a `SEARCH` you need to use the `reportStream` method (you can see more details [here](https://opteo.com/dev/google-ads-api/#using-report-stream)). I'm not 100% sure but this is my conclusion after a lot of tests.

**Comment by obto** [comment]
Did some digging and debugging of the source code and found that both `report` and `reportStream` use the `Search` and `SearchStream` grpc functions of the [GoogleAdsService](https://developers.google.com/google-ads/api/reference/rpc/v6/GoogleAdsService). 

Which as mentioned on the [Access levels page](https://developers.google.com/google-ads/api/docs/access-levels#standard_access), has unlimited usage for Standard tokens.

So my query above would be counted as a `SEARCH` request and not a `GET`.

Going to keep this issue open for a few days in case the devs have time to review this. Just in case I'm getting something totally mixed up in my code delving

**Comment by kritzware** [comment]
The above is correct! `report` and `reportStream` internally use `Search` and `SearchStream`, so the unlimited usage for standard tokens applies.
