### ISSUE TITLE
How the release system works

### ISSUE THREAD

**Issue by Zikoel** [Opteo/google-ads-api#218]
Hi guys I can't see anymore the tag relative to certain released version. The last available tag is for release `v4.0.3` from version `v4.0.4-beta0` to `v5.0.0` (included) there aren't tags! Something is changed on how you release this library?

**Comment by kritzware** [comment]
Hi @Zikoel, thanks for pointing this out. Looks like we forgot to setup a Git tag for the latest release `v5.0.0.`. We'll make sure to continue with these in the future. It's definitely available on [NPM](https://www.npmjs.com/package/google-ads-api) though.

**Comment by Zikoel** [comment]
Hi guys I know that this is a very minor problem for you but I want reopen this task as a reminder! To have the version tagged and not only on the commit comment increase a lot the readability of the code base in my opinion.
