### ISSUE TITLE
(5.0.0) Some types no longer exported without equivalents elsewhere

### ISSUE THREAD

**Issue by rosslavery** [Opteo/google-ads-api#221]
Hope you don't mind me flooding the issue tracker.

Having read the [notes here](https://github.com/Opteo/google-ads-api/pull/201), I understand that the `types` export has been removed and replaced by the others to match the official API exports. There are some types that are still specific to the library that have no Google-provided equivalent.

We have the following interface in our pre-v5 code:

```
import { types } from 'google-ads-api';

export interface AdsDateRange {
  date_constant?: types.DateConstant;
  from_date?: string;
  to_date?: string;
}
```

We use this in a few places to spread it into the `report()` options, e.g.:

```
export async function getGoogleRows(
  dateRange: AdsDateRange
) {
  const metrics = [
    'metrics.conversions',
    'metrics.clicks'
  ];

  return await adsApi.report({
    entity: 'customer',
    attributes: ['customer.id', 'customer.currency_code'],
    metrics,
    ...dateRange
  });
}
```

Unfortunately `types.DateConstant` has nothing to replace it. I've noticed it's still exported from `node_modules\google-ads-api\build\src\types.d.ts` but not further exported by the main package: `export { CustomerOptions, ReportOptions, MutateOperation, Constraint, Constraints, } from "./types";`

**Comment by WillCooter** [comment]
Hi Ross,
In this version of the API we wanted to keep the exported modules as small as possible. However it is still possible to access the date constant type from the report options like so:
```ts
type DateConstant = ReportOptions["date_constant"];
```
If you require `DateConstant` to be defined, then you can wrap it in the `NonNullable` generic utility type:
```ts
type DateConstant = NonNullable<ReportOptions["date_constant"]>;
```
