### ISSUE TITLE
(5.0.0) Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by rosslavery** [Opteo/google-ads-api#222]
Hi all (again) :)

Receiving the following issue when performing any API request:

```
{ TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (/usr/app/node_modules/google-ads-node/node_modules/@grpc/grpc-js/build/src/channel.js:69:19)
    at new Client (/usr/app/node_modules/google-ads-node/node_modules/@grpc/grpc-js/build/src/client.js:58:36)
    at new ServiceClientImpl (/usr/app/node_modules/google-ads-node/node_modules/@grpc/grpc-js/build/src/make-client.js:58:5)
    at GrpcClient.createStub (/usr/app/node_modules/google-ads-node/node_modules/google-gax/build/src/grpc.js:235:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'Channel credentials must be a ChannelCredentials object' }
```

My [Google-fu](https://github.com/firebase/firebase-tools/issues/2207) [says](https://github.com/firebase/firebase-js-sdk/issues/3196) it's related to mismatching `@grpc/grpc-js` versions. But `npm list @grpc/grpc-js` shows:

```
+-- @google-cloud/automl@2.4.0
| `-- google-gax@2.10.3
|   `-- @grpc/grpc-js@1.2.9
`-- google-ads-api@5.0.0
  +-- google-ads-node@4.0.0
  | `-- google-gax@2.10.3
  |   `-- @grpc/grpc-js@1.2.9
  `-- google-gax@2.10.3
    `-- @grpc/grpc-js@1.2.9
```

**Comment by rosslavery** [comment]
As an update, even after removing _all_ Google-related dependencies besides `google-ads-api`, still getting the same error:

```
`-- google-ads-api@5.0.0
  +-- google-ads-node@4.0.0
  | `-- google-gax@2.10.3
  |   `-- @grpc/grpc-js@1.2.9
  `-- google-gax@2.10.3
    `-- @grpc/grpc-js@1.2.9
```

**Comment by rosslavery** [comment]
Further update after more research. Appears to be related to duplicate versions of `google-auth-library` being installed.

```
+-- google-ads-api@5.0.0
| +-- google-ads-node@4.0.0
| | `-- google-gax@2.10.3
| |   +-- @grpc/grpc-js@1.2.9
| |   | `-- google-auth-library@6.1.6
| |   `-- google-auth-library@7.0.2
| +-- google-auth-library@6.1.6
| `-- google-gax@2.10.3
|   +-- @grpc/grpc-js@1.2.9
|   | `-- google-auth-library@6.1.6  deduped
|   `-- google-auth-library@7.0.2
`-- google-auth-library@7.0.2
```

To test a fix I used [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions) to force all sub-dependencies to use `google-auth-library@7.0.2` and now it's working.

Seems directly related to: https://github.com/grpc/grpc-node/issues/1695

Seems like an upstream issue so probably safe to close (?). Not sure if there's anything you'd can or would like to do on your side to handle this.

**Comment by kritzware** [comment]
Nice, glad you figured it out @rosslavery. You're right though that this seems like an issue in a dependency we're using, so I think it's fair to close this issue for now. We can re-open it if this continues to occur after a future grpc-js release.

**Comment by felixmosh** [comment]
I've got this error as well, 
```
yarn why google-auth-library
├─ @google-cloud/common@npm:4.0.2
│  └─ google-auth-library@npm:8.4.0 (via npm:^8.0.2)
│
├─ google-ads-api@npm:11.1.0
│  └─ google-auth-library@npm:7.14.1 (via npm:^7.1.0)
│
├─ google-gax@npm:3.5.0
│  └─ google-auth-library@npm:8.4.0 (via npm:^8.0.2)
│
└─ google-gax@npm:3.5.2
   └─ google-auth-library@npm:8.4.0 (via npm:^8.0.2)
```
Should I update google-auth-library:7.14.1 to v8?

**Comment by cynosureabu** [comment]
same here. I tried to use 'override' to force a version of google-auth-library to be 7.14.1  in package.json, but it still has the same error

├─┬ google-ads-api@12.0.1
│ ├─┬ google-ads-node@10.0.0
│ │ └─┬ google-gax@3.5.2
│ │   └── google-auth-library@7.14.1 invalid: "^8.0.2" from node_modules/google-gax
│ ├── google-auth-library@7.14.1 deduped
│ └─┬ google-gax@3.5.2
│   └── google-auth-library@7.14.1 invalid: "^8.0.2" from node_modules/google-ads-api/node_modules/google-gax
└─┬ googleapis@47.0.0
  ├── google-auth-library@7.14.1 invalid: "^5.6.1" from node_modules/googleapis
  └─┬ googleapis-common@3.2.2
    └── google-auth-library@7.14.1 invalid: "^5.6.1" from node_modules/googleapis-common
