### ISSUE TITLE
Can't create Local Ad

### ISSUE THREAD

**Issue by md16289390** [Opteo/google-ads-api#226]
Here is my code - 

```
const ad_group_ad = {
      ad_group: 'customers/7566295805/adGroups/124393432051',
      status: 2,
      ad: {
        final_urls: ['my-website-url'],
        local_ad: {
          headlines: [{ text: 'Local Ad headline' }],
          descriptions: [{ text: 'Local Ad descriptions' }],
          call_to_actions: [{ text: 'Buy Now' }],
          logo_images: [{asset: 'customers/7566295805/assets/13509720139' }],
          marketing_images: [{asset: 'customers/7566295805/assets/13519411331' }],
          videos: [{asset: 'customers/7566295805/assets/13509605983'}],
        }
      }
    };

    const result = await customer.adGroupAds.create(ad_group_ad);

```
I am facing this error when i am trying to create this ad ->

**{
    "code": {
        "adError": 1
    },
    "errorMessage": "The error code is not in this version."
}**

Moreover, assets are also visible in UI in recent images or videos when i try to create ad from UI.

Can you help to solve this ? This is urgent

**Comment by kritzware** [comment]
Which version of `google-ads-api` are you using? 

Passing a single resource into the `create` methods is no longer supported. It must always be an array, like this:
```ts
await customer.adGroupAds.create([ad_group_ad]);
```

**Comment by md16289390** [comment]
I am using this version 
`"google-ads-api": "^4.0.3"`

**Comment by md16289390** [comment]
Even after updating the version now to latest 5.0.1, I am creating ad like this -

`const client = new GoogleAdsApi({
      client_id: 'client id',
      client_secret: 'secret',
      developer_token: 'token'
    });

    const customer = client.Customer({
      customer_id: '756-629-5805',
      login_customer_id: '832-065-9346', // Optionally provide a login-customer-id
      refresh_token:
        'token'
    });
    const ad = new resources.Ad({
      local_ad: {
        headlines: [{ text: 'Local Ad headline' }],
        descriptions: [{ text: 'Local Ad descriptions' }],
        call_to_actions: [{ text: 'Buy Now' }],
        logo_images: [{asset: 'customers/7566295805/assets/13509720139' }],
        marketing_images: [{asset: 'customers/7566295805/assets/13519411331' }],
        videos: [{asset: 'customers/7566295805/assets/13509605983'}],
      },
      final_urls: ["my-website-url"],
      type: enums.AdType.LOCAL_AD,
    });
    
    const adGroupAd = new resources.AdGroupAd({
      status: enums.AdGroupAdStatus.ENABLED,
      ad_group: 'customers/7566295805/adGroups/124393432051',
      ad,
    });
     const { results } = await customer.adGroupAds.create([adGroupAd]);
    `
    
    It keeps giving me this error ->
    
    `{
    "statusCode": 200,
    "data": {
        "errors": [
            {
                "error_code": {
                    "header_error": "INVALID_LOGIN_CUSTOMER_ID"
                },
                "message": "The login customer id header '832-065-9346' could not be validated."
            }
        ]
    }
}`

which is weird because with older version it was working correct.

Also, I am on development mode - so i have one test manager account (customer id - 832-065-9346) and under that test google ads account (customer id - 756-629-5805)

Don't know why this error is coming ?

Please help me solve this issue

**Comment by kritzware** [comment]
v5 doesn't support passing in customer ids with dashes anymore, so the customer ids should be formatted like so:
```ts
customer_id: '7566295805',
login_customer_id: '8320659346',
```

For a full list of the breaking changes in v5, [see here](https://github.com/Opteo/google-ads-api/pull/201#issuecomment-788933339).

**Comment by md16289390** [comment]
Ah, got it- Thanks it worked.

But am facing issue for marketing images - `AdError.MISSING_REQUIRED_IMAGE_ASPECT_RATIO`

API's as well are little slow and time taking now.

Also, when we would get the latest documentation for v5 because as of now all other functions are not working correct like asset.list() etc.
How quick the versions will come in future just to make sure that we can rely on the package ?

**Comment by md16289390** [comment]
I am keep getting this error for marketing images when am creating ad- even i have uploaded the image asset of 800*418(1.91 and when i try to create ad from dashboard using that image - it is working there. 
It has these properties  - 
- Image (1 ratio selected)
1.91:1
- File name
Indian Food curry butter chicken
- Dimensions
800 × 418

Error through API - 

`
{
    "statusCode": 200,
    "data": {
        "errors": [
            {
                "error_code": {
                    "ad_error": "UNKNOWN"
                },
                "message": "The error code is not in this version.",
                "trigger": {
                    "string_value": "1.91 x 1"
                },
                "location": {
                    "field_path_elements": [
                        {
                            "field_name": "operations",
                            "index": 0
                        },
                        {
                            "field_name": "create"
                        },
                        {
                            "field_name": "ad"
                        },
                        {
                            "field_name": "local_ad"
                        },
                        {
                            "field_name": "marketing_images"
                        },
                        {
                            "field_name": "asset"
                        }
                    ]
                },
                "details": {
                    "unpublished_error_code": "AdError.MISSING_REQUIRED_IMAGE_ASPECT_RATIO"
                }
            },
            {
                "error_code": {
                    "image_error": "ASPECT_RATIO_NOT_ALLOWED"
                },
                "message": "The aspect ratio of the image is not allowed.",
                "trigger": {
                    "string_value": ""
                },
                "location": {
                    "field_path_elements": [
                        {
                            "field_name": "operations",
                            "index": 0
                        },
                        {
                            "field_name": "create"
                        },
                        {
                            "field_name": "ad"
                        },
                        {
                            "field_name": "local_ad"
                        },
                        {
                            "field_name": "marketing_images",
                            "index": 0
                        },
                        {
                            "field_name": "asset"
                        }
                    ]
                }
            }
        ]
    }
}
`

**Comment by md16289390** [comment]
Is there any update on this ?

Can we have some Dev support for this package ?

**Comment by WillCooter** [comment]
Sorry for the late reply. These kind of issues are best directed to the [official google ads api forum](https://groups.google.com/g/adwords-api).
