### ISSUE TITLE
Cannot pass location Id for linking GMB specific locations while creating Campaign

### ISSUE THREAD

**Issue by md16289390** [Opteo/google-ads-api#232]
While creating campaign - it is only taking GOOGLE_MY_BUSINESS(2) as ENUM in local_campaign_setting.

What does that mean ?

Can we pass location Ids of GMB to link specific locations ?

**Comment by kritzware** [comment]
We'd recommend contacting Google Ads API support or using the official forum for these kind of questions. We don't offer Google Ads support.
