### ISSUE TITLE
uploadClickConversions returning "Invalid customer ID ''." error after 5.0.3 update

### ISSUE THREAD

**Issue by FelipeMicali** [Opteo/google-ads-api#233]
Hello!

After the v3 API deprecation the uploadClickConversions stopped working, and today I've updated the library to the latest version 5.0.3, but this function stopped working.

I've tested the "const campaigns = await googleAdsApiCustomer.report({..." function and it's working, I'm able to retrieve all campaigns from our account, so the "client" is correct.

This is the error response the the library is returning when I try to use any customer function:
```ts
GoogleAdsFailure {
  errors: [
    GoogleAdsError {
      error_code: [ErrorCode],
      message: "Invalid customer ID ''."
    }
  ]
}
```
This is strange, because the other functions are working.

This is the function that I'm executing for uploading the conversions (variables are in uppercase):
```ts
const result = await customer.conversionUploads.uploadClickConversions(
        [
          {
            gclid : GCLID,
            conversion_action: `customers/${CUSTOMER_ACCOUNT_ID}/conversionActions/${CUSTOMER_CLICK_CONVERSION_ACTION}`,
            conversion_date_time: CONVERSION_DATE_TIME,
            conversion_value: CONVERSION_VALUE ,
            currency_code: 'BRL'
          }
        ],
        {
          partial_failure: true
        },
        true
      )
```
Could you please help me solve this problem?

Thank you!

**Comment by kritzware** [comment]
Hi @FelipeMicali, these kind of services are slightly more advanced so I'll give you an example of how to use it. The parameter type has also changed to match the official docs, so you should be passing in an object like this: https://developers.google.com/google-ads/api/reference/rpc/v6/UploadClickConversionsRequest

We'll have examples for these specific methods in the future when we upgrade our docs.

I'm pretty sure something like this should work, assuming the `conversions` array you're passing is correct:
```ts
import { services } from "google-ads-api"

const result = await customer.conversionUploads.uploadClickConversions(
    [
        new services.UploadClickConversionsRequest({
            customer_id: customer.credentials.customer_id,
            conversions: [
                {
                    gclid: GCLID,
                    conversion_action: `customers/${CUSTOMER_ACCOUNT_ID}/conversionActions/${CUSTOMER_CLICK_CONVERSION_ACTION}`,
                    conversion_date_time: CONVERSION_DATE_TIME,
                    conversion_value: CONVERSION_VALUE,
                    currency_code: 'BRL',
                },
            ],
        }),
    ],
    {
        partial_failure: true,
    }
)
```

**Comment by kritzware** [comment]
I'm going to close this issue, but feel free to re-open if the above didn't solve the issue.

**Comment by WillCooter** [comment]
Solved by @artyom-ivanov here: https://github.com/Opteo/google-ads-api/issues/247
