### ISSUE TITLE
quota limits for `.report` method?

### ISSUE THREAD

**Issue by arditti** [Opteo/google-ads-api#236]
Hello all,

We start getting `quota` errors from several positions on our code.
All the relevant code use `.report` method - which as i understand DOES have sort of limitations.

According to Google API docs, the limitation is 15,000 request OR unlimited according to the account type.
https://developers.google.com/google-ads/api/docs/best-practices/quotas#:~:text=Unlike%20daily%20operations%2C%20the%20limits,1%2C000%20get%20requests%20per%20day.
https://developers.google.com/google-ads/api/docs/access-levels

Our account is set as `Standard access`  - which should have unlimited requests.

I thought maybe the issues is `.report` is using Google's `get` quota (which is limited to 1000 daily requests) instead of `search` which is unlimited.

Any thoughts or advise on this subject?

Thanks!

**Comment by kritzware** [comment]
Hi @arditti, all customer (not the Customer Service) level methods such as `report`, `query` and `reportStream` all internally use `search` (or `searchStream`). They are not using `get` for exactly the reasons you list.

Perhaps in your code you're doing more requests than expected and reaching rate limits?

**Comment by arditti** [comment]
@kritzware thanks for the quick response!

Do you have information about rate limits? other than daily ones?

**Comment by WillCooter** [comment]
@arditti you'll be able to find more information on rate limits [here](https://developers.google.com/google-ads/api/docs/best-practices/quotas).
