### ISSUE TITLE
FR: expose a stream-type result from 'reportStream' besides current 'async generator'

### ISSUE THREAD

**Issue by lushu** [Opteo/google-ads-api#237]
Thanks for the quick fix. However, I have other thoughts regarding the performance:

- The function is named as 'reportStream' while it returns a 'generator'.
- In some (if not most) cases, we use 'reportStream' to pipe it to a writeStream instead of handling the data in the position where we get the reports. Google Ads reports are offered based on single Ads account and the most common use case is to handle all Ads accounts reports from a same MCC account at the same time. So we need to download those reports first.
- Transforming stream to generator and later generator back to streams seems to be a waste. 
- Can we offer two different functions at 'google-ads-api' level, e.g. 'reportGeneratorOnStream' which returns current generator and 'reportStream' to return the original stream?

Thank you.

_Originally posted by @lushu in https://github.com/Opteo/google-ads-api/issues/229#issuecomment-797804796_

**Comment by lushu** [comment]
I found another performance issue due to this design.

I used `Readable.from` to convert current `generator` to `stream`. However, due to [this](https://github.com/Opteo/google-ads-api/blob/f2ed2721c635929fa0848f2f174d42b5bc60067f/src/customer.ts#L160), there is a `yield` for each object (line). So the number of 'data' events in the new stream would be as many as of the number of lines in the report.

For a report of 160k lines, it will trigger the error `4 DEADLINE_EXCEEDED: Deadline exceeded` when I tried to dump it to Cloud Storage. I guess the error was triggered by too many and too frequent writing request to Cloud Storage.

So could you help to look at this FR? Thank you.

**Comment by WillCooter** [comment]
Hi Lushu,
These are both good observations, we will look into this as soon as possible. I like the idea of a separate `reportGeneratorOnStream` method to return an iterable, while the `reportStream` method returns the stream itself. Hopefully we can get hooks to work well with this.
Once this has been done I think we will recommend using `reportStream` for larger queries that are likely to cause issues such as the `4 DEADLINE_EXCEEDED: Deadline exceeded` error.

**Comment by leopragi** [comment]
I guess this FR will take sometime. Is it possible to retry on `DEADLINE_EXCEEDED: Deadline exceeded` error.

https://github.com/googleads/google-ads-python/issues/87#issuecomment-491323499

**Comment by lushu** [comment]
Hi @WillCooter,

Is there any updates on this? Thank you.

**Comment by WillCooter** [comment]
Hopefully we'll be getting round to it this week

**Comment by leopragi** [comment]
@WillCooter 

Quick question: what is the recommended way to fetch reports with > 1 million data?

Stream: Google suggesting this if reports >

**Comment by WillCooter** [comment]
@leopragi `reportStream` currently calls `searchStream` internally, however as @lushu mentioned above the async generator has it's limits. The next release will include a new function that returns the raw stream from `searchStream` so that you can handle the events manually for large requests such as > 1 million rows.

**Comment by leopragi** [comment]
@WillCooter Thanks!

 But calling library's `reportStream` returns error for large reports while Google's REST API `searchStream` succeeds without any error. Is it possible to fix it anytime soon? I don't have any problem with it being a iterator. 

@lushu mentioned `DEADLINE_EXCEEDED: Deadline exceeded` error is actually from his implementation on converting to streams and trying to dump on cloud storage. Not that one I m facing I guess.

But my problem is for larger reports, `reportStream` throwing `DEADLINE_EXCEEDED: Deadline exceeded` while Google's `searchStream` succeeds.

**Comment by leopragi** [comment]
Is there any alternative for Ads API `search` in this library? Because, I want to get the results on each pagination instead of getting it after completion.

**Comment by leopragi** [comment]
@WillCooter please let me know if you have any update on the former one?

**Comment by WillCooter** [comment]
@leopragi As mentioned above, we are working on a new method to return the raw data stream. Using this you will be able to watch for data events (each containing a chunk of 10,000 rows), and deal with them as you see fit. This will be our recommended method of dealing with larger queries.

**Comment by WillCooter** [comment]
We have just released `v5.1.2` of the library containing some of the requested changes. The main things you will be interested in are:
 - A new method `reportStreamRaw` which returns the raw stream straight from Google, allowing you to handle the `data`, `error` and `end` events manually. We have also exposed our parsing method as you may still wish to parse the raw results. @lushu 
 - The timeout for all query functions has been set to 1 hour (Google's recommendation), which has solved the issue of the `DEADLINE_EXCEEDED` errors for very large queries. @leopragi 

If you find any more problems please continue to make issues.

**Comment by lushu** [comment]
@WillCooter Thanks Will. I was testing on this new version and I would like to have your opinions on this issue: when I use `report` or `reportStream`, the result is clean and only contains fields that I put in the `ReportOptions`. However, if I use `reportStreamRaw`, the result contains a lot of fields that are not in `ReportOptions` with the NULL value. 

My questions are: 

1. I guess it was caused by the lower level lib `google-ads-node`. I knew there was a very big difference between the current `google-ads-node` and previous one. However, is this expected behaviour? 

2. How does current `google-ads-api` adapter to that? And is it possible to let `reportStreamRaw` behave in that way as well?

3. Will there be a big performance impact in this kind of transformation back and forth?
