### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by issacg** [Opteo/google-ads-api#24]
When running the default examples, I get an error "customer.search is not a function"

However, customer.query works fine.

I'm not sure if this is a documentation bug or a software bug...

**Comment by mateuszjanusz** [comment]
Hi @issacg, 

That looks like the documentation bug. The `search` method was renamed to `query` since v1 and it doesn't exist anymore. 

Sorry about that, I'll make sure we update our docs asap.

Thanks!
