### ISSUE TITLE
GAQL (customer.query) is not working on the version 5.1.1

### ISSUE THREAD

**Issue by wilderperozo** [Opteo/google-ads-api#241]
Hi There.

I made a GAQL query (customer.query) using the version [5.1.0](https://www.npmjs.com/package/google-ads-api/v/5.1.0) and it was working pretty well, I just updated to the version [5.1.1](https://www.npmjs.com/package/google-ads-api/v/5.1.1) and now is showing me the next error: 

![image](https://user-images.githubusercontent.com/9922225/111714278-5668bb00-881f-11eb-875e-c466ae8f1d2f.png)

My code:

```
const customer = client.Customer({
                            customer_account_id: id,
                            login_customer_id: id, 
                            refresh_token: id,
                        });

const results = await customer
    .query(
      `SELECT ad_group_ad.ad.expanded_text_ad.headline_part1,
          ad_group_ad.ad.expanded_text_ad.headline_part2,
          ad_group_ad.ad.expanded_text_ad.headline_part3,
          ad_group_ad.ad.final_urls,
          ad_group_ad.ad.id,
          ad_group_ad.ad.expanded_text_ad.description,
          ad_group_ad.ad.expanded_text_ad.description2,
          ad_group.labels,
          ad_group.name,
          ad_group_ad.policy_summary.approval_status,
          ad_group_ad.policy_summary.review_status,
          ad_group_ad.status,
          ad_group.status,
          ad_group.id,
          campaign.name
      FROM ad_group_ad
      WHERE ad_group_ad.ad.id IN (${ids})`,
    )
    .catch(console.error);

```

**Comment by Zikoel** [comment]
From commit flow I can see there is only one [commit](https://github.com/Opteo/google-ads-api/commit/d2d234a7a09ed2b0b5ad5920a25bd2cf863a1e4f)  between version `5.1.0` and `5.1.1` and seems not related to your error! If you rollback the error disappear ?

**Comment by wilderperozo** [comment]
> From commit flow I can see there is only one [commit](https://github.com/Opteo/google-ads-api/commit/d2d234a7a09ed2b0b5ad5920a25bd2cf863a1e4f) between version `5.1.0` and `5.1.1` and seems not related to your error! If you rollback the error disappear ?

Thanks for your answer. 

Yeah, after rollback the error disappear

**Comment by WillCooter** [comment]
Hi @wilderperozo, are you still experiencing these issues in the latest version of the library (`v5.1.2`)?
