### ISSUE TITLE
Querying customInterests does not return any value

### ISSUE THREAD

**Issue by arditti** [Opteo/google-ads-api#242]
Hey,

Im trying to work with audiences in mu campaigns, 
But I fail to understand how to connect and query audiences.

If i understand the Docs correctly, connect an audience to an ad groups is done by setting `ad_group_criterion` with `custom_intent` value.

And query for existing audiences, it should be done using `customer.customInterests.list()`.

1. when setting `ad_group_criterion` with `custom_intent` - I'm getting the following error:
```
This operation is not permitted on this campaign type
```

2.  when query for all audiences, i always get an empty results, even though there are some existing on my account.

Can you please advise on how should I work with audiences? am i looking at the right place?

**Comment by WillCooter** [comment]
Hi @arditti. This looks like an issue with campaign types and audience conflicts. These kind of issues are best directed to the [official google ads api forum](https://groups.google.com/g/adwords-api).
