### ISSUE TITLE
uploadConversionAdjustments - conversion_adjustments[0].order_id - "Too short."

### ISSUE THREAD

**Issue by Kevin-M-Zaleo** [Opteo/google-ads-api#246]
### What I'm trying to do

Upload a GoogleConversionAdjustmentRequest to retract/cancel out a formerly uploaded conversion from a conversionAction, identified by gclid and timestamp, since no order_id was provided during the initial upload

### What I did

created UploadConversionAdjustmentsRequest with a single ConversionAdjustment
verified UploadConversionAdjustmentsRequest with no errors
upload conversionAdjustment

### Expected result

Retraction of the specified conversion

### What actually happens 

`{
  "results": [],
  "partial_failure_error": {
    "details": [
      {
        "type_url": "type.googleapis.com/google.ads.googleads.v6.errors.GoogleAdsFailure",
        "value": {
          "type": "Buffer",
          "data": [
            "just replaced"
          ]
        }
      }
    ],
    "code": 3,
    "message": "Too short., at conversion_adjustments[0].order_id"
  }
}`

### Function

```
export const retractGoogleConversionUpload = async (
    customerId: string,
    googleCustomerZaleo: Customer,
    conversionActionResourceName: string,
    adjustmentDateTime: string,
    gclid: string,
    originalConversionDateTime: string,
) => {
    const original = validateGoogleDateTime(originalConversionDateTime)
    const adjustment = validateGoogleDateTime(adjustmentDateTime)

    if (!original || !adjustment) {
        throw new Error("Provided timestamps don't have the required format. Aborting")
    }

    const gclidDateTimePair = services.GclidDateTimePair.create({
        gclid: gclid,
        conversion_date_time: original,
    })

    const conversionAdjustment = services.ConversionAdjustment.create({
        adjustment_date_time: adjustment,
        adjustment_type: ConversionAdjustmentType.RETRACTION,
        conversion_action: conversionActionResourceName,
        gclid_date_time_pair: gclidDateTimePair,
    })

    const conversionAdjustmentRequest = services.UploadConversionAdjustmentsRequest.create({
        customer_id: customerId,
        partial_failure: true,
        validate_only: true,
        conversion_adjustments: [conversionAdjustment],
    })

    console.log(JSON.stringify(services.ConversionAdjustment.verify(conversionAdjustment))) // null

    return await googleCustomerZaleo.conversionAdjustmentUploads.uploadConversionAdjustments(
        conversionAdjustmentRequest,
    )
}
```

### What i tried

- modifying the adjustment date
- change validate_only to `false`
- changed `conversionAdjustment` to be a variable, to use the `conversion_identifier` attribute
- adding different values as `order_id`
- using the `IConversionAdjustment` type instead
- reinstalling and updating the npm package

### Question

Is this a known bug or am I doing something wrong?
Is there a known solution to this?
What else could I try or what shall I change?

TIA

**Comment by WillCooter** [comment]
Hi @Kevin-M-Zaleo. We are aware of this issue and are waiting on a fix in the [node-js gapic library](https://github.com/googleapis/gapic-generator-typescript). Once this has been done we will release with the fix.

**Comment by advance512** [comment]
@Kevin-M-Zaleo what does the verify() call do?
