### ISSUE TITLE
Sharing OAuth with googleapis client?

### ISSUE THREAD

**Issue by issacg** [Opteo/google-ads-api#25]
Hi!

My application also uses other Google APIs.  Ever since starting to use this library, I'm getting 401 errors from other Google libraries using the [official Google API](https://github.com/googleapis/google-api-nodejs-client).

I'm going to start, but hypothesizing that I'm going to see that each library is using the client id/secret and refresh token to generate their own access tokens which are flapping and locking one another out.  

Would it be possible to allow this library to get and manage the access_token, at least, via the [official Google Auth library for nodejs](https://github.com/googleapis/google-auth-library-nodejs)?  That way it can (hopefully) be managed by a singleton instance dealing with the OAuth-level authentication (or any Google-supported authentication) and play nicer with the rest of the ecosystem?

**Comment by avermeil** [comment]
Hi :)

I'm not sure I understand how our access tokens would be interfering with the other google libraries. Is there some kind of limit to how many `access_tokens` that can be generated per `refresh_token`? Are you using the same refresh token with other libraries?

The entire code for getting `access_tokens` in this library is in the `refreshAccessToken()` function: https://github.com/Opteo/google-ads-api/blob/bec0d5273f6d344e44c403d22e5e9cd0011fcce9/src/token.ts#L65

As you can see, there's really not much to it, and it's pretty self-contained.

I would like to understand the problem better before making any changes. As a test, perhaps you could fork this library and replace the `refreshAccessToken()` function with an equivalent call to the official Google OAuth library, to see if that helps with your 401 errors?

**Comment by issacg** [comment]
As I said originally, the flapping is just a hypothesis.  I posted early in the thought that one of the maintainers might know something that I have yet to discover.  Given that that's not the case, I'll happily keep digging on my side and  update here. Thanks for the rapid responses!

**Comment by avermeil** [comment]
No problem at all -- let us know if you find anything!

**Comment by issacg** [comment]
I can't prove (or disprove) my hypothesis, so closing this.
