### ISSUE TITLE
Manager's customer id  must be set in the "login-customer-id" header

### ISSUE THREAD

**Issue by akhtariev** [Opteo/google-ads-api#251]
Hi there!

This error started appearing for me half of the time:
![image](https://user-images.githubusercontent.com/34196718/114077973-398f3880-985d-11eb-99ca-bec228b2ad81.png)

No changes to the API calls were made and they were working for a few months. I am on version 4.0.2. Should I upgrade to resolve this?

Any help is greatly appreciated. Thank you!

**Comment by WillCooter** [comment]
Hi @akhtariev. We'd recommend updating to the latest version of the api (`v5.1.2`). If this issue persists after you have updated and fixed any [breaking changes](https://github.com/Opteo/google-ads-api/pull/201#issuecomment-788933339) then feel free to reopen/create a new issue.
