### ISSUE TITLE
How to get location details from location_id?

### ISSUE THREAD

**Issue by VasudevHarshal-123** [Opteo/google-ads-api#252]
I'm able to extract location id from the URL eg: location_id=9301955. I have not found a way in the documents to make an API call to get the corresponding location.

**Comment by WillCooter** [comment]
You need to query the `geo_target_constant` report, e.g.:

```ts
const location = await customer.report({
    entity: 'geo_target_constant',
    attributes: [
        'geo_target_constant.canonical_name',
        'geo_target_constant.country_code',
        'geo_target_constant.id',
        'geo_target_constant.name',
        'geo_target_constant.parent_geo_target',
        'geo_target_constant.resource_name',
        'geo_target_constant.status',
        'geo_target_constant.target_type',
    ],
    constraints: {
        'geo_target_constant.id': 9301955,
    },
})
```

**Comment by VasudevHarshal-123** [comment]
@WillCooter  I have a follow-up question. The location ids are constants that correspond to a location then why do I need to make a customer instance for this. Shouldn't this be independent?

**Comment by WillCooter** [comment]
The purpose of this library is to make it easier to query Google Ads for data, and for all GAQL queries you will need customer credentials. 

However if this is an issue then you could use [this CSV provided by Google](https://developers.google.com/adwords/api/docs/appendix/geotargeting) containing all of their targetable locations and their corresponding data.
