### ISSUE TITLE
Get list of client account under custumer account

### ISSUE THREAD

**Issue by elfilalime** [Opteo/google-ads-api#253]
Hello,

I have been reading the API documentation and going through the code, but sorry i don't find a way to retrieve the list of client for each customer account (customer account that i can retrieve using : await client.listAccessibleCustomers(refreshToken); )

So to clarify i want this list : 

![image](https://user-images.githubusercontent.com/31894280/114427144-134dfd80-9bbb-11eb-8a58-b85567ab1eaf.png)

I found this in the old documentation : customer.customerClients.list() but didn't work in the new release.

Thank you too much for you time and the work that you gave to make this api useful 🙏

**Comment by wturyn** [comment]
I'm facing the same problem - could we, please, get an answer?

**Comment by wturyn** [comment]
I've got it:
1. Create a customer with `login_customer_id` and `customer_id` set as, for example, M1.
2. Run query:
```
{
  "entity": "customer_client",
  "attributes": [
    "customer.id",
    "customer_client.id",
    "customer_client.descriptive_name"
  ]
}
```

**Comment by WillCooter** [comment]
@wturyn has got the right idea. The list methods no longer exist and `report` should be used instead.
