### ISSUE TITLE
There are some problems for using atomic mutation on V5

### ISSUE THREAD

**Issue by mmjvn** [Opteo/google-ads-api#256]
Hello Developers
After moving to api version 5, i got some problems with atomic mutation :(
1. Can not create extensionFeedItems: We can not use temporary id --> It is Google side problem
2. google-ads-api bug: https://github.com/Opteo/google-ads-api/blob/master/src/types.ts at line 119
  operation?: "create" | "update" | "delete"; 
--> it should be : operation?: "create" | "update" | "remove"; as Google has changed delete method to remove. You have changed but forgot that code.
3. Event fixing (2), I still have problem with remove, now i got error "Resource name '[object Object]' is malformed: expected 'customers/{customer_id}/campaignBudgets/{campaign_budget_id}'." when trying to remove campaign budget. The same problem happens with other resource.
Please have a look. Thank you

**Comment by mmjvn** [comment]
More information for section 3.
It would not work when we use MutateOperation :
const removeCampaignBuget: resources.ICampaignBudget = {
       resource_name: 'customers/XXXXXX/campaignBudgets/YYYYYY'
}
const removeCampaignBudgetOperation : MutateOperation<resources.ICampaignBudget> = {
      entity: "campaign_budget",
      resource: removeCampaignBuget,
      operation: "remove"
    }
customer.mutateResources([removeCampaignBudgetOperation])
    
but it would work when i use type of any like this
const removeCampaignBudgetOperation : any = {
      entity: "campaign_budget",
      resource: 'customers/XXXXX/campaignBudgets/YYYYY',
      operation: "remove"
}
customer.mutateResources([removeCampaignBudgetOperation])

**Comment by rosslavery** [comment]
Just +1-ing to say this was the only issue we encountered during our migration to the latest version. Fix like @mmjvn mentioned is to remove typing from our operations and replace `delete` (what this library expects) with `remove` (what Google expects).

**Comment by WillCooter** [comment]
Point 2 has been fixed in the latest version of this library (`v8.0.0`). We will take up point 3 with our Google contacts next week.
