### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by zth** [Opteo/google-ads-api#258]
Hi! Are there examples anywhere of error handling with this library? In terms of what error can appear where, and how to figure out what type of error I'm getting. 

I'm trying to handle auth related errors (basically, I want to do a few things if anything errors because of auth). How would I go about doing that with this library?

**Comment by WillCooter** [comment]
Hi @zth. You can find references for the google-ads errors [here](https://developers.google.com/google-ads/api/docs/release-notes) in their docs. Select v6 → errors in the side bar.

**Comment by zth** [comment]
@WillCooter excellent, thank you very much!

**Comment by kritzware** [comment]
We've just merged in a tiny example of error handling with this library @zth, see it [here in the readme](https://github.com/Opteo/google-ads-api#error-handling).
