### ISSUE TITLE
Invalid customer ID

### ISSUE THREAD

**Issue by AshwanthMadhav** [Opteo/google-ads-api#259]
const { GoogleAdsApi } = require('google-ads-api');
           const client = new GoogleAdsApi({
                client_id: clientId,
                client_secret: clientSecret,
                developer_token: developerToken,
            })

            let customer = client.Customer({
                customer_account_id: clientCustomerId,
                login_customer_id: clientCustomerId, // Optionally provide a login-customer-id
                refresh_token: refreshToken,
            })

            let customerClients = await customer.report({
                entity: 'customer_client',
                attributes: [
                    'customer.resource_name',
                    'customer_client.manager',
                    'customer.descriptive_name',
                    'customer_client.client_customer',
                ],
            })

I couldn't get the details using this format in recent days. It works fine beforea few months ago.

**Comment by kritzware** [comment]
Hi @AshwanthMadhav, what error exactly are you running into? Please can you share the output of running this code. I can't tell from here but if your customer IDs contain `-` then it won't work:
```
// bad 
const customerId = "123-456-7890"

// good
const customerId = "1234567890"

```

**Comment by AshwanthMadhav** [comment]
Getting Error:

GoogleAdsFailure {
 errors: [
  GoogleAdsError {
   error_code: [ErrorCode],
   message: "Invalid customer ID ''."
  }
 ]
}

**Comment by AshwanthMadhav** [comment]
Customer ID look like this.

const customerId = "1234567890"

**Comment by kritzware** [comment]
This is because some customer fields have been renamed, such as `customer_account_id` now being `customer_id`. See our examples here: https://github.com/Opteo/google-ads-api#create-a-customer-instance

**Comment by AshwanthMadhav** [comment]
@kritzware Okay. Let me check

**Comment by AshwanthMadhav** [comment]
Thanks. Its working.
