### ISSUE TITLE
FR: New alternative for customer.report (Pagination Control)

### ISSUE THREAD

**Issue by leo-pragi** [Opteo/google-ads-api#261]
Currently customer.report paginates automatically and gives all result at the end. But I need a function to have the data once it does the request and it continues next pagination.

Something likes this
```
async function* reportRaw(reportOptions) {
    let response = await restCall(`/search`, query) // generated using reportOptions
    while(true) {
         yield response.data
         if(!response.pageToken) return []
         response = await restCall(`/search`, response.pageToken)
    }
}
```

Note: Using searchStream with large accounts (like 3 million ads) is eating up memory. I m think this as alternative.

**Comment by WillCooter** [comment]
Hi @leo-pragi, thanks for the feature request. Unfortunately this is not something we will be adding to the api at the risk of it becoming bloated with overly specific functions. I'd suggest instead that you reconsider the reports you are making. If it contains 3 million ads then it is advisable to use constraints in the report options to make your queries more specific.
