### ISSUE TITLE
how I can assign a goal for my compaign using a web service call ???

### ISSUE THREAD

**Issue by noureddineammar** [Opteo/google-ads-api#266]
Is there a way to put a goal for the campaign created using an api ??.
Because I have not found how to do that, on the other hand if I navigate to the graphical interface of google ads, I find that my campaign does not have a goal, then I can select a goal from the list displayed (prospects , sales, etc ...)
my question is: how I can assign a goal for my compaign using a web service call ???

**Comment by kritzware** [comment]
Hi @noureddineammar, please direct this issue over to the official [Google Ads API forum](https://groups.google.com/g/adwords-api). We only provide support for this library here and not general Google Ads advice.
