### ISSUE TITLE
How to work with developer_token when connecting to multiple accounts?

### ISSUE THREAD

**Issue by mikhail-monchak** [Opteo/google-ads-api#267]
Hi there 👋

I'm building a service that processes Google Ads data. The flow is following:
- the client web application requests a user with access to Google Ads API (`https://www.googleapis.com/auth/adwords` scope) and gets a `refresh_token`
- the server has `client_id` and `client_secret` of registered Google project

But `GoogleAdsApi` class also needs `developer_token` to be provided. Am I correct in saying that the token is needed to access a particular Google Ads API only and does not make any sense in my scenario? If not, what developer_token should I use then?

Will appreciate your thoughts! 👍

**Comment by WillCooter** [comment]
@mikhail-monchak Sorry for the slow response. You will need a `developer_token` to use the Google Ads API. Information on acquiring this token can be found [here](https://developers.google.com/google-ads/api/docs/first-call/dev-token).
