### ISSUE TITLE
getEnumString undefined / not implemented.

### ISSUE THREAD

**Issue by ChrisAlvares** [Opteo/google-ads-api#270]
According to the docs, there should be a function called getEnumString, but when adding the method, it returned undefined: 

```
const {getEnumString} = require('google-ads-api');
console.log(getEnumString) //returns undefined
```

Docs: https://opteo.com/dev/google-ads-api/#utilities

**Comment by kritzware** [comment]
Hi @ChrisAlvares, our docs are outdated at the moment and we recommended following the README here for now. We're working on upgrading and building new content for them soon.

The `getEnumString` helper was removed in a previous release. The same functionality can be achieved by using the enums themselves, like so:
```ts
    const enumValue = enums.AdvertisingChannelType.SHOPPING // 4
    const enumString = enums.AdvertisingChannelType[enumValue] // "SHOPPING"
```
