### ISSUE TITLE
customer mutateResource returns type

### ISSUE THREAD

**Issue by Zikoel** [Opteo/google-ads-api#278]
Hi guys,

I'm experimenting with the v5 (v5.2.0) of this library and I found an unexpected type: The return type of `Customer` class method `mutateResources` declare as return type a `Promise<services.MutateGoogleAdsResponse>` but during a debug session this is not what I see. I see a tuple of three elements.

![tuple-result](https://user-images.githubusercontent.com/6044789/120629283-f40a7880-c465-11eb-8e1e-0181156ecf8c.png)

at the same time accessing with the correct public property of the response class we have an undefined property

![result-mutate](https://user-images.githubusercontent.com/6044789/120629479-24521700-c466-11eb-83e7-6351122e66bc.png)

To reproduce the error try to perform any atomic mutation and inspect the result

**Comment by Zikoel** [comment]
I tried to go more deeper to see where I land...

the trip start from my code where I'm writing `const result = await customerClient.mutateResources(cleanedResources)`

the method return object is this

https://github.com/Opteo/google-ads-api/blob/9b878a9b37d8f1d569af746155ba6ee3488a5f80/src/customer.ts#L411-L414

and the service is coming from here

https://github.com/Opteo/google-ads-api/blob/9b878a9b37d8f1d569af746155ba6ee3488a5f80/src/customer.ts#L405-L408

the method `buildMutationRequestAndService` declare as return type for service `services.GoogleAdsService` that is coming from

https://github.com/Opteo/google-ads-api/blob/9b878a9b37d8f1d569af746155ba6ee3488a5f80/src/protos/index.ts#L13
https://github.com/Opteo/google-ads-api/blob/9b878a9b37d8f1d569af746155ba6ee3488a5f80/src/protos/index.ts#L1

Here finish my trip following the types... is difficult to follow but seems ok. Come back to the method `buildMutationRequestAndService` we have
https://github.com/Opteo/google-ads-api/blob/9b878a9b37d8f1d569af746155ba6ee3488a5f80/src/service.ts#L184-L186
and here we have
https://github.com/Opteo/google-ads-api/blob/9b878a9b37d8f1d569af746155ba6ee3488a5f80/src/service.ts#L85-L99

Now here there are some types overwriting and I suspect that here something was broken with the last update but unfortunately I can't go deeper for now! Maybe this trigger some ideas to someone more smart than me with this lib.

**Comment by WillCooter** [comment]
@Zikoel Well spotted, you are correct. We will fix this when we get round to upgrading to Google Ads API V8.

**Comment by WillCooter** [comment]
@Zikoel Thanks for your patience. This has been fixed in the latest version of the library (`v8.0.0`).
