### ISSUE TITLE
Invalid customer ID ''.

### ISSUE THREAD

**Issue by stefan-rode** [Opteo/google-ads-api#279]
I use version 5.2.0 of the package and would like to upload a click conversion, but unfortunately I always get the error message:
```ts
"errorMessage": {
    "errors": [
        {
            "error_code": {
                "request_error": "INVALID_CUSTOMER_ID"
            },
            "message": "Invalid customer ID ''."
        }
    ],
    "request_id": "8mdifVT1ymeTIdKLZ3mmuQ"
} 
```
My code looks like this:
```ts
const { GoogleAdsApi, services } = require('google-ads-api');

async function upload() {
    const client = new GoogleAdsApi({
      client_id: 'aaaaaa.apps.googleusercontent.com',
      client_secret: 'secret',
      developer_token: 'another secret',
    });
    
    const customer = client.Customer({
      customer_id: '1234567890',  // no hyphens
      refresh_token: 'refresh token',
    });
    
    const conversion = new services.ClickConversion({
      gclid: 'some gclid',
      conversion_action: '987654321',
      conversion_date_time: '2021-06-08 07:58:35+00:00',
      conversion_value: 123,
      currency_code: 'EUR',
    });
    
    const result = await customer.conversionUploads.uploadClickConversions([conversion]);
}
```
I already read this issue here: https://github.com/Opteo/google-ads-api/issues/259
and this works for me:
```ts
let customerClients = await customer.report({
        entity: 'customer_client',
        attributes: [
            'customer.resource_name',
            'customer_client.manager',
            'customer.descriptive_name',
            'customer_client.client_customer',
        ],
    })
```
So I'm pretty sure that the `customer_id` I use is correct.
I also tried to set `login_customer_id`, but that also doesn't help.

What am I doing wrong ? Is the way I create the click conversion correct ?

**Comment by Batuhan-Akkaya** [comment]
Same problem in version 5.2.0

**Comment by WillCooter** [comment]
@stefan-rode Sorry for the late reply. Your code appears to be correct. Do you get this error when you use other features in the API such as a report query? Or is the error only thrown for the click conversion upload service?

**Comment by MitulGedeeya** [comment]
@WillCooter same error occuring here and also there are other issues are being occurring as documentation for > v5 is not available. When I update from v4.0 to v5.0 of google-ads-api we are facing issues

**Comment by LuKaa** [comment]
Same issue here but with a report request. 

The request has been working under 4.*

Any ideas where I should start troubleshooting this ?

**Comment by WillCooter** [comment]
Are you certain that you are following [Google's API Call Structure](https://developers.google.com/google-ads/api/docs/concepts/call-structure?hl=en#request_headers) correctly? For example, have you removed all hyphens (`-`) from your login customer id?

**Comment by LuKaa** [comment]
@WillCooter thank you for your support.

I have been using it with the hyphens since that's what I used to do in the old version. But I have tested it without them now and I still get the same error.

Just to make sure my google client credentials are actually still working I made a request like this and I do get a correct response:

```js
const {GoogleAdsApi, types, enums} = require('google-ads-api');

const client = new GoogleAdsApi({
    client_id: process.env.GOOGLE_ADS_CLIENT_ID,
    client_secret: process.env.GOOGLE_ADS_SECRET,
    developer_token: process.env.GOOGLE_ADS_DEVELOPER,
});
let refreshToken ="**********";

const customers = await client.listAccessibleCustomers(refreshToken);
```

But basic requests that used to work are failing now. For example, I need to check if a customer is a manager or not and I used to do this like that.  

```js

let customer = client.Customer({
                            customer_account_id: endAdvertiser.replace(/-/gm,''), // tested both with and without hyphens
                            refresh_token: refresh_token,
                            access_token: access_token,
                        });
let webproperties= await customer.get(customerClientID);
```

Also queries and reports are failing with the same error.

```js
let customerClientList = await customer.query(`SELECT customer.id,
                                                                                  customer_client.id,
                                                                                  customer_client.resource_name,
                                                                                  customer_client.time_zone,
                                                                                  customer_client.descriptive_name,
                                                                                  customer_client.currency_code,
                                                                                  customer_client.manager,
                                                                                  customer_client.test_account,
                                                                                  customer_client.client_customer
                                                                           FROM customer_client
                                                                           LIMIT 100`);
```

```js
const campaignsReport = await client.Customer(CustomerObj).report({
                entity: 'campaign',
                attributes: ['campaign.id', 'campaign.name', 'campaign.serving_status', 'campaign.status', 'campaign.start_date', 'campaign.end_date', 'campaign_budget.amount_micros'],
            });
```

**Comment by LuKaa** [comment]
I found the error in my request.

I was using **customer_account_id** instead of **customer_id**. 

Requests are working now but customer.get(id) is still not working. I will find a workaround for this I guess the function got deprecated in v5 or v8

**Comment by WillCooter** [comment]
@LuKaa Well found! The `get` function is still available, however you will need to use the customer resource name instead of the id. The customer resource name looks like this: `customers/123456789`, where the numerical value is the customer id.
