### ISSUE TITLE
Mutation operation 'create' doesn't work for customer creation

### ISSUE THREAD

**Issue by douglas-pires** [Opteo/google-ads-api#280]
### Overview

Hi friends 👋🏻 

In our project, when I try to use the master client account to create more sub accounts. We tried to use `mutateResources` method like below:

```typescript
  const master_client = googleClient.Customer({
    customer_id: "string",
    refresh_token: "string",
    login_customer_id: "string",
    linked_customer_id: "string"
  });

  master_client.mutateResources([
    {
      entity: "customer",
      resource: {
        // resource info here
      },
      operation: "create"
    }
  ]);
```

However, it's going to throw an error saying that operation field was not provided. The following code will work though:

```typescript
const master_client = await googleClient.Customer({
    customer_id: "string",
    refresh_token: "string",
    login_customer_id: "string",
    linked_customer_id: "string"
  });

  const settings = new services.CreateCustomerClientRequest(
    // settings passed here
  );
```

The code is making requests to a test account.

Package version: 5.2.0

**Comment by eliotik** [comment]
@kritzware could you please also check this one? I checked payload and it seems the same issue as for BillingSetup - it has only `\n\ncustomer_id� (` where customer_id is a number of customer we use for client api.

**Comment by WillCooter** [comment]
@douglas-pires @eliotik Does this still happen in the latest version of the library (`v8.1.0`)?
