### ISSUE TITLE
TypeError: Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by MosheOz** [Opteo/google-ads-api#281]
After creating an instance of client and customer getting this issue:
TypeError: Channel credentials must be a ChannelCredentials object

Any ideas?

**Comment by rosslavery** [comment]
I encountered this error:

https://github.com/Opteo/google-ads-api/issues/222

While I needed to temporarily force resolutions, the real fix was updating other Google dependencies (@google-cloud, firebase, etc) to their latest versions.
