### ISSUE TITLE
Uprade to v6

### ISSUE THREAD

**Issue by brantian** [Opteo/google-ads-api#282]
I've just received an email from Google alerting that v4 and v5 APIs will be suspended by June 23th and that my application is still making requests to some of those APIs. 

How do I update the Google Ads API version on my application using this library?

Thanks

**Comment by kritzware** [comment]
Hi @brantian, you can simply upgrade to the latest version of this library and you'll be on V7 of the Google Ads API.

**Comment by brantian** [comment]
Great, thank you!
