### ISSUE TITLE
AdGroup - Targeting expansion - how to mutate and query

### ISSUE THREAD

**Issue by arditti** [Opteo/google-ads-api#288]
Hey guys,

Im looking to query and mutate AdGroup's Targeting expansion settings (using Google's UI is adGroup->settings->Targeting expansion).

I've been looking anywhere in the documents, and in the code itself, but i could find any clue about it.

What have i missed?

**Comment by kritzware** [comment]
Hi @arditti, you're more likely to get a good answer for this over at the [official Google Ads API forum](https://groups.google.com/g/adwords-api?pli=1). I'm not sure myself but from a quick look found the [`TargetingSetting`](https://developers.google.com/google-ads/api/reference/rpc/v8/TargetingSetting) field of the [`AdGroup`](https://developers.google.com/google-ads/api/reference/rpc/v8/AdGroup) resource. Perhaps this is relevant?

**Comment by arditti** [comment]
> Hi @arditti, you're more likely to get a good answer for this over at the [official Google Ads API forum](https://groups.google.com/g/adwords-api?pli=1). I'm not sure myself but from a quick look found the [`TargetingSetting`](https://developers.google.com/google-ads/api/reference/rpc/v8/TargetingSetting) field of the [`AdGroup`](https://developers.google.com/google-ads/api/reference/rpc/v8/AdGroup) resource. Perhaps this is relevant?

Appreciate your reference to the group. 
Just posted the question there as well - Once i get an answer ill post it here as well.

**Comment by kritzware** [comment]
If you get an answer as to where it's located in the API (and if it's possible currently) I'll happily show you how to do it with our library 👍

**Comment by arditti** [comment]
@kritzware 
So after a [discussion](https://groups.google.com/g/adwords-api/c/mRxeOdArfq8/m/GXrnqtDuAAAJ) with Google guys, it seems like this sections still not supported by their API.

Thanks (again) for the help here
