### ISSUE TITLE
getEnumString is not a function

### ISSUE THREAD

**Issue by MitulGedeeya** [Opteo/google-ads-api#299]
We are at critical point. can anyone give me a link of the list of the breaking changes while moving from v4.0 to v5.0 of google-ads-api?

**Comment by WillCooter** [comment]
@MitulGedeeya  The breaking changes can be found [here](https://github.com/Opteo/google-ads-api/pull/201#issuecomment-788933339).

**Comment by MitulGedeeya** [comment]
@WillCooter I found there are many changes which are not available in documentation. can you please have a look there or point me if possible?

**Comment by WillCooter** [comment]
`getEnumString` is no longer a function in this library. The string value of an enum can now be found on the enum itself, accessed with the numeric enum value.

```ts
const numericValue = enums.CampaignStatus.ENABLED // 2
const stringValue = enums.CampaignStatus[numericValue] // "ENABLED"
```

Are there any other changes that you don't understand?

**Comment by MitulGedeeya** [comment]
@WillCooter Thanks for this quick reply. closing it now :)
