### ISSUE TITLE
TypeError: Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by sunildarji811** [Opteo/google-ads-api#303]
Getting error like below with updated version.

 `   "google-ads-api": "^8.0.0",`

I have already checked [#222 ](https://github.com/Opteo/google-ads-api/issues/222) but didn't help 

`TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (..\node_modules\@grpc\grpc-js\build\src\channel.js:75:19)       
    at new Client (..\node_modules\@grpc\grpc-js\build\src\client.js:61:36)`

**Comment by WillCooter** [comment]
@sunildarji811  You've tried using [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions)?

**Comment by sunildarji811** [comment]
@WillCooter Yeah but did not help. 

update - If I initialize `const client = new GoogleAdsApi({...})` in` sails.js helper` it is not working.

But If I use `const client = new GoogleAdsApi({...})` directly inside `controller ` it is working.

Really strange issue.

**Comment by WillCooter** [comment]
@sunildarji811 I'm afraid I don't know then, there could be many different things going wrong here. If you find a solution please leave a comment with it to help others in the future

**Comment by WillCooter** [comment]
@sunildarji811 I am unfamiliar with the sails.js framwork. Are you trying to use this library in the frontend? It will only work in a node-js environment.

**Comment by sunildarji811** [comment]
It is node js library. But for now I am able to find workaround with above solution.
