### ISSUE TITLE
Google Ads API documentation is too far out of date

### ISSUE THREAD

**Issue by jeanlescure** [Opteo/google-ads-api#306]
We have encountered two issues so far that could've been solved much faster had the documentation been up to date.

Firstly the `.list()` method has been removed from `customer.conversionActions` for v5, also v4 is now blocked so anyone forced to update to v5 will get errors regarding a method that according to the documentation still exists:

https://opteo.com/dev/google-ads-api/#list-conversionaction

Where it states that you should be able to do:

```ts
// Listing all the conversionActions in the account
let result = await customer.conversionActions.list()

// Listing with constraints, sorting, and a limited number of results
let result = await customer.conversionActions.list({
  constraints: [
    {
      key: 'conversion_action.some_field',
      op: '=',
      val: 'yellow submarine',
    },
  ],
  limit: 15,
  order_by: 'conversion_action.some_field.sub_field',
})
```

The real fix is to replace calls to that non-existing `customer.conversionActions.list(...)` method for a report, as follows:

```ts
let result = await customer.report({
  entity: 'conversion_action',
  attributes: [
    'conversion_action.attribution_model_settings.attribution_model',
    'conversion_action.attribution_model_settings.data_driven_model_status',
    'conversion_action.category',
    'conversion_action.counting_type',
    'conversion_action.mobile_app_vendor',
    'conversion_action.status',
    'conversion_action.type',
    'conversion_action.name',
    'conversion_action.resource_name',
  ],
})
```

Secondly we had an issue with `customer.conversionUploads.uploadClickConversions` where the documentation indicates that `uploadClickConversions` has 3 arguments:

https://opteo.com/dev/google-ads-api/#upload-conversionclick

```ts
// uploading ClickConversions

const click_conversions: ClickConversion[] = [
  {
    // Your ClickConversion here
  },
  {
    // Your ClickConversion here
  },
]

// Getting identifying information for all uploads
const result = await customer.conversionUploads.uploadClickConversions(click_conversions, {}, true)

// Getting identifying information for all uploads with options
const result = await customer.conversionUploads.uploadClickConversions(
  click_conversions,
  {
    validate_only: true,
  },
  true
)
```
whereas in reality since April it was reported in #233 that #247 "solves" the problem, although the problem here is really that when people follow the documentation they are given code that will fail with no easy to debug errors on JS and will waste dev time in TS.

Is there any timeline in regards to updating the docs?

**Comment by WillCooter** [comment]
Hi @jeanlescure, sorry this has been so confusing for you. As you can see in the README, our documentation is outdated from an older version of this library and the Google Ads API. Rebuilding these docs is a lot of work, however we do have plans to revamp it at some point. For now we recommend using this library’s README for guidance on how to use the library, and using the [Google-Ads-API docs](https://developers.google.com/google-ads/api/docs/start) for everything else.
I can see how including a link to the old documentation in the README could be confusing, so we will remove it for the time being.

**Comment by jeanlescure** [comment]
@WillCooter I understand that a lot of the friction currently affecting those of us moving from v4 to v5 is indirectly correlated to changes in Google API and not necessarily due to any particular decisions within Opteo.

We have currently shifted the focus away from the docs and towards the README, the specs, and creating a Typescript sandbox where we could compare our previous code-base to the changes that would be required to fully transition to v5.

With that in mind, I would like to mention that the sudden blockage of v4 took us by surprise, and took down one of our production servers for a few hours while we hastily patched what could be quickly patched and the aftermath has since basically hijacked the working hours of 3 of our devs for the past week and a half. Is there any official Opteo communication channel where my team can keep track of these decisions so that from here on we can plan version transitions ahead of time?

I'm looking for a single source of truth that we can assign the task of keeping an eye on from here on forward.

**Comment by WillCooter** [comment]
@jeanlescure The decision to deprecate v4 of the API came from Google, you can find their deprecation schedule [here](https://developers.google.com/google-ads/api/docs/sunset-dates). We try to keep this library on the latest version of the Google Ads API, so the best place to keep track of our production decisions is by keeping an eye on this library's GitHub page. When a new Google Ads API version is available we will make an issue, which you can then subscribe to. Any notable/breaking changes will be included in the associated pull request. So in answer to your question there are two sources of truth to keep an eye on, however the best practice would be to make sure you are keeping up to date with the latest version of this library.

**Comment by Zikoel** [comment]
@jeanlescure You can also subscribe to the google ads developer mailing list where google notify the new releases and deprecations with a margin of 3-4 months.
