### ISSUE TITLE
Any way to retrieve the value of the enum instead of the library-assigned id for it?

### ISSUE THREAD

**Issue by raulrene** [Opteo/google-ads-api#310]
When retrieving enum-like fields the Google APIs return the value directly, for example for the `enum CriterionType` the value from the api is `type: 'LOCATION'`, while when using the library the value is `type: 7`.

Wouldn't it make more sense for the end user to have the proper google field returned instead of the internal library ID for it? '7' doesn't mean anything and we just have to re-map the field based on your `enums` to get the proper value.

Or is there any flag I can pass in order to retrieve the original enum value? Thanks!

**Comment by WillCooter** [comment]
Hi @raulrene, the string value of the enum can be accessed by passing the numeric value to the enum, e.g.:
```ts
const numericEnum = enums.CampaignStatus.ENABLED // 2
const stringEnum = enums.CampaignStatus[2] // "ENABLED"
```
