### ISSUE TITLE
v8.0.0+ does not return the list of customers accessible to an account

### ISSUE THREAD

**Issue by varun27896** [Opteo/google-ads-api#315]
I upgraded the package to the latest version and noticed that the `listAccessibleCustomers` method fails to return the array of customer objects and returns an empty array instead. 

I tried going back to the previous versions i.e `5.2.0` and `5.1.3` and it works with the expected behaviour. Hope this is addressed in the next patch release as it could have a potentially large blast radius in the future

**Comment by WillCooter** [comment]
Hi @varun27896, there are some known issues with `v8` of this library at present. We are currently working on a fix, but for the moment I would suggest remaining on an older version of the library.

**Comment by WillCooter** [comment]
Hi @varun27896, I am unable to replicate this issue on my end, it appears to be working fine. Could you upgrade to the latest version of the library (`v8.1.0`) and try again?

**Comment by varun27896** [comment]
Correction- you were unable to replicate this issue on v8.1.0 since it has been fixed.
This was a bug that was raised by many other users as well. Thanks for fixing it.

**Comment by mledwards** [comment]
That's the community spirit @varun27896 🙄
