### ISSUE TITLE
Any expected stable version release date?

### ISSUE THREAD

**Issue by MitulGedeeya** [Opteo/google-ads-api#317]
Hi, I am adding this because we are facing some issues.

2 are follow which I already created them in issues.

1. #312 
2. Error "Mutate operations must have 'create', 'update', or 'remove' specified" while creating Billing Setup or Customer client links ( #316  )

There is no clear documentation as well. So, can you please also tell us when can we expect it as well?

**Comment by WillCooter** [comment]
Hi @MitulGedeeya, apologies for the delayed response. We are currently very busy at Opteo, so we cannot tell you when to expect documentation. For now I suggest using the README of this library in conjunction with the [Google Ads docs](https://developers.google.com/google-ads/api/docs/release-notes). As for the issues we are working with representatives from Google to get the latest version of this library working. We will let you know when a stable release is available.

**Comment by MitulGedeeya** [comment]
Thanks @WillCooter . Looking forward to use the stable release :muscle:

**Comment by WillCooter** [comment]
@MitulGedeeya A new version of the library has just been released (`v8.1.0`). This should solve the invalid customer id issues

**Comment by MitulGedeeya** [comment]
@WillCooter Thanks. I will update version and check.
