### ISSUE TITLE
`extension_feed_item.sitelink_feed_item.url_custom_parameters` is not a valid attribute

### ISSUE THREAD

**Issue by felixmosh** [Opteo/google-ads-api#318]
There is no way to fetch in a report `url_custom_parameters` field of SiteFeedItem but it is [documented](https://developers.google.com/google-ads/api/reference/rpc/v8/SitelinkFeedItem)

```js
const extensionItems = await client.report({
  entity: 'extension_feed_item',
  attributes: [
    'extension_feed_item.extension_type',
    'extension_feed_item.status',
    'extension_feed_item.device',
    'extension_feed_item.resource_name',
    'extension_feed_item.sitelink_feed_item.link_text',
    'extension_feed_item.sitelink_feed_item.final_urls',
    'extension_feed_item.sitelink_feed_item.line1',
    'extension_feed_item.sitelink_feed_item.line2',
    'extension_feed_item.sitelink_feed_item.url_custom_parameters', // <-- when added it fails
  ],
});
```

**Comment by WillCooter** [comment]
Hi @felixmosh, this error is coming from Google Ads and not from this library. These kind of issues are best directed to the [official google ads api forum](https://groups.google.com/g/adwords-api).

**Comment by felixmosh** [comment]
Typescript types as well?

**Comment by WillCooter** [comment]
@felixmosh The `extension_feed_item.sitelink_feed_item.url_custom_parameters` field doesn't appear to exist on the `extension_feed_item` resource (see [here](https://developers.google.com/google-ads/api/fields/v8/extension_feed_item)). Where did you see this field?

**Comment by felixmosh** [comment]
Check the url above, it shows the Field

**Comment by WillCooter** [comment]
@felixmosh I guess Google haven't seen fit to include it in the API yet. Perhaps it's due to be deprecated, or just not used enough to be considered valuable. My only suggestion would to be ask why this is in the office google ads api forum.
