### ISSUE TITLE
Question: Any upcoming plan for missing reports?

### ISSUE THREAD

**Issue by MitulGedeeya** [Opteo/google-ads-api#319]
For example: **CALL_METRICS_CALL_DETAILS_REPORT** -> **call_view**

**Comment by WillCooter** [comment]
Hi @MitulGedeeya, we only compile methods for services (e.g. [CampaignService](https://developers.google.com/google-ads/api/reference/rpc/v8/CampaignService)). However you can still query reports such as the `call_view` report using the `report` method, e.g.:

```ts
const calls = await customer.report({
    entity: "call_view",
    attributes: ["call_view.call_status", "call_view.type"],
})
```
