### ISSUE TITLE
`listAccessibleCustomers` function is blocking?

### ISSUE THREAD

**Issue by AlexGodard** [Opteo/google-ads-api#324]
Hello,

Whenever I use the `listAccessibleCustomers` function, it seems to be blocking my app for a good 7-8 seconds (the time it takes for `listAccessibleCustomers` to complete). The healthcheck endpoint that I have on my server will hang until the function completes.

Is there any way to make this non-blocking?

Thank you.

**Comment by WillCooter** [comment]
Hi @AlexGodard, there is known issue with the API where the first request will take 5-10 seconds. Unfortunately this is unavoidable as the protos need to be imported on the first query. We have discussed this with our contacts at Google and they have assured us that they have plans to improve this.

**Comment by AlexGodard** [comment]
Ah, I didn't realize this behavior only occured in the very first query. I'm going to make a call as soon as the app starts so the protos are loaded before the first queries come in.

Thanks for you help!

**Comment by zth** [comment]
@WillCooter curious, did your contacts at Google mention roughly when they might look into this?
