### ISSUE TITLE
How to update campaign budget

### ISSUE THREAD

**Issue by divyeshgajja** [Opteo/google-ads-api#330]
Hello Guys,
can you Please tell how to update my campaign budget using API.

Hear is my small Code:

 **$campaignBudget = new CampaignBudget([
                     'amount_micros' => $daily_budget
                 ]);
                 $campaignBudgetOperation = new CampaignBudgetOperation();
                 $campaignBudgetOperation->setUpdate($campaignBudget);
                 //$campaignBudgetOperation->setUpdateMask(FieldMasks::allSetFieldsOf($campaignBudget));
                 $campaignBudgetServiceClient = $googleAdsClient->getCampaignBudgetServiceClient();
                 $responses = $campaignBudgetServiceClient->mutateCampaignBudgets(
                     $customerId,
                     [$campaignBudgetOperation]
                 );**

i am trying this code for update budget but still this is not working.
please give me solution.

**Comment by WillCooter** [comment]
@divyeshgajja is that php? this is a javascript library
