### ISSUE TITLE
Cannot get authenticated

### ISSUE THREAD

**Issue by bogdancss** [Opteo/google-ads-api#332]
I am having trouble getting even basic functionality to work.

I have followed instructions and have gathered all the necessary credentials: created an OAuth cred and got the Client ID and the Client Secret, as well as the Developer Token. I then created a Refresh Token.

Running the following code
```
const client = new GoogleAdsApi({
  client_id: process.env.GADS_CLIENT_ID,
  client_secret: process.env.GADS_CLIENT_SECRET,
  developer_token: process.env.GADS_DEV_TOKEN,
})

const customers = await client.listAccessibleCustomers(process.env.GADS_REFRESH_TOKEN)
```
returns the following error:
```
Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: invalid_request
  code: 16,
  details: 'Failed to retrieve auth metadata with error: invalid_request',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient',
  statusDetails: []
```

Any help will be appreciated.

**Comment by evantrimboli** [comment]
I'm having the same issue. It was working for a while and stopped (same code). I'm pretty sure it has something to do with an incompatibility with another package added to the project.

**Comment by WillCooter** [comment]
Hi @bogdancss @evantrimboli, this error comes from the Google Ads API, so your question could be better answered at the [Google Ads API forum](https://groups.google.com/g/adwords-api). In the meantime a quick search of the error message revealed [this](https://stackoverflow.com/questions/66477703/error-16-unauthenticated-failed-to-retrieve-auth-metadata-with-error-could-no), it may be of help.

**Comment by mateioprea** [comment]
@bogdancss can you catch the error in your code and see the actual google response? 
I was using an user which was not a valid Google Asd user (it's a new account). 

This is what I got after catching the listAccessibleCustomers

```
 errors: [
    GoogleAdsError {
      error_code: [ErrorCode],
      message: 'User in the cookie is not a valid Ads user.'
    }
  ],
  ```
