### ISSUE TITLE
How can i generate refresh token ?

### ISSUE THREAD

**Issue by RedRosh** [Opteo/google-ads-api#333]
i have all client_id + client_secret + dev token , but i could not get the refresh token . 
can anyone show me how to do so ?  
thaanks

**Comment by avermeil** [comment]
Hi @RedRosh, I recommend reading up on OAuth flows here: https://developers.google.com/google-ads/api/docs/oauth/overview

Or if you want a quick way to generate a single refresh token, you can use this tool we built: https://refresh-token-helper.opteo.com/
