### ISSUE TITLE
Asking for permission through OAUTH to Google Ads data

### ISSUE THREAD

**Issue by kamrankhanwastaken** [Opteo/google-ads-api#339]
Hi everyone,

This isn't necessarily an "issue" but I wasn't sure where else to ask for help or any sort of guidance on this.

I'm using this module to retrieve google ads data using an MCC account, but I was wondering if this module provides the ability to request access to someone's Google Ads data through the pop-up consent screen without the need need to manually add those accounts under one MCC account.

I'm new to this area of authentication so kind of lost on what to do. I'm using Auth0 to authenticate users, but I don't know if I would need to build this consent feature to get access separately or if this module provides that capability.

I looked at [google-api-nodejs-client](https://github.com/googleapis/google-api-nodejs-client) but Google Ads isn't listed in the supported APIs so I don't know if that is even an option.

Any help would be greatly appreciated!

**Comment by kritzware** [comment]
Hi @kamrankhanwastaken, authentication for the Google Ads API is quite complex unfortunately. This library assumes you've done most of this work already. To retrieve a refresh token for a Google Ads account the user will have to go through the OAuth process. There is a bit more information over at the official docs here: https://developers.google.com/google-ads/api/docs/first-call/overview

We've also built a tiny frontend for quickly retrieving refresh tokens for a Google Ads account here: https://refresh-token-helper.opteo.com/
