### ISSUE TITLE
detail placements remove operation

### ISSUE THREAD

**Issue by AlitalipSever** [Opteo/google-ads-api#341]
Hello, thank you for this library.

I could not find the necessary action to **remove DetailPlacements** by adgroup or campaign. Does the library support this feature? This process can be done on the GoogleAds UI.

**Comment by Zikoel** [comment]
From the official [GADS doc](https://developers.google.com/google-ads/api/reference/rpc/v9/DetailPlacementViewService) seems to me the `DetailPlacement` is read only and that is not possibile to mutate it from APIs. Maybe I wrong but the are sometime resources that laks support from APIs, is this is the case (I'm not completely sure) the only things that we can do is to ask on the official ADS Dev group.
