### ISSUE TITLE
listAccessibleCustomers for manager account

### ISSUE THREAD

**Issue by anishpateluk** [Opteo/google-ads-api#344]
Would it be possible to optionally pass in a `customer_id` into the `listAccessibleCustomers` method, so we can see which customer ids are accessible to a parent/manager customer id?

Maybe even expose the [Service Class](https://github.com/Opteo/google-ads-api/blob/master/src/service.ts) so we can construct our own services if they haven't been implemented yet by this library?

Currently, I'm not seeing a workaround to this.

**Comment by anishpateluk** [comment]
I can use this query:
```
const query = `
      SELECT 
        customer_client.id,
        customer_client.descriptive_name
      FROM customer_client
      LIMIT 20
    `;
```

Where the customer is the manager account id

**Comment by thokkane** [comment]
@anishpateluk is there a way you detected the account is a manager account when getting a list of accounts? Is there method to find this out?
