### ISSUE TITLE
Basic starting question for new user

### ISSUE THREAD

**Issue by sgpascoe** [Opteo/google-ads-api#348]
Hi there. I have written an App using nodejs and js. I have never used an API before. 

I think I have the correct auth information now, and I'm trying to get the node_module to work, but can't seem to get it to load.

My app is mode up of a node server, a html file, and a single js file, like this:
```
/server.js
/public/index.html
/public/js/script
```

I've used npm install, and I can see the google-ads-api in my `/nodes_module/` folder. 

I just don't know where or how to call the node module! 

Right now I've created  `/public/js/ads.js`, and I've set it to load as `type = "module"` within the index.html

I have this inside:

```
import { GoogleAdsApi } from "/node_modules/google-ads-api";

const client = new GoogleAdsApi({
  client_id: "[my client ID]",
  client_secret: "[my client secret]",
  developer_token: "[my dev token]",
});


const refreshToken = "[my refresh token]"
const customers = await client.listAccessibleCustomers(refreshToken);`
```

However When loading the page, I get `http://localhost:3000/node_modules/google-ads-api net::ERR_ABORTED 404 (Not Found) `in the console.

**Comment by Zikoel** [comment]
Seems like that your problem is not with this library in particular but you are missing some js programming basisc! The right import for this library is `import { GoogleAdsApi, Customer, errors } from 'google-ads-api'` but is a very basic concept! You need to keep confidence with JS in general before approaccing such not very easy library. Without the source that you try to run I can't help you mutch more.

**Comment by sgpascoe** [comment]
I just wanted to start with the basic example given in the readme, to get up and running. I have written a lot in js, but as I said, APIs are completely new to me, this is the first I have tried. 

Without the path structure, and simply using from 'google-ads-api' (this is how the readme is written too) results in:

Uncaught TypeError: Failed to resolve module specifier "google-ads-api". Relative references must start with either "/", "./", or "../".

**Comment by Zikoel** [comment]
See one of my very basic examples [here](https://gist.github.com/Zikoel/fd07b8578f4cedb99943281474320a58)

**Comment by sgpascoe** [comment]
This also contains `from 'google-ads-api'`

which returns `Uncaught TypeError: Failed to resolve module specifier "google-ads-api". Relative references must start with either "/", "./", or "../".`

**Comment by sgpascoe** [comment]
@Zikoel does this file structure look incorrect?

**Comment by Zikoel** [comment]
You are trying to use this library client side! But I'm pretty sure that is almost impossibile do that! This is a library developed to be used on server side! You need to move all you logic on the server side part of your app and use te client only to show someting to the user!

More of this admitting (and is not the case) that the library is ready to be used on the client side you need to pack it and serve it the bundle on the client side with something like webpack or similar! I'm sorry but seems like that you are mossing some very basic concept about `nodejs` and in general webapps composed by backend and frontend!

I don't want discorage you absolutelty but I suggest you first study the lib on server side and with a solid undertanding go further and integrate an UI. I've no problem to show you a minimal example!

**Comment by sgpascoe** [comment]
Thanks so much @Zikoel ! This is exactly what I needed to hear to solve the problem, I'll do the imports on the server side and work out how to pass the data to the client side :) 

Sorry for asking such a basic question, I'm really trying to learn backend and API related things recently, and really appreciate the help. I'm learning very fast with these practise projects.

**Comment by sgpascoe** [comment]
Hi @Zikoel I am revisiting this issue from the backend and have a new question. 

In my server.js I am referencing the file adsAccess.js, which is in the same folder.

```
var ad = require('./adsAccess');
```

And in adsAccess.js, I have:
```
import { GoogleAdsApi, Customer, errors } from 'google-ads-api'

```

However now I have the error 

`SyntaxError: Cannot use import statement outside a module`

Googling this error suggests I need to change the package.json, but I don't want to make the whole project a module, so I'm unsure what to do next.
