### ISSUE TITLE
Multiple requests were attempting to modify the same resource at once.

### ISSUE THREAD

**Issue by Zikoel** [Opteo/google-ads-api#349]
Hi guys! Starting from some hours ago! I starting to se this error on my logs!

The error I think is that [Link to oficial DOC](https://developers.google.com/google-ads/api/reference/rpc/v7/DatabaseErrorEnum.DatabaseError)

Someone has notice this kind of error befere? I'm triyng to understand if can be a mis uses of the library from my side or something else! I am pretty sure that I don't have concurrent requests at same time!

**Comment by rosslavery** [comment]
This happens when you are trying to mutate the same resource more than once in a single mutate request. 

E.g. setting a campaign budget to two different values in two different operations in an array of operations.

**Comment by Zikoel** [comment]
Thanks for the suggestion! I have a complete report of what goes wrong every time. I will check if that is the case!

**Comment by Zikoel** [comment]
Ok I solve my problem! I'm not mutating the same resources in the same query! For my mistake I permit my users to update too often and Google sometimes take many seconds to complete a mutation. The error disappear adding a guard for multiple simultaneous mutations.
