### ISSUE TITLE
I wanted to Generate Keyword Ideas using string of keywords and pageURL but can't found any documentation or example.

### ISSUE THREAD

**Issue by HassanTarique27** [Opteo/google-ads-api#351]

**Comment by rohitnishad613** [comment]
same here. Any update?

**Comment by rohitnishad613** [comment]
I found solution and I have created the PR, https://github.com/Opteo/google-ads-api/pull/357

**Comment by WillCooter** [comment]
Hi @rohitnishad613, thanks for your contribution. I will include it in the next release of the library
