### ISSUE TITLE
Generate Keyword Ideas 

### ISSUE THREAD

**Issue by rohitnishad613** [Opteo/google-ads-api#353]
How to Generate Keyword Ideas?
Offical docs: https://developers.google.com/google-ads/api/docs/keyword-planning/generate-keyword-ideas

**Comment by Zikoel** [comment]
Why you open an issue to link a page of the official doc ?

**Comment by rohitnishad613** [comment]
how to generate Keyword Ideas using this library?

**Comment by rohitnishad613** [comment]
> Why you open an issue to link a page of the official doc ?

how to generate Keyword Ideas using this library?

**Comment by rohitnishad613** [comment]
i found the answer #294
