### ISSUE TITLE
geoTargetConstants list function

### ISSUE THREAD

**Issue by danielgarstin** [Opteo/google-ads-api#354]
As stated [here](https://opteo.com/dev/google-ads-api/#list-geotargetconstant), I should be able to list all geo target constants. However this functionality doesn't seem to have been implemented yet. Is this expected? I'm on version 9.0.0

**Comment by valentina98** [comment]
I have the same question for [UserList](https://opteo.com/dev/google-ads-api/#userlist).

**Comment by kritzware** [comment]
Hi @danielgarstin, our documentation at https://opteo.com/dev/google-ads-api is currently outdated (new docs coming soon) so for now you should refer to the README in this repo.

Several versions ago the `list` methods were removed. Instead you should use `report` and specify the exact fields you need.
