### ISSUE TITLE
Upgrade Google Ads to v10

### ISSUE THREAD

**Issue by cedrictwillie** [Opteo/google-ads-api#359]
- [x] Feature Request

What would the timeline be for supporting version 10 of the api.

Is following the "Upgrading API Versions" section [here](https://github.com/opteo/google-ads-node) something the community can do to upgrade?

Thanks

**Comment by cedrictwillie** [comment]
I'm going to take a stab at following the instructions [here](https://github.com/opteo/google-ads-node) and put up a PR.

**Comment by cedrictwillie** [comment]
I have a PR to upgrade to `v10` in the `google-ads-node` package which this package depends on. Hopefully it will be merged soon.

https://github.com/Opteo/google-ads-node/pull/89

**Comment by Zikoel** [comment]
I want to candidate myself too as an help for this repo!

**Comment by Midnight-Conqueror** [comment]
@Zikoel @rosslavery Hi guys! We are really interested in this and would love to talk more about it. Can you both email me joel@opteo.com. Perhaps there are also other opportunities we could discuss

**Comment by rosslavery** [comment]
> @Zikoel @rosslavery Hi guys! We are really interested in this and would love to talk more about it. Can you both email me [joel@opteo.com](mailto:joel@opteo.com). Perhaps there are also other opportunities we could discuss

Emailed :)

**Comment by kritzware** [comment]
We have a PR ready to go for the v10 release https://github.com/Opteo/google-ads-api/pull/364

**Comment by kritzware** [comment]
v10 is now available on NPM and we've created a release here: https://github.com/Opteo/google-ads-api/releases/tag/v10

**Comment by cedrictwillie** [comment]
@kritzware Thank you all for all of the hard work! Much appreciated.
