### ISSUE TITLE
Getting historical location targets within a date range

### ISSUE THREAD

**Issue by kamrankhanwastaken** [Opteo/google-ads-api#361]
Hi everyone,

This isn't really an issue I believe and I'm not sure where else seems like a valid forum to ask for help in understanding how to retrieve specific information regarding location targets for campaigns.

Currently I'm using the following query to retrieve location targets:
```
location_view = await customer.report({
        entity: "location_view",
        attributes: [
          "campaign_criterion.location.geo_target_constant",
          "campaign_criterion.location_group",
          "campaign_criterion.location_group.feed",
          "campaign_criterion.proximity.address.city_name",
          "campaign_criterion.proximity.address.country_code",
          "campaign_criterion.proximity.address.postal_code",
          "campaign_criterion.proximity.address.province_code",
          "campaign_criterion.proximity.address.province_name",
          "campaign_criterion.proximity.address.street_address",
          "campaign_criterion.proximity.geo_point.latitude_in_micro_degrees",
          "campaign_criterion.proximity.geo_point.longitude_in_micro_degrees",
          "campaign_criterion.proximity.radius",
          "campaign_criterion.proximity.radius_units",
          "campaign.name",
          "campaign_criterion.bid_modifier",
        ],
        metrics: [
          "metrics.clicks",
          "metrics.impressions",
          "metrics.ctr",
          "metrics.average_cpc",
          "metrics.cost_micros",
        ],
        from_date: data.fromDate,
        to_date: data.toDate,
        constraints: [
          {
            key: "metrics.impressions",
            op: ">",
            val: 0,
          },
          {
            key: "metrics.cost_micros",
            op: ">",
            val: toMicros(1),
          },
        ],
      });
    }
```

This is working as it should be i.e. I'm able to receive location targets that have been *currently* set for campaigns.

However, what I would actually like is targets that were set within a given date range for a campaign that might no longer be active and this query doesn't give me accurate historical data for location targets.. it only gives me the current ones that are live on the account.

Is there a query I can use to generate a report which would give me location targets (deleted and new) for a given campaign within a date range and not just the ones that are currently active on the account?

**Comment by WillCooter** [comment]
Hi @kamrankhanwastaken, I don't know if this is currently possible in the Google Ads API. The only idea I have is to have a play with the `change_event` resource, e.g.
```ts
const respone = await customer.report({
    entity: 'change_event',
    attributes: ['change_event.campaign'],
})
```
However I don't know how far back Google's event change records go. In future questions like this would be better directed to the official [Google Ads API forum](https://groups.google.com/g/adwords-api). Sorry we can't be of more help
