### ISSUE TITLE
Q: how to get metadata for fields (type, repeate, etc)?

### ISSUE THREAD

**Issue by evil-shrike** [Opteo/google-ads-api#362]
Hi,
I'm trying to export data from reports to BigQuery and I need to know schema of my data, that I got from API.
Protos knows and contains all fields for each resources that can be selected. But query results don't provide any metadata.
I found only `fields.enumFields` in field.js that contains all fields for enums which great. But I need the same for all other attribute types. Is it possible to get them using?

For example, for campaign resource, there could be:
```
  campaign.labels AS labels,  --RESOURCE_NAME, Repeated=True
  campaign.bidding_strategy AS bidding_strategy,  -- RESOURCE_NAME
  campaign.manual_cpm, -- MESSAGE
  campaign.maximize_conversion_value.target_roas AS target_roas,  -- DOUBLE
  campaign.network_settings.target_content_network AS target_content_network,  -- BOOLEAN
  campaign.targeting_setting.target_restrictions AS target_restrictions  -- MESSAGE(TargetRestriction), Repeated=True
```
for each field I need to have its type and other metadata (repeated).
Somehow it can be extracted from results but not reliable, for example for an empty result it's not possible.

**Comment by WillCooter** [comment]
Hi @evil-shrike, the return type for any report or query will be a `GoogleAdsRow[]`. In the `GoogleAdsRow` type, all keys are optional as we are unable to build specific types based on the report options of the query (this is a project we have considered, however the type structure is currently too complicated for TypeScript to handle). However there are specific types available for each field, as well as metrics and segments.

At Opteo, when we do a Google Ads request we build a custom type and pass it as a generic to the `report` function. I will add a basic example of this below, I hope it helps...

```ts
import { enums, resources, common } from '@gads'

// utility type to force pick keys from a type and force them to be required
type PickRequired<T, K extends keyof T> = NoUndefinedFields<Pick<T, K>>

// build an interface using the PickRequired util type
interface Campaign {
    campaign: PickRequired<resources.Campaign, 'id' | 'name'>
    metrics: PickRequired<common.Metrics, 'clicks'>
    segments: PickRequired<common.Segments, 'date'>
}

// do a request with the interface included as a generic type
const campaigns = await customer.report<Campaign[]>({
    entity: 'campaign',
    attributes: ['campaign.id', 'campaign.name'],
    metrics: ['metrics.clicks'],
    segments: ['segments.date'],
    constraints: [{ 'campaign.status': enums.CampaignStatus.ENABLED }],
})
```
