### ISSUE TITLE
Is the report call considered a GET request or an API operation in Google Ads API?

### ISSUE THREAD

**Issue by kamrankhanwastaken** [Opteo/google-ads-api#368]
Just asking this because I couldn't find an answer in the documentation.

When I make a `report` call in this module, am I essentially making a `GET` request call? Asking because the [rate limits](https://developers.google.com/google-ads/api/docs/best-practices/quotas) for `GET` requests vs API operations is quite substantial and would require different caching strategies for the application I'm building.

Any help is appreciated.

**Comment by Midnight-Conqueror** [comment]
Its technically known as a GRPC request, you can find out more [here](https://developers.google.com/google-ads/api/docs/best-practices/quotas#grpc_limitations).

**Comment by kamrankhanwastaken** [comment]
Is there a limit on how many GRPC requests you can do? It's hard to know from the docs under which rate limit that would fall under.

**Comment by WillCooter** [comment]
@kamrankhanwastaken Its hard to say, Google haven't supplied an exact quota on that web page. This sort of request would be better suited to the official [Google Ads API forum](https://groups.google.com/g/adwords-api).
