### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by quesurifn** [Opteo/google-ads-api#37]
How does one get a refresh token? 

`Refresh token: You'll get this token when somebody authorises you to query their adwords account via OAuth.` Is not thorough documentation.

**Comment by avermeil** [comment]
Hi Kyle!

Getting refresh tokens is a bit outside the scope of this library at the moment.

There's some official documentation here: https://developers.google.com/google-ads/api/docs/oauth/overview

However, I agree that it's still pretty confusing.

We've just published a small tool to help: **https://refresh-token-helper.opteo.com/**. It generates a `refresh_token` from a `client_id` and `client_secret`.

Let us know if you have any more issues :)

**Comment by quesurifn** [comment]
Thank you!

**Comment by truptijogi7** [comment]
Hi @avermeil Thanks for awesome library!

Is there any way to get `refresh_token` using `expressjs` with react js code? 

On google site, there are examples of server side tech without node js. 

Or might be not possible with expressjs or nodejs?
