### ISSUE TITLE
ipBlocking via Opteo

### ISSUE THREAD

**Issue by HogansJoe** [Opteo/google-ads-api#370]
The official Adwords rpc API could be used for Ip Blocking or whitelisting up to 500 entries. 
I am intrigued to automate ip blocking and whitelisting thru Opteo. ["IpBlocking official Adwords API Reference".](https://developers.google.com/google-ads/api/reference/rpc/v10/IpBlockInfo).

> Google Ref: An IpBlock criterion used for IP exclusions. We allow: - IPv4 and IPv6 addresses - individual addresses (192.168.0.1) - masks for individual addresses (192.168.0.1/32) - masks for Class C networks (192.168.0.1/24)

Is there a way how to use this "IpBlockInfo" criterion with Opteo?

**Comment by rosslavery** [comment]
I believe it would be the same as adding any other customer/campaign/adgroup criterion. 

If you aren't sure how I can prep a simple example.

**Comment by HogansJoe** [comment]
Sure, please. If you could provide me with an example, I would be very pleased with that and start testing.

Did research and found the following for that criterion via the rpc:

[proto criterion](https://github.com/googleads/google-ads-python/blob/bdc334af6303cd63a4b5ff74a984263027cfe3a0/google/ads/googleads/v10/common/types/criteria.py#L1025)
[And ipBlockInfo as ip_block ](https://github.com/googleads/google-ads-python/blob/bdc334af6303cd63a4b5ff74a984263027cfe3a0/google/ads/googleads/v10/resources/types/campaign_criterion.py#L147)

**Comment by HogansJoe** [comment]
Trying figuring something out, is this the right Opteo way? Don't see any good step by step documentation. 
I missed the concept of targeting a campaign and do some mutations by setting the ip's to block or whitelist. 
Is there already an example? 

```
import {

  resources, enums, ResourceNames

} from "google-ads-api";

//Some code to bind the campaign 

....

//Guessing the operation code
const operations: ip_block [
  {
    entity: "campaign",
    operation: "ip_block"
    resource: {
     
      ip_adress: "123.123.123", //Field as string
     
    },
  },
 
];

...

```

**Comment by WillCooter** [comment]
Hi @HogansJoe, you will need to specify the resource name of the campaign you wish to apply the block to, like so...
```ts
customer.campaignCriteria.create([{
    resource_name: 'customer/111/campaign/222',
    ip_block: { ip_address: '123.123.123' }
}])
```
