### ISSUE TITLE
How to get the CustomerID of the account I'm currently logged into?

### ISSUE THREAD

**Issue by Acnologla** [Opteo/google-ads-api#371]

**Comment by kritzware** [comment]
Hi @Acnologla, you can retrieve the Customer ID like the following:

```ts
import { GoogleAdsApi } from "google-ads-api";

const client = new GoogleAdsApi({
  client_id: "<CLIENT-ID>",
  client_secret: "<CLIENT-SECRET>",
  developer_token: "<DEVELOPER-TOKEN>",
});

const customer = client.Customer({
  customer_id: "1234567890",
  refresh_token: "<REFRESH-TOKEN>",
});

// If you lose the value above passed into client.Customer
// you can access it on the customer instance with credentials.customer_id
console.log(customer.credentials.customer_id)
```

**Comment by Acnologla** [comment]
> Hi @Acnologla, you can retrieve the Customer ID like the following:
> 
> ```ts
> import { GoogleAdsApi } from "google-ads-api";
> 
> const client = new GoogleAdsApi({
>   client_id: "<CLIENT-ID>",
>   client_secret: "<CLIENT-SECRET>",
>   developer_token: "<DEVELOPER-TOKEN>",
> });
> 
> const customer = client.Customer({
>   customer_id: "1234567890",
>   refresh_token: "<REFRESH-TOKEN>",
> });
> 
> // If you lose the value above passed into client.Customer
> // you can access it on the customer instance with credentials.customer_id
> console.log(customer.credentials.customer_id)
> ```

But how would I get the customerID just passing the refreshToken? it's possible?

**Comment by mrinc** [comment]
@Acnologla  looks like there is a ```client.listAccessibleCustomers(refreshToken)``` method for that... not sure if it works, but it is there.
