### ISSUE TITLE
Do you have support for new price_asset type of Assets?

### ISSUE THREAD

**Issue by jascaniojs** [Opteo/google-ads-api#374]
Hi, excelent work with you library, ive been working with it smoothly for the last year.

Right now i'm having an issue trying to create new price_asset extensions, Im trying something like:

**Comment by WillCooter** [comment]
Hi @jascaniojs, we do indeed support this if you are using the latest version of the library (`v10.0.1`). See [here in the Google Ads docs](https://developers.google.com/google-ads/api/reference/rpc/v10/AssetOperation).
```ts
gads.assets.create([{ price_asset: { ... } }])
```
