### ISSUE TITLE
Support for User List mutations

### ISSUE THREAD

**Issue by StanHilliar** [Opteo/google-ads-api#376]
Hi,

I've been looking to make use of your package and was wondering if this supports the ability to create and update User Lists in the Google Ads platform.
I have been able to query the Ads accounts and list out all the existing User lists etc. by making use of this package without issues.
However I haven't seen anywhere a mention of how to access the mutate endpoints for User Lists, only for campaigns.

I've tried working through the Google docs on how to interact with the mutate endpoint and combine that with what I've found here, but haven't had any luck with that.
I'm looking for a method something like:
```ts
let response = await customer.userLists.create( "<paramater_list_here>" )
```

**Comment by WillCooter** [comment]
Hi @StanHilliar, you are pretty much there. We do have methods for creating, updating and removing user lists. The arguments for these functions are an object with keys relating to Google Ads fields, except for `remove` which takes an array of resource name strings.
```ts
customer.userLists.create({ name: "my user list" })
customer.userLists.update({ resource_name: "a/1/b/2", name: "new name for user list" })
customer.userLists.remove(["a/1/b/2"])
```
You can find out everything you need to know about UserList mutations [here in the Google Ads docs](https://developers.google.com/google-ads/api/reference/rpc/v10/UserListOperation). For an example of a mutation with this library [see here in our own docs](https://developers.google.com/google-ads/api/reference/rpc/v10/UserListOperation).
