### ISSUE TITLE
generateForecastMetrics

### ISSUE THREAD

**Issue by punmin1125** [Opteo/google-ads-api#378]
I want to get keyword forecast value using generateForecastMetrics function. I try with `customer.keywordPlans.generateForecastMetrics(customers/1111111111/keywordPlans/11111111)`, but I get this error message.

```
GoogleAdsFailure {
  errors: [
    GoogleAdsError {
      error_code: ErrorCode { request_error: 17 },
      message: "'' part of the resource name is invalid."
    }
  ],
  request_id: 'ltJEiDuV2RFxQuPqHGKKmg'
}
```

 May I know how to get the correct result from generateForecastMetrics.

**Comment by WillCooter** [comment]
Your resource name will need to be a string, like so:
```ts
const result = await customer.keywordPlans.generateForecastMetrics("customers/1111111111/keywordPlans/11111111")
```

**Comment by punmin1125** [comment]
It returns an empty result. Thank @WillCooter for the help, I solved the problems using google's php function.
