### ISSUE TITLE
Add hooks on generateHistoricalMetrics

### ISSUE THREAD

**Issue by Symbolic76** [Opteo/google-ads-api#380]
I've been trying to mock API calls to be able to cancel requests from ```generateHistoricalMetrics```.

I realized there is no hooks on this method and i can't mock this properly.

**Comment by WillCooter** [comment]
@Symbolic76 Interesting idea, this would involve creating a generic hook for all service methods with the method called being passed as an argument (or perhaps just the name of the function). We will consider this for the next version of the API.
