### ISSUE TITLE
Add streaming GAQL query endpoint

### ISSUE THREAD

**Issue by PaulLockhart** [Opteo/google-ads-api#381]
Would be super nice to be able to open a search stream via a GAQL query rather than the special request object, similarly to how you can do this with the regular query-based search endpoint.

Wondering if this is already possible, and if not it would be a very useful feature.

**Comment by WillCooter** [comment]
Interesting idea @PaulLockhart, do you mind if I ask why you would prefer to use GAQL over the report options?

**Comment by arditti** [comment]
> Interesting idea @PaulLockhart, do you mind if I ask why you would prefer to use GAQL over the report options?

Personally I use GAQL as there are a lot of Google's own examples over their docs

**Comment by PaulLockhart** [comment]
> Interesting idea @PaulLockhart, do you mind if I ask why you would prefer to use GAQL over the report options?

I don't particularly mind the library default implementation if building a project from scratch, but I think using GAQL makes requests more universal and language independent, and makes it easier to pick up and use the library for an existing code base with GAQL queries.

**Comment by WillCooter** [comment]
@arditti @PaulLockhart We will be upgrading the library to `v11` of the API next week. I'll have a look into it then, and if it isn't too much work I'll try to fit this in for you.
