### ISSUE TITLE
Request is missing required authentication credential

### ISSUE THREAD

**Issue by tyukoditamas** [Opteo/google-ads-api#382]
Hello team!

I have successfully managed to test java example for ListAccessibleCustomers from the git examples but as i have to migrate Google Adwords to Google Ads in NodeJs, i couldn't manage to set up the initial calls.

So using https://github.com/Opteo/google-ads-api for NodeJs and trying to use the equivalent method for ListAccessibleCustomers i am receiving the following error: 
`'Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential.'`

I want to point out again, that in Java the connection worked, and the credentials were good. But trying to switch it to NodeJs the credentials seems to not work (i am using the same credentials).

This is my implementation:

```ts
const client = new GoogleAdsApi({
    client_id: "clientID",
    client_secret: "clientSecret",
    developerToken: "devToken"
})

const refreshToken = refreshToken
const customers = await client.listAccessibleCustomers(refreshToken);
console.log(customers)
```

Do you have any idea why this happens?

**Comment by WillCooter** [comment]
Hi @tyukoditamas, it looks like you are using a bad key in your instantiation of `GoogleAdsApi`. You have the key `developerToken` in camel case, when it should be `developer_token` in snake case. Hope this fixes it for you

**Comment by tyukoditamas** [comment]
Hey @WillCooter the instantiation credentials that i wrote are just for example case :)

**Comment by tyukoditamas** [comment]
@WillCooter it took me to realise i am dumb ... When i read your answer i thought you are referring to the developer_token value. But now i realised you were talking about they key itself .. and it truly works with "developer_token"

My apologies and thank you!!

**Comment by WillCooter** [comment]
@tyukoditamas hahah not a problem mate!
