### ISSUE TITLE
client.listAccessibleCustomers(refresh_token) throw Error: 16 UNAUTHENTICATED

### ISSUE THREAD

**Issue by yo1nick** [Opteo/google-ads-api#384]
Hello, I need a little help to get the list with all accessible clients, I try the example code but I get this error:
Error: 16 UNAUTHENTICATED: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

**Comment by WillCooter** [comment]
Could you provide a copy of your code?

**Comment by yo1nick** [comment]
> @yo1nick Could you provide a copy of your code?

Thanks, but I solved the problem, I used camel case for refresh token

**Comment by punmin1125** [comment]
hi, @yo1nick  can you show me the sample code, because I facing the same issues. Thanks.

**Comment by yo1nick** [comment]
> 

Sorry for my late response, but what I was doing wrong it was that in config instead of refresh_token my key was refreshToken

```
client.Customer({
  customer_id: "1234567890",
  **refreshToken**: "<REFRESH-TOKEN>", <-- this was wrong
});

```
