### ISSUE TITLE
How to get and use page_token

### ISSUE THREAD

**Issue by andrienpecson** [Opteo/google-ads-api#386]
According to [SearchGoogleAdsRequest](https://developers.google.com/google-ads/api/reference/rpc/v10/SearchGoogleAdsRequest#next_page_token) we can access the `page_token` in the results and pass it to paginate. My question is how can I get the `page_token` and pass it to the next page of results?

**Comment by marcinbedus** [comment]
Same problem here.

**Comment by WillCooter** [comment]
In this API, when doing a query, all pages are fetched and concatenated into one response ([see here in the code](https://github.com/Opteo/google-ads-api/blob/master/src/customer.ts#L266)). Therefore you do not need to concern yourself with page tokens, unless you have a very specific use case, in which case I would be very interested to hear your reasons...?
