### ISSUE TITLE
Creating Location in Campaign

### ISSUE THREAD

**Issue by irohitb** [Opteo/google-ads-api#39]
Hey,  I see that you do provide support to add location in code? (probably in customer.ts file) but I can't see anything in docs and am unable to comprehend how I can set location. 

I understand that docs are in the process of being updated, but can someone please help me in finding the way to add location till that time.

**Comment by avermeil** [comment]
Hey!

Try something like this:

```javascript

const campaign_criterion = {
  campaign: 'customers/xxxxxxx/campaigns/xxxxxxxxx',
  location: { geo_target_constant: 'geoTargetConstants/2004' }
}

const result = await customer.campaignCriterion.create(campaign_criterion)
```

I haven't tested this snippet, but that's the general structure :)

**Comment by irohitb** [comment]
Interesting and thanks for responding, 

What would be the `geoTargetConstants/2004`? Is it in general location ID (the 2004) 

Something like `geoTargetConstants/${locationID}` if not, how can we make 'geoTargetConstants/2004' ?

**Comment by avermeil** [comment]
Yes, it's the `locationID`. You can get every single geoTargetConstant and their associated location IDs by running:

``` javascript
const result = await customer.geoTargetConstants.list()
```

I don't think we provide any helper functions to build resource names from IDs yet, but we might in the future. The idea, according to Google, is that you're supposed to use the resource names *instead* of IDs.

**Comment by irohitb** [comment]
Just not to buzz you more, Can you also help how we can get/create Criterion ID?
