### ISSUE TITLE
Support for KeywordPlanIdeaService.GenerateKeywordHistoricalMetrics

### ISSUE THREAD

**Issue by davidmrindus** [Opteo/google-ads-api#391]
Hi Opteo,
I would like to ask if a method `GenerateKeywordHistoricalMetrics` of `KeywordPlanIdeaService` is supported?
https://developers.google.com/google-ads/api/reference/rpc/v10/KeywordPlanIdeaService

I see that there is `generateHistoricalMetrics` under `keywordPlans()`, but it does require a KeywordPlan.

`keywordPlanIdeas()` has only `generateKeywordIdeas` as I see.

Thank you!

**Comment by WillCooter** [comment]
Hi @davidmrindus , the `generateHistoricalMetrics ` function was only added in v10.1 of the API. We didn't get round to making a version of this library for that version of the API, however we will be updating the library for v11 of the API next week. Once this is done the field will be available 🙂

**Comment by davidmrindus** [comment]
Hi @WillCooter,
Thank you for your response. That's great news. Looking forward for the next release!
