### ISSUE TITLE
Discovery Ads Support

### ISSUE THREAD

**Issue by tills13** [Opteo/google-ads-api#393]
**Summary**

Add support for Discovery campaign and ad creation.

**Description**

Seems like Google has recently updated the API to support the creation of Discovery campaigns and ads. Listing via `customer.report` results in an AdvertisingChannelType of unspecified. Creating might be possible as well, though you have to manually specify the type (untested).

Official documentation has walkthroughs for other languages: https://developers.google.com/google-ads/api/docs/discovery/create-campaign

**Comment by tills13** [comment]
If there's a process for mapping new features into this repo documented point me to it and I can submit a PR for this work.

**Comment by WillCooter** [comment]
Hi @tills13, this was indeed added in `v10.1` of the API. We will be upgrading to `v11` next week, so if you can wait until then we will gave this sorted for you soon. I appreciate the offer to submit a PR, however the upgrade process can be a little finicky at times, so it's best if we do it ourselves.
