### ISSUE TITLE
Error using ["segment.date"]

### ISSUE THREAD

**Issue by MecBonjourno** [Opteo/google-ads-api#395]
Hello everybody.

I'm trying to retrieve data with an example from Opteo in Google Ads Api

```javascript
import { enums } from "google-ads-api";

const campaigns = await customer.report({
  entity: "ad_group",
  metrics: [
    "metrics.cost_micros",
    "metrics.clicks",
    "metrics.impressions",
    "metrics.all_conversions",
  ],
  segments: ["segments.date"],
  from_date: "2021-01-01",
  to_date: "2021-02-01",
});
```

and I'm getting this error: 
```
GoogleAdsFailure {
  errors: [
    GoogleAdsError {
      error_code: [ErrorCode],
      message: "Expects filters on the following field to limit a finite date range: 'segments.date'"
    }
  ],
  request_id: 'KuRroo11SQz7jQn7nH61Jw'
}
```

also, when using query it just doesnt apply the WHERE option

```
const query = await Promise.all([
    customer.query(`
     SELECT campaign.name FROM campaign WHERE segments.date DURING LAST_MONTH
       `),
      ]);
```

and it returns all my campaings not the ones in the last month.

Any ideas??

**Comment by WillCooter** [comment]
Hi @MecBonjourno, I'm afraid I am unable to reproduce you issues. Running the first query exactly as you have written it over multiple ads accounts returns regular results. All I can suggest is that your read [this documentation](https://developers.google.com/google-ads/api/docs/reporting/segmentation?hl=en#rules_for_core_date_segment_fields) to see if you can figure out what's going on.

The second issue is curious as it depends how you define a campaign from the last month. Google may consider any active, paused or deleted campaigns to be in this month. I suggest you write more detailed constraints here, such as `metrics.impressions > 0` or `campaign.status = "ENABLED"`.
