### ISSUE TITLE
Missing include_average_cpc in HistoricalMetricsOptions

### ISSUE THREAD

**Issue by rynti** [Opteo/google-ads-api#398]
When using `customer.keywordPlanIdeas.generateKeywordIdeas` to generate keyword ideas, the request object has an attribute `historical_metrics_options`, documented here:

> **Attention:** The links to the API docs don't work when clicked directly - one has to copy the URL and manually paste it in the URL bar.

- [The attribute in the request object](https://developers.google.com/google-ads/api/reference/rpc/v11/GenerateKeywordIdeasRequest#google.ads.googleads.v11.services.GenerateKeywordIdeasRequest.FIELDS.google.ads.googleads.v11.common.HistoricalMetricsOptions.google.ads.googleads.v11.services.GenerateKeywordIdeasRequest.historical_metrics_options)
- [The options themselves](https://developers.google.com/google-ads/api/reference/rpc/v10/HistoricalMetricsOptions)

However, when using `google-ads-api` or `google-ads-node`, the `include_average_cpc` attribute within the HistoricalMetricsOptions is missing. It should exist in both v10 and v11 (and probably older versions as well).

Is this an issue that can be easily fixed? I haven't found a workaround yet.

**Comment by WillCooter** [comment]
Hi @rynti, the `include_average_cpc` field was only added to the `historical_metrics_options` in v10.1 of the API. We didn't get round to making a version of this library for that version of the API, however we will be updating the library for v11 of the API next week. Once this is done the field will be available 🙂 

https://developers.google.com/google-ads/api/docs/release-notes#planning_2
