### ISSUE TITLE
Just looking for some guidance: How would I create a new negative keyword list, or view a search terms array? 

### ISSUE THREAD

**Issue by sgpascoe** [Opteo/google-ads-api#405]
I don't see anything in the documentation that touches on search terms reports or negative keyword lists.

Is there an example of how to simply export 30 days of search terms, or create a new negative keyword list with one keyword?

**Comment by WillCooter** [comment]
Hello @sgpascoe. To query the last 30 days of search terms I would recommend using the [`report` method](https://github.com/Opteo/google-ads-api#retrieve-ad-group-metrics-by-date) with a query like so:
```ts
const search_terms = customer.report({
    entity: 'search_term_view',
    attributes: ['search_term_view.search_term', ... ],
    metrics: ['metrics.clicks', ... ],
    from_date: '2022-05-25', // 30 days ago
})
```
If you are getting very large numbers of search terms then you may be better of streaming the results in using the [`reportStream` method](https://github.com/Opteo/google-ads-api#retrieve-keywords-with-an-async-iterator). For more information on the search term view resource see [here](https://developers.google.com/google-ads/api/fields/v11/search_term_view).

To create a new negative keyword list containing a keyword, you will need to perform 2 separate mutations. First a `create` operation on the [shared set service](https://developers.google.com/google-ads/api/reference/rpc/v11/SharedSetService). This will return the **resource name** of the new shared set. You will then need to perform a second `create` operation on the [shared criteria service ](https://developers.google.com/google-ads/api/reference/rpc/v11/SharedCriterionService) using your new shared set's resource name.
```ts
const { results: [{ resource_name }] } = await customer.sharedSets.create([
    {
        name: 'new shared set',
        type: enums.SharedSetType.NEGATIVE_KEYWORDS,
        status: enums.SharedSetStatus.ENABLED,
    },
])

await customer.sharedCriteria.create([
    {
        shared_set: resource_name,
        keyword: {
            text: 'new keyword',
            match_type: enums.KeywordMatchType.EXACT, // or BROAD or PHRASE
        },
    },
])
```

**Comment by sgpascoe** [comment]
I'm getting 

`  GoogleAdsError {
    error_code: ErrorCode { query_error: 12 },
    message: "Error in SELECT clause: invalid field name '_'."
  }`

when I use the first example.

**Comment by sgpascoe** [comment]
That's fantastic! 

I've got the first example up and running now, but struggling with only returning the actual search term.

I've tried search_terms.attributes or search_terms.search_term_view or search_terms.search_term_view.search_term but I can't seem to find the right locator - am I misunderstanding how this object is being returned? 

Apologies, I know this is probably very basic stuff

**Comment by WillCooter** [comment]
The `search_term_view.search_term` attribute should be the actual search term. The returned object will always have the attributes, metrics and segments that you have specified in your query/report.

**Comment by sgpascoe** [comment]
This did the job! 

`      var stfinaldata = [];
      const stimportdata = Object.values(result);
      for(let i = 0; i < stimportdata.length; i++){ 
        let stnarrowdata = Object.values(stimportdata[i]);
        let stsinglefinal = stnarrowdata[0].search_term
        stfinaldata.push(stsinglefinal);
      }`

**Comment by sgpascoe** [comment]
@WillCooter For the second example, in the sharedset creation, I'm receiving the error: `ReferenceError: enums is not defined`

is there something I may have missed? I am creating the client and then the customer beforehand

**Comment by sgpascoe** [comment]
OK, So I've figured the Second error is due to me trying to use a variable for the match type

```
let matchType = BROAD;
await customer.sharedCriteria.create([
    {
        shared_set: resource_name,
        keyword: {
            text: 'new keyword',
            match_type: enums.KeywordMatchType.matchType , 
        },
    },
])
```


Does not work, so instead I have 

```
if (matchtype == 'BROAD'){
    await customer.sharedCriteria.create([
      {
          shared_set: resource_name,
          keyword: {
              text: negativeword,
              match_type: enums.KeywordMatchType.BROAD, 
          },
      },
  ])
  }
  else if (matchtype == 'EXACT'){
    await customer.sharedCriteria.create([
      {
          shared_set: resource_name,
          keyword: {
              text: negativeword,
              match_type: enums.KeywordMatchType.EXACT, 
          },
      },
  ])
  }
  else if (matchtype == 'PHRASE'){
    await customer.sharedCriteria.create([
      {
          shared_set: resource_name,
          keyword: {
              text: negativeword,
              match_type: enums.KeywordMatchType.PHRASE, 
          },
      },
  ])
  }
```

and although not as elegant, it does the job. 

I think for the first error I'm just getting hung up on the line `const { results: [{ resource_name }] } = await customer.sharedSets.create([` as I can't seem to use it in a separate catch function to the keyword creation, as the keyword creation then can't find `resource_name`. 

I either need a way to define it in a way that can be called from a separate function (and ignore the shared set error in the first function, continuing with the keyword creation function seperately) or a way to check that the shared set is not already created. 

I've been doing a lot of trial and error and reading within the API using the links you provided, and solved the majority of my issues, but I feel this is a little obfuscated for me to work out unfortunately. 

Thanks so much for your guidance so far, it's really helping me to learn, but I feel I am a long way from understanding how the API works.

**Comment by sgpascoe** [comment]
@WillCooter I'm now returning resource_name successfully from my first function, to create the shared set.

However I'm still stuck on the last hurdle. If the set already exists, it catches the error and does not return a value for resource_name. Is there a method for simply checking to see if a shared set exists? I imagine I need to define the sharedset without using a create operation, and then somehow return the sharedset.status, but I'm unsure how to do that. I've been experimenting with various things, but the segmented nature of the Ads API reference is making it difficult for me to understand how to turn single references into full code!

**Comment by sgpascoe** [comment]
> @sgpascoe This error is coming from Google rather from this library, I am not sure what it means. You will have to consult [Google's API docs](https://developers.google.com/google-ads/api/reference/rpc/v11/overview) or ask the folks over on the [Google Ads API forum](https://groups.google.com/g/adwords-api).

Thanks @WillCooter  I will do. 

Does my code above look sound, or is there a quicker way in place to make this check?

**Comment by sgpascoe** [comment]
@WillCooter After attaining a new refresh token and fixing the issue a week ago, I am getting the same error. Is there a problem with the refresh token generator above?
