### ISSUE TITLE
Query on developer_token needed 

### ISSUE THREAD

**Issue by braj1999** [Opteo/google-ads-api#414]
Hi,

I am planning to use this library for one of my new integration with google ads API. I am trying to understand why `developer_token` is needed here apart from OAUTH 2 clientId, secret and refresh token. The `developer_token` has wide scope as per my understanding and some customers may not feel confident in sharing that.

I have done an integration with Gmail earlier using `googleapis` and there we just need to initialize with OAUTH 2 creds(access_token, refresh_token, client_id, client_secret) etc

**Comment by assaf** [comment]
For most Google APIs, you only need the end-user's consent, which you get through OAuth.

Some APIs have a separate review/approval process, Google Ads is one of these: https://developers.google.com/google-ads/api/starter-checklist
