### ISSUE TITLE
Support of multiple API versions

### ISSUE THREAD

**Issue by evil-shrike** [Opteo/google-ads-api#415]
Hi.
I understand that the library is based on [google-ads-node](https://github.com/Opteo/google-ads-node) which contains all generated code from protobufs. But in the end the library supports only one API version which can be a blocker if you need to execute queries against different versions. 
If we look at Python client it simply accepts an argument `version` on the client creation.

Did you ever consider to support multiple versions at once? At lease last 3. It would be a great addition.

**Comment by WillCooter** [comment]
Hi @evil-shrike, what is your use case here? Why would you want to execute queries against different versions?

**Comment by evil-shrike** [comment]
Hi. 
We have a [tool](https://github.com/google/ads-api-report-fetcher) that executes queries. So queries are external for it. Users gets the tool and execute their queries. Among other it can be an automated execution in Cloud. 
If the tool is updated, it can contain updated google-ads-api lib with updated API, so then there's a non-zero probability that queries will start failing because of breaking changes. Unfortunately there are always plenty of them. Like renaming enum values, fields, etc. All last major updates (10, 11) contains breaking changes.
With Python version we can stick queries to the API version they were written against and they will continue to work. With NodeJS that's not possible. The only way is to support multiple versions of our tool for each API version which VERY cumbersome.

**Comment by wcoots** [comment]
Hi @evil-shrike, unfortunately this is not a priority for us. Apologies.
