### ISSUE TITLE
queryStream is not a function?

### ISSUE THREAD

**Issue by swaroopu-kr** [Opteo/google-ads-api#423]
Hello, I am trying to get some keyword data back and was trying to use the gaql `queryStream` but node tells me that that is not a function. I am trying to just test with the sample code from the documentation.

![image](https://user-images.githubusercontent.com/82593765/193917840-d82490d2-4020-434f-ab12-37dbc05dedfb.png)

![image](https://user-images.githubusercontent.com/82593765/193917592-fe88ba80-4a72-4e05-a904-a5f6535629b8.png)

What gives?

**Comment by wcoots** [comment]
Hi @swaroopu-kr, apologies for the delayed response, we are very busy at the moment at Opteo. Unfortunately I am unable to replicate your issue, when I run this code `queryStream` works fine. Are you sure you are instantiating your customer class correctly?

**Comment by wcoots** [comment]
Closing for now, feel free to re-open if the issue persists.
