### ISSUE TITLE
Error: grpc: received message larger than max...

### ISSUE THREAD

**Issue by issacg** [Opteo/google-ads-api#43]
### I'm submitting a ...

-   [X] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

I've run into scenarios  when running a query returns the following error "Error: Received message larger than max (9154892 vs. 4194304)"

### Other information

t CustomerService.<anonymous> (C:\prj\node_modules\google-ads-api\build\services\service.js:205:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\prj\node_modules\google-ads-api\build\services\service.js:5:65)

**Comment by kritzware** [comment]
Hi @issacg, unfortunately I'm not sure there is much we can do about this issue. I believe this comes from the [grpc-node](https://github.com/grpc/grpc-node) library that we're using internally.

Which queries does this happen for? Is there any way you can limit the results you're retrieving, using the `limit` constraint?

**Comment by avermeil** [comment]
Fixed in `2.1.1`.
