### ISSUE TITLE
Ability to retrieve request ID & request/response logs

### ISSUE THREAD

**Issue by sheyDev** [Opteo/google-ads-api#431]
Is there a way to get the request/response logs and the request ID from this package? I've gone through the documentation but i'm unable to find anything relating to logging.
Thank you.

**Comment by rosslavery** [comment]
I posted about this a little while ago here. We just use the REST API when we need to reproduce an error that occurs with this wrapper 🙂

https://github.com/Opteo/google-ads-api/issues/314
