### ISSUE TITLE
Upgrade to Google Ads API V12

### ISSUE THREAD

**Issue by nagyadam2092** [Opteo/google-ads-api#433]
### Issue for tracking the v12 upgrade
Release notes: https://developers.google.com/google-ads/api/docs/release-notes#v12
Video highlights: https://www.youtube.com/watch?v=sLWp0ceS-nk

**Comment by nagyadam2092** [comment]
@wcoots I have created this issue so we can follow the upgrade process.

**Comment by nagyadam2092** [comment]
@wcoots sorry, I just realised there was an issue opened already here: https://github.com/Opteo/google-ads-api/issues/427
I guess there just needs to be an actual release made now?

**Comment by wcoots** [comment]
Hi @nagyadam2092, version 12 of the API is already live, we released this a month ago. Update to version `v12.0.1` of this library to use it.

**Comment by tills13** [comment]
Sorry to dig this up but there was some confusion on my part seeing only v11 here but v12.0.1 available through npm. Are you no longer publishing releases here?
