### ISSUE TITLE
What is the correct Oauth2 scope to be used with this package?

### ISSUE THREAD

**Issue by vitorklock** [Opteo/google-ads-api#434]
Currently, when acquiring the user Oauth2 I'm using the following scopes:
```
const scopes = [
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/analytics.readonly',
        'https://www.googleapis.com/auth/analytics',
        'https://www.googleapis.com/auth/adwords',
        'openid', 'email', 'profile',
    ];
```
As adwords (`https://www.googleapis.com/auth/adwords`) is being deprecated, what is the correct new adsAPI URI to be used?

**Comment by assaf** [comment]
The Google Ads API which replaces the Adwords API uses the same scope: `https://www.googleapis.com/auth/adwords` https://developers.google.com/google-ads/api/docs/oauth/internals

The API is currently at version 12, I don't expect they'll change the scope name.

**Comment by vitorklock** [comment]
> The Google Ads API which replaces the Adwords API uses the same scope: `https://www.googleapis.com/auth/adwords` https://developers.google.com/google-ads/api/docs/oauth/internals
> 
> The API is currently at version 12, I don't expect they'll change the scope name.

Makes sense, and it indeed worked. Thanks!

**Comment by vitorklock** [comment]
> The Google Ads API which replaces the Adwords API uses the same scope: `https://www.googleapis.com/auth/adwords` https://developers.google.com/google-ads/api/docs/oauth/internals
> 
> The API is currently at version 12, I don't expect they'll change the scope name.

Makes sense, and it indeed worked. Thanks!
