### ISSUE TITLE
Version v9 is deprecated. Requests to this version will be blocked.

### ISSUE THREAD

**Issue by sgpascoe** [Opteo/google-ads-api#438]
Hi there, I've started getting this error: 

GoogleAdsFailure {
  errors: [
    GoogleAdsError {
      error_code: [ErrorCode],
      message: ' Version v9 is deprecated. Requests to this version will be blocked.'
    }
  ],

**Comment by wcoots** [comment]
@sgpascoe Yes `v9` of the Google Ads API was [sunset a while ago](https://developers.google.com/google-ads/api/docs/sunset-dates). Update to the latest version of this package (`v12.0.1`) to use the latest version of the API.
