### ISSUE TITLE
Ads API v12

### ISSUE THREAD

**Issue by Zikoel** [Opteo/google-ads-api#443]
Hi guys,

There are plans to release v12 of the library? I saw some work a couple of month ago but no more update! The sunset date for the V11 is fixed at `March 31, 2023` and is very close.

**Comment by rosslavery** [comment]
The latest release is already targeting v12 of the Ads API. 

v13 is out now. I tried prepping a PR but unfortunately I'm hitting a blocker. I pinged Opteo just waiting on a response.

**Comment by wcoots** [comment]
on it today

**Comment by jackson-oomdo** [comment]
Hello @wcoots,

I see that you commented that you are working on it but today I'm getting the error "Version v10 is deprecated. Requests to this version will be blocked". Is there a way for me to upgrade it to V11 or is there nothing I can do and just have to wait for you to make the updates?

**Comment by bharatwaaj** [comment]
What is the timeframe on this upgrade? Can we get to know on a timeline?

**Comment by wcoots** [comment]
@Zikoel @rosslavery @bharatwaaj Running into some problems compiling the latest proto files. Have contacted Google to see how they can be resolved, but the only timeline I can give is "coming soon".

**Comment by rosslavery** [comment]
Thanks for the update @wcoots :D

**Comment by KristijanS99** [comment]
Hi guys, any updates on this one? Can we help in any way? Since tomorrow v11 is going down I guess?

**Comment by KristijanS99** [comment]
I just checked on our end it seems v11 is still used, considering v11 lifetime is ending tomorrow is there any updates regarding this? Anything we can do to help guys?

**Comment by rosslavery** [comment]
The title of this issue is wrong, this library supports V12 in it's current
release. The discussion is about getting it updated to support V13.

So if you're up to date with the package, you're fine until September (I
believe?).

**Comment by Zikoel** [comment]
Sorry to all. There is a desync between the released version on npm currently at version `12.0.1` and the releases decalred on the repo actually at version 11 see.

![release](https://user-images.githubusercontent.com/6044789/229134096-9fde6c28-77b0-4753-af8d-61e1e35471b8.png)

So there is no problem with V12 I will close the issue! Sorry for the noise.
