### ISSUE TITLE
UserListService how to mutateMembers 

### ISSUE THREAD

**Issue by sweetanalytics** [Opteo/google-ads-api#445]
We are migrating from [node-adwords](https://github.com/ChrisAlvares/node-adwords) library where we had `user_lists` and we were adding members to that list. In that library we used the `AdwordsUserListService`:

```
service.mutateMembers(
  {
    operations: [
      {
        operator,
        operand: {
          userListId: this.audience.id,
          membersList: members,
        },
      },
    ],
  }
)
```

We can see there's a service in this library called `UserListService`. The problem is that when you try to use it, it throws the following error: 

`TypeError: rpcImpl must be a function`

This might be related to https://github.com/Opteo/google-ads-api/issues/376. We're not able to find any documentation on mutating customer lists. Any guidance would be much appreciated.

**Comment by wcoots** [comment]
Hi @sweetanalytics, the answer is in the issue you linked, you need to use the `create`/`update`/`remove` format for mutations.

**Comment by sweetanalytics** [comment]
Thanks @wcoots, however the examples in the linked issue don't specify the parameters for adding or removing members from the list. They only cover how to create a list, rename a list name, and delete a list, but not how to add members or remove members. Any thoughts?
