### ISSUE TITLE
Upgrade Google Ads API to v15

### ISSUE THREAD

**Issue by evil-shrike** [Opteo/google-ads-api#480]
Hello.
v15 has been released on the 18th of Oct - https://developers.google.com/google-ads/api/docs/release-notes#v15
Please upgrade the proxy protobufs for v15.

**Comment by lushu** [comment]
Also there is a blog about the changes in data uploading: [Updates to Customer Match, Conversions, and Store Sales Uploads](http://ads-developers.googleblog.com/2023/10/updates-to-customer-match-conversion.html)


> The [Google Ads API v15 release](https://developers.google.com/google-ads/api/docs/release-notes) introduced the Consent object for uploading consent with your data. This Consent is used across all uploads for call conversions, click conversions , Customer Match, and Store Sales.

**Comment by evil-shrike** [comment]
ping

**Comment by evil-shrike** [comment]
Hi, sorry for bothering I understand it's Christmas period but it's more than 2 month since the API release, could you share any estimates for a v15 support release please?

**Comment by leovujanic** [comment]
Hi!
I'm also interested in this update, especially as they stated in the email  "You must complete this update before March 2024 in order to continue using Customer Match for users in EEA."

So any update on the status would be appreciated.

**Comment by aliqaryan** [comment]
I haven't seen any new commit in this repo for a couple of months now!! is this library still active?

**Comment by wenson** [comment]
mark it

**Comment by olchyk98** [comment]
ping

**Comment by sheyDev** [comment]
How do we do this ourselves? Is updating the protobufs hard? We really need this upgrade because pulling reporting for asset groups on PMX campaigns are not available till v15.

**Comment by marcolucio** [comment]
we need v15 upgrade too, pls  :+1:

**Comment by evil-shrike** [comment]
Hi. In two weeks (on March 6, 2024 ) the requirement for providing consent for uploading user ids becoming mandatory and it's not supported by the current version (v14), so all user code that depends on this will start failing.
Any update on this?

**Comment by imosing** [comment]
Hi! It's more than 3 months since the latest update already.
v16 is released - https://developers.google.com/google-ads/api/docs/release-notes#v16

Can you please share any updates?

**Comment by danielglh** [comment]
The good news is this package has been upgraded to v16 already...

**Comment by aliqaryan** [comment]
> The good news is this package has been upgraded to v16 already...

Which package?

**Comment by danielglh** [comment]
> > The good news is this package has been upgraded to v16 already...
> 
> Which package?

This npm package `google-ads-node`. It has been upgraded to v16 directly and skipped v15.

https://www.npmjs.com/package/google-ads-api

**Comment by danielvoelk** [comment]
Google Ads API version 14 is deprecated and will stop accepting requests from June 5, 2024 onwards.

Would be good if version 16 would come out of beta, because in 2 weeks the old version won't work anymore.
