### ISSUE TITLE
V16 is deprecated. need v17, other calls are invalid

### ISSUE THREAD

**Issue by Tsilo** [Opteo/google-ads-api#495]
google recently deprecated everything except v17.  how can we move forward?

**Comment by avermeil** [comment]
v16 (which the current version of this library uses) will continue to work until January 2025. We will have released a new version well before then. Looking at [the schedule](https://developers.google.com/google-ads/api/docs/sunset-dates), we'll probably skip straight to 17.1 when that comes out.

**Comment by ikmalsuzali** [comment]
I have tested `listAccessibleCustomers` locally, it works fine but running it on production fails. I suspect that v16 is deprecated
