### ISSUE TITLE
asset related information issue

### ISSUE THREAD

**Issue by Ka6utack** [Opteo/google-ads-api#55]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

**Comment by Ka6utack** [comment]
Thanks very much for ur work. Pulling adwords data is a quite explosive thing, especially when in a smaller level, such as asset. This is a very tedious job. Your work is so awesome.
I think an issue is...
`customer.report({
  entity: 'video',
  attributes: ['campaign.id', 'campaign.name', 'ad_group.id', 'ad_group.name', 'ad_group.status', 'video.id'],
  metrics: ['metrics.impressions', 'metrics.clicks', 'metrics.conversions'],
  segments: ['segments.date'],
  from_date: '2019-05-22',
  order_by: 'metrics.clicks',
  sort_order: 'desc',
  limit: 5,
}).then(data =>
  console.log(data)
).catch(err =>
  console.error(err)
)`
This is normally executed code. Campaign id is correct, but adgroup id and video id are different from what I see in backstage.
I'd like to see your reply and salute your work again.

**Comment by avermeil** [comment]
Hi @Ka6utack ! Thanks for the kind words :)

I'm not sure that I understand your question. Are you saying that the `ad_group.id` in the result rows doesn't match what you expect? Where are you seeing a different AdGroup ID?

**Comment by Ka6utack** [comment]
> Hi @Ka6utack ! Thanks for the kind words :)
> 
> I'm not sure that I understand your question. Are you saying that the `ad_group.id` in the result rows doesn't match what you expect? Where are you seeing a different AdGroup ID?
Thanks for your reply. 
When we were on adwords's asset page. its url looks like `https://ads.google.com/aw/adassets?campaignId=**********&adGroupId=***********&ocid=*********&__c=**********&authuser=1&__u=**********` these params are included in the url. the campaign id is same with the `campaign_id` field data pulled with your work. bt `adgroup_id` doesn't correspond to `adGroupId` in the url. where i hover on a video asset. the link displayed is like `https://www.youtube.com/watch?v=DR2***Ut7zk`. the video id is consistent with your `video.id` field. I think there's something wrong with it, or it could be something wrong with my parameters.
thx! man!

**Comment by avermeil** [comment]
I'm not sure why those wouldn't match... We only do very light parsing of results, so it's very unlikely that we would be mixing up the adgroups. It's more likely that the AdWords UI's URLs don't work in quite the way we expect. It's a complicated Angular app, after all.

Still, if you would like to confirm that the AdGroups we're returning in this library are correct, here are two things you could do:
- Try using https://github.com/Opteo/google-ads-node to make the same GAQL query. That library does almost no parsing of results, so what you see is what you get. If the results (campaign-adgroup-video groups) are different to this library, then this library has a bug.
- Try getting the adgroup name. That's easier to cross check in the AdWords UI than the adgroup ID.
