### ISSUE TITLE
Results are returned as objects instead of raw values

### ISSUE THREAD

**Issue by mateuszjanusz** [Opteo/google-ads-api#59]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

I noticed that the library wraps some results into objects with key _value_, instead of returning just raw values. 

For instance, when I queried final urls for an ad group ad, I received this array of objects:
 `[ { value: 'https://www.geoteam.be/nl/steden/aalst' } ]` 
According to the [API documentation](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v1.resources#google.ads.googleads.v1.resources.Ad), I should receive array of strings that looks like this: 
`['https://www.geoteam.be/nl/steden/aalst' ]`. 

### Other information

Another example of the issue:
```
[ { ad_group:
     { resource_name: 'customers/xxx/adGroups/xxx',
       cpc_bid_micros: 1000000,
       targeting_setting:
        { target_restrictions:
           [ { targetingDimension: 3, bidOnly: { value: true } },
             { targetingDimension: 4, bidOnly: { value: false } },
             { targetingDimension: 5, bidOnly: { value: true } },
             { targetingDimension: 6, bidOnly: { value: true } },
             { targetingDimension: 7, bidOnly: { value: false } },
             { targetingDimension: 8, bidOnly: { value: true } },
             { targetingDimension: 9, bidOnly: { value: true } } ] } } } ]
}
```
Here the library should return booleans for bidOnly.

**Comment by avermeil** [comment]
This is indeed a bug. Fixing it will be an important breaking change, so we'll release a fix for it along  with v2 of the google ads API.
