### ISSUE TITLE
customer.campaigns.list() is returning "Process finished with exit code 0"

### ISSUE THREAD

**Issue by leongrin** [Opteo/google-ads-api#61]
### I'm submitting a ...

-   [X] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [X] question about how to use this project

### Summary

I am trying to implement the google-ads-api in my Node Express app. I downloaded the library (npm i google-ads-api), and I am trying to get started with the code below.

```javascript
const GoogleApiNodeLibrary = require('google-ads-api');

const client = new GoogleApiNodeLibrary.GoogleAdsApi({
    client_id: 'XXX',
    client_secret: 'XXX',
    developer_token: 'XXXX',
});

const customer = client.Customer({
    customer_account_id: 'XXX',
    login_customer_id: 'XXX',
    refresh_token: 'XXX'
});

customer.campaigns.list();
```

The values I am using for Authentication are all correct. The "login_customer_id:" uses the MCC ID, and the "customer_account_id:" uses one of the accounts ID linked to the MCC account.

When I run this code, I don't get an error. It just take a few seconds and then return "Process finished with exit code 0".

How can I fix this?

**Comment by kritzware** [comment]
Hi @leongrin , 

I think this happens because you're not waiting for the `list()` method to finish, since it's an asynchronous function. If you add an `await`, as shown in the example below, the code will work 😄 

```javascript
// Make sure main() can use await
async function main() {
  const client = new GoogleAdsApi({
    client_id: GADS_CLIENT_ID,
    client_secret: GADS_CLIENT_SECRET,
    developer_token: GADS_DEVELOPER_TOKEN
  })

  const customer = client.Customer({
    customer_account_id: GADS_CID,
    login_customer_id: GADS_LOGIN_CUSTOMER_ID,
    refresh_token: GADS_REFRESH_TOKEN
  })
  
  // Wait for the result to come back, using await
  const campaigns = await customer.campaigns.list()
  console.log(campaigns)
}
```

**Comment by leongrin** [comment]
Hi @kritzware 

That's correct. Now it's working. Thank you so much!
