### ISSUE TITLE
Issue with nested objects/arrays - Related to closed issue #59

### ISSUE THREAD

**Issue by nsberndt** [Opteo/google-ads-api#66]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

It appears there is an issue with the interpretation/parsing of deeply nested objects/arrays. I am finding this issue specifically in the structure of AdGroup -> `targeting_setting` but it may also exist elsewhere in the API.

Overall this seems to be related to but not necessarily the same as the bug/discussion in closed issue #59. I have observed the following potential issues:

1. `targeting_restrictions: undefined` in the struct of an AdGroup

2. `nested_path` for deeply nested array is being generated as `targeting_setting.target_restrictions.targetingDimension` when it appears this should actually be `targeting_setting.target_restrictions[<INDEX>].targetingDimension`

### Other information

This bug is being encountered specifically when trying to build AdGroup via API per the structure of the [google-ads-api documentation](https://opteo.com/dev/google-ads-api/#adgroup) and the native [Google Ads API documentation](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.common#google.ads.googleads.v2.common.TargetingSetting). It appears at least part of the issue is within the handling of the `unroll(v)` function on **line 84** of `google-ads-node/build/lib/utils.js` -- I believe this may need to have the index passed in from the `isArray` portion above it and a determination made as to how to structure the `nested_path` accordingly. 

The following console logs may be helpful:

_(Occurs when attempting to build/create AdGroup)_
```
Error: Attempted to set value "3" on invalid path "targeting_setting.target_restrictions.targetingDimension" in resource
    at toProtoValueFormat (~/google-ads-api-test/node_modules/google-ads-node/build/lib/utils.js:96:15)
    at unroll (~/google-ads-api-test/node_modules/google-ads-node/build/lib/utils.js:87:19)
    at convertToProtoFormat (~/google-ads-api-test/node_modules/google-ads-node/build/lib/utils.js:83:26)
    at unroll (~/google-ads-api-test/node_modules/google-ads-node/build/lib/utils.js:86:19)
    at pb.(anonymous function).value.map (~/google-ads-api-test/node_modules/google-ads-node/build/lib/utils.js:79:24)
    at Array.map (<anonymous>)
    at convertToProtoFormat (~/google-ads-api-test/node_modules/google-ads-node/build/lib/utils.js:78:36)
    at unroll (~/google-ads-api-test/node_modules/google-ads-node/build/lib/utils.js:86:19)
    at Object.convertToProtoFormat (~/google-ads-api-test/node_modules/google-ads-node/build/lib/utils.js:83:26)
    at GoogleAdsClient.buildResource (~/google-ads-api-test/node_modules/google-ads-node/build/lib/client.js:82:41)
```

_(Log of the struct for AdGroup -- note `target_restrictions: undefined` which should be an array of objects with `targeting_dimension` and `bid_only` properties )_

```
{ struct:
   { resource_name: 'string',
     id: 'number',
     name: 'string',
     status: 'enum_AdGroupStatus',
     type: 'enum_AdGroupType',
     ad_rotation_mode: 'enum_AdGroupAdRotationMode',
     base_ad_group: 'string',
     tracking_url_template: 'string',
     url_custom_parameters: { key: 'string', value: 'string' },
     campaign: 'string',
     cpc_bid_micros: 'number',
     cpm_bid_micros: 'number',
     target_cpa_micros: 'number',
     cpv_bid_micros: 'number',
     target_cpm_micros: 'number',
     target_roas: 'number',
     percent_cpc_bid_micros: 'number',
     explorer_auto_optimizer_setting: { opt_in: 'boolean' },
     display_custom_bid_dimension: 'enum_TargetingDimension',
     final_url_suffix: 'string',
     targeting_setting: { target_restrictions: undefined },
     effective_target_cpa_micros: 'number',
     effective_target_cpa_source: 'enum_BiddingSource',
     effective_target_roas: 'number',
     effective_target_roas_source: 'enum_BiddingSource',
     labels: 'string' } }
```

I am actively working on a suitable resolution but would appreciate feedback/assistance from the community and authors in the meantime. I will comment/update/PR if I find a suitable fix that does not seem to cause breaking changes elsewhere in the API

**Comment by avermeil** [comment]
Hi @nsberndt !

Thanks for the very detailed bug report :)

1. I'm not yet sure why `targeting_restrictions` is `undefined` in the struct of an AdGroup. It might be related to this PR? https://github.com/Opteo/google-ads-node/pull/20

2. The `Error: Attempted to set value "3" on invalid path "targeting_setting.target_restrictions.targetingDimension" ` seems like a related bug. The actual error message may be misleading -- it's likely that it's just failing because `targeting_restrictions` is `undefined`. 

Could you share the exact code that causes that error? 

Thanks for your help!

**Comment by nsberndt** [comment]
Hi @avermeil -- thanks for the response. I will look through that PR. As far as my code, I am running the following function:

```
async function createAdGroup() {

  const ad_group = {
  campaign: 'customers/8833035246/campaigns/2064931322',
  cpc_bid_micros: 1430000,
  cpm_bid_micros: 10000,
  cpv_bid_micros: 0,
  effective_target_cpa_micros: 0,
  labels: [],
  name: 'Ad group 1',
  status: 2,
  target_cpa_micros: 0,
  target_cpm_micros: 10000,
  targeting_setting: { 
    target_restrictions: [ 
      { targetingDimension: 3, bidOnly: true }, 
    ],
  },
  type: 2,
  url_custom_parameters: []
  }

  try {
    const result = await customer.adGroups.create(ad_group)
    console.log(result)
    return result
  }
  
  catch(e){
    console.error(e)
  }

}
```

I have tried running with different variations on the prop names i.e. `targeting_dimension` vs `targetingDimension` (as it is returned on AdGroups created through the Google Ads GUI directly) but the same error persists. I have also tried various other combinations of property enums and fields with no luck.

Note this is all just for testing at this point i.e. test account/campaign etc (not actually in production). Ultimately I am just trying to complete the process flow of Campaign / AdGroup / Ad creation using your API. I am able to successfully create Campaigns as well as modifying and fetching most data, but unable to create AdGroups due to this bug. 

If you are able to successfully create AdGroups (test or otherwise) with the currently published codebase for this API I would appreciate a sample of the code or function(s) you are using to do so. 

Thanks for all the work you guys have done on this so far! Happy to help where I can.

**Comment by avermeil** [comment]
Hey @nsberndt -- sorry about letting this issue linger.

I've tried creating adgroups in this latest version (v3.2.0) and it seems to work fine. I wrote this test as an example: https://github.com/Opteo/google-ads-api/blob/master/src/tests/ad_group.test.ts

Are you still having trouble with this?

**Comment by nsberndt** [comment]
Hi @avermeil -- I haven't actually looked into it much further as we will probably just be working with the AdWords API for the time being given Ads' beta status. I will try and get around to testing at some point in the near future but I would say if it is working in your tests it is likely resolved or was a user error on my end.
