### ISSUE TITLE
unhandled rejection error ETIMEDOUT

### ISSUE THREAD

**Issue by huturen** [Opteo/google-ads-api#68]
### unhandled rejection error:
unhandledRejection Error: connect ETIMEDOUT 216.58.200.237:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '216.58.200.237',
  port: 443
}

![image](https://user-images.githubusercontent.com/5173298/62597080-64521c80-b917-11e9-8e68-45e5f7a310ec.png)

try-catch clause can not handle this error.
the exception was thrown by google-ads-api.

here is my code:
```javascript
    async query(gaqlString) {
        try {
            const customer = this._getCustomer();
            const result = await customer.query(gaqlString);

            return this._result(0, 'ok', result);
        } catch (err) {
            return this._result(-1, err.message || err);
        }
    }
```

**Comment by avermeil** [comment]
Hi @huturen !

This looks like a network error, likely when trying to get an access token. In your code example, what is `this._getCustomer()`? Shouldn't that function be async?

**Comment by huturen** [comment]
many thanks.

it was just a network error.
