### ISSUE TITLE
TypeError: operation.setUpdate is not a function

### ISSUE THREAD

**Issue by Mattensor** [Opteo/google-ads-api#70]
Hey there,

I'm wanting to update an existing billing setup and get back the following error: 
`TypeError: operation.setUpdate is not a function at BillingSetupService.<anonymous>`

I run the following code (using version 3.2.0):
```
await customer.billingSetups.update({
    resource_name: "customers/*****/billingSetups/*****",
    start_time_type: TimeType.NOW
  });
```

Not too sure why I can't update, would be amazing to get a hand :)

**Comment by avermeil** [comment]
Hey @Mattensor! It looks like it's not possible to update billingSetups -- they can only be created or removed: https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#google.ads.googleads.v2.services.BillingSetupOperation

This is an error in our documentation. We'll update our docs and remove that function from the library. 

Thanks for reporting this :)

**Comment by Mattensor** [comment]
Ahh right, thanks @avermeil
