### ISSUE TITLE
Refresh token helper callback redirect_uri_mismatch

### ISSUE THREAD

**Issue by mledwards** [Opteo/google-ads-api#73]
When using the [refresh token helper](https://refresh-token-helper.opteo.com) I get this message "The redirect URI in the request, https://refresh-token-helper.opteo.com/callback/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs,"

**Comment by avermeil** [comment]
Did you add https://refresh-token-helper.opteo.com/callback/ to your list of `Authorized redirect URIs` in your google cloud platform UI?

**Comment by mledwards** [comment]
Ah of course! Thanks.
