### ISSUE TITLE
Account Budget Proposal Error

### ISSUE THREAD

**Issue by Mattensor** [Opteo/google-ads-api#75]
Hey there,

I'm wanting to update an existing account budget and get back the following error:
TypeError: operation.setUpdate is not a function
    at AccountBudgetProposalService.<anonymous> 

I run the following code (using version 3.2.0):
```
customer.accountBudgetProposals.update({
    resource_name: accountBudget,
    proposal_type: 4
});
```
Not too sure why I can't update, I had a similar issue when trying to update billing setups (was not possible in the api). Looking at the docs this should be possible :)

https://developers.google.com/google-ads/api/docs/billing/account-budgets#terminating_account_budgets

Am I missing something here? 
Thanks

**Comment by Mattensor** [comment]
Any update on this?

**Comment by kritzware** [comment]
Hi @Mattensor, apologies for the delay on this one.

Unfortunately, it seems like account budget proposals cannot be updated, according to [the Google Ads API documentation](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#google.ads.googleads.v2.services.AccountBudgetProposalOperation). They only support creation or removal 😞

**Comment by Mattensor** [comment]
Amazing! that makes sense in a weird way
