### ISSUE TITLE
Missing fields when using any type of simulations

### ISSUE THREAD

**Issue by loicadolphe** [Opteo/google-ads-api#77]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

When querying any type of simulations (i.e. `ad_group_simulation` or `campaign_criterion_simulation`) with the `report()` method any fields ending in `list` are not shown. 

This is the list of all the missing fields : 

 - `campaign_criterion_simulation.bid_modifier_point_list`
 - `ad_group_simulation.cpc_bid_point_list`
 - `ad_group_simulation.target_cpa_point_list `
 - `ad_group_criterion_simulation.cpc_bid_point_list `

**Comment by kritzware** [comment]
This turned out to be our own internal caching issue, so closing for now.
