### ISSUE TITLE
url_custom_parameters missing keys

### ISSUE THREAD

**Issue by BraunreutherA** [Opteo/google-ads-api#79]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

Hi there, 

thanks for the great library! Sadly the when querying for any resource that uses url_custom_parameters I get back an array with objects of values. The official google API should return the keys of the custom parameter aswell. Only having a value without the key is not very helpful. Do I have to specify something to get it? 
Here you can find the google docs: https://developers.google.com/adwords/api/docs/reference/v201809/AdGroupService.CustomParameter.html

Here is a sample query: 

```js
const results = await customer.report({
    entity: 'ad_group_criterion',
    attributes: ['ad_group_criterion.url_custom_parameters'],
});
```

and the result:

```json
[
  {
    "ad_group_criterion": {
      "resource_name": "customers/<my-customer-id>/adGroupCriteria/<ad-group-criterion-id",
      "url_custom_parameters": [
        {
          "value": "value1"
        },
        {
          "value": "value2"
        }
      ]
    }
  }
]
```

**Comment by avermeil** [comment]
This issue should now be resolved in google-ads-api@3.4.3. I'm going to close this issue, but feel free to re-open should any more problems arise :)
