### ISSUE TITLE
Error: Cannot find module './entities/AdGroupCriterions'

### ISSUE THREAD

**Issue by jafaircl** [Opteo/google-ads-api#8]
When deployed to Heroku (Linux), a server won't start because of this error. It looks like the filename wasn't updated from `AdgroupCriterions` to `AdGroupCriterions` but the references in `Customer` were before 0.5.0 was released to npm. When I look in node_modules the file is still named `AdgroupCriterions`. It seems like if the current version on Github is pushed to npm, that will fix the issue.

**Comment by mateuszjanusz** [comment]
Hi @jafaircl,

I cannot reproduce this error, however, it looks like a caching issue. 
Can you possibly remove /node_modules directory, clear cache and rebuild all modules? 

We haven't changed any references or file names in this package recently. 
Also, the most recent code (v0.5.0) has been released to npm.

**Comment by jafaircl** [comment]
@mateuszjanusz I tried deleting node_modules, deleting node_modules and package-lock.json, and deleting mode_modules, package-lock.json and running npm cache-clean. Heroku also has node modules caching set to false. When I open node_modules, it still shows this list of files:

![screen shot 2019-02-11 at 10 26 36 am](https://user-images.githubusercontent.com/6155007/52573699-ae36cb80-2de8-11e9-8b83-a50e38282c37.png)


Note the `AdgroupCriterions.js` in lib/entities. I don't see any reference to `AdgroupCriterions` in the repo so I'm not sure how/why it's getting changed.

**Comment by avermeil** [comment]
I've just released a new version, hopefully with that filename fixed. Let me know if this fixes your issue.

**Comment by jafaircl** [comment]
@avermeil that does seem to have fixed it. Thanks!
