### ISSUE TITLE
Support sorting by multiple fields

### ISSUE THREAD

**Issue by HNicolas** [Opteo/google-ads-api#80]
Currently the query builder does not support sorting query results by multiple fields.
It should allow ordering by multiple fields with different sort orders like specified in the documentation : https://developers.google.com/google-ads/api/docs/query/ordering-limiting

Moreover, by default DESC sort_order is appended to the order part of the query although the official documentation says that sort order is not mandatory and the default behavior is to sort results ascending.

https://github.com/Opteo/google-ads-api/blob/e99a0f3cccb17f34bdcfbf8d40d8d5cbd5cb62ca/src/utils.ts#L182

**Comment by WillCooter** [comment]
This has now been added with an alternative methods of sorting the results of report. Now you can use the `order` key, which should be an array of objects with a `field` key and an optional `sort_order` key. The order of the items in the array will map to the order of the sorting keys in the GAQL query, and hence the priorities of the sorts.

```ts
const response = await customer.report({
  entity: "campaign",
  attributes: ["campaign.id"],
  metrics: ["metrics.clicks"],
  segments: ["segments.date"],
  order: [
    { field: "metrics.clicks", sort_order: "DESC" },
    { field: "segments.date", sort_order: "ASC" },
    { field: "campaign.id" }, // default sort_order is descending
  ],
});
```
