### ISSUE TITLE
Missing descriptive_name for customer_client entities

### ISSUE THREAD

**Issue by mortiy** [Opteo/google-ads-api#88]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary
I'm running `client.customerClients.list()`, but it's entities missing `descriptive_name` property.
I'm getting only these properties in response: `resource_name`, `client_customer`, `hidden`, `level`

PHP example shows that the fields should be there:
https://github.com/googleads/google-ads-php/blob/master/examples/AccountManagement/GetAccountHierarchy.php#L128

**Comment by meip** [comment]
I recently stumble across a similar issue while it turned out to be personal fault (see https://groups.google.com/d/topic/adwords-api/i8VMe9KiUXc/discussion). After defining the name in the Google Ads setting I was able to query it with the `report` functionality:

```JavaScript
customerClient.report({
    entity: 'customer',
    attributes: [
        'customer.id',
        'customer.descriptive_name',
        'customer.manager',
        'customer.currency_code',
        'customer.time_zone'
    ]
})
```

**Comment by mortiy** [comment]
Thanks, but it looks like not my case.
I'm working with another table — `customer_client`.
I was able to get those client's names by loading one by one using `customer_client.client_customer` resource_name and `customer` table.
But I would like to access `customer_client.descriptive_name` directly.

**Comment by WillCooter** [comment]
We are currently working on upgrading to Google Ads API V3. This issue has been fixed in the release, and will be coming soon.

**Comment by spicy-sauce** [comment]
> We are currently working on upgrading to Google Ads API V3. This issue has been fixed in the release, and will be coming soon.

Is this feature available? Is it possible to get all the client accounts of a specific ad manager account?
Thanks.

**Comment by pschiume** [comment]
I'm having exactly the same issue, descriptive_name in missing. It is fixed?
