### ISSUE TITLE
AssetService not in the documentation

### ISSUE THREAD

**Issue by noudadrichem** [Opteo/google-ads-api#89]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [x] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

I wasn't able to find the AssetService inside the documentation but I did find it in the code. I was wondering if this was done on purpose.

**Comment by avermeil** [comment]
Hi @noudadrichem !

I don't think this was done on purpose -- we must have forgotten to add it to the docs. We'll add it in the next release.

**Comment by avermeil** [comment]
Should be added to the docs now.
