### ISSUE TITLE
Skip, Offset in fetching

### ISSUE THREAD

**Issue by noudadrichem** [Opteo/google-ads-api#90]
### I'm submitting a ...

-   [ ] bug report
-   [x] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary
I'm not able to find any functionality about skipping the first `x` amount of items. I do see that campaigns has a `LIMIT` key but it would be nice to have something like SKIP or OFFSET too like in SQL. e.g:
```js
customer.campaign.list({
    skip: 10,
    limit: 10,
})
```
⬆ Gets result 10 to 20.

**Comment by tbregovic** [comment]
@noudadrichem The way its described in documentation of this package:

> This library handles paging automatically. If the number of returned rows is larger than the page size, it will paginate through result sets and return all of the results when done. Defaults to 10,000.

Unfortunately this also doesn't work for me, I'm using custom query to retrieve minimum data but there is so much of it that when I get everything lambda runs out of memory.

It would be great if there was an optional parameter `page_token` so we could do pagination manually ([doc ref](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v3.services#google.ads.googleads.v3.services.SearchGoogleAdsRequest)).

**Comment by avermeil** [comment]
Hi @tbregovic ,

What's the custom query that you're using? Are you using a `LIMIT` clause, and/or setting the `page_size` parameter?

**Comment by tbregovic** [comment]
@avermeil Have to say that lambda isn't running out of memory because of the size fetched data (at least not now) but the size of it probably isn't helping.
Currently in testing phase with data filtered by date and as much as I can I'm already over 50k items (don't know what will happen when I go over 1mil of them).
Because in prod I expect way more I try to optimize every little bit as much as I can and calling page by page manually so I can work with batches of items would help that.

**Comment by avermeil** [comment]
@tbregovic Have you considered using `customer.reportStream()`? It will results as it gets them, allowing you to do your processing and avoid excessive memory usage.

**Comment by tbregovic** [comment]
> @tbregovic Have you considered using `customer.reportStream()`? It will results as it gets them, allowing you to do your processing and avoid excessive memory usage.

@avermeil Haven't thought of that, thanks for the tip will try it out.
Paging would still be nice to have :)

**Comment by WillCooter** [comment]
We want to keep the report options as close to what is possible in google ads query language as possible. Therefore this is not in our current scope. However this will be possible in a future version of [google-ads-node](https://github.com/opteo/google-ads-node).
