### ISSUE TITLE
Unable to use "DISPLAY_SMART_CAMPAIGN" advertising_channel_sub_type with "DISPLAY" type"

### ISSUE THREAD

**Issue by umar0107** [Opteo/google-ads-api#94]
Want to use auto targeting (Ad group) like smart targeting option in which campaign choose automatically its adgroup and for this google adwords provide "DISPLAY_SMART_CAMPAIGN" advertising_channel_sub_type with "DISPLAY" type" but it is not working using this library.
Please have a look on if it is bug or please tell me if i'm doing anything wrong.

**Comment by LaurynasP** [comment]
Key Point: To use Smart Display campaigns, your account needs to meet the conversion-based eligibility requirements: at least 50 conversions on the Display Network—or at least 100 conversions on the Search Network—in the last 30 days.

**Comment by umar0107** [comment]
Hey @LaurynasP thanks for your response,
I can use Smart Display campaigns on adwords dashboard, but unable to use in API.
any thoughts?

**Comment by umar0107** [comment]
hey @avermeil  @loicadolphe ,
please provide some solution it.
thanks

**Comment by loicadolphe** [comment]
Hi @umar0107 ,

Can you send me the query you're running? Are you trying to set up auto targeting via the api or are you just fetching data?

**Comment by umar0107** [comment]
Hi @loicadolphe ,
here is code in which i'm trying to set up auto targeting via api.

`const campaignParams = {
    name: param.name + '-' + timestamp,
    campaign_budget: campaignBudget.resourceName,
    manual_cpc: {
        enhanced_cpc_enabled: true
    },
    advertising_channel_type: enums.AdvertisingChannelType.DISPLAY,
    advertising_channel_sub_type: enums.AdvertisingChannelSubType.DISPLAY_SMART_CAMPAIGN,
    status: enums.CampaignStatus.PAUSED,
    start_date: param.startDate,
    end_date: param.endDate,
    payment_mode: enums.PaymentMode.CLICKS,
}
const { results } = await customer.campaigns.create(campaignParams)`

**Comment by loicadolphe** [comment]
Hi @umar0107 

Unfortunately I'm getting the following error directly from Google Ads : `OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE`, which means it's out of the scope of this library. 
You can always investigate on the forums (https://support.google.com/google-ads/community?hl=en) to find out if they are planing to make it possible via the API. 

Sorry I couldn't be more helpful.
