### ISSUE TITLE
7 PERMISSION_DENIED: User doesn't have permission to access customer

### ISSUE THREAD

**Issue by grzegorzCieslik95** [Opteo/google-ads-api#96]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary
Hi, i have a problem with create client with `login_customer_id`.  I have code like this:

```
authorize() {
        const client = new GoogleAdsApi({
            client_id: this.clientId,
            client_secret: this.clientSecret,
            developer_token: this.developerToken
        });

        this.customer = client.Customer({
            customer_account_id: this.customerAccountId,
            login_customer_id: this.loginCustomerId,
            refresh_token: this.refreshToken
        });
    }
```

when i try get customerClientLinks list i have this error

```
Error: User doesn't have permission to access customer. Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. See https://developers.google.com/google-ads/api/docs/concepts/call-structure#login-customer-id
    at CustomerClientLinkService.<anonymous> (/home/gcieslik/workspace/export-creator-worker/node_modules/google-ads-api/build/services/service.js:178:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/gcieslik/workspace/export-creator-worker/node_modules/google-ads-api/build/services/service.js:6:65)
  code: { authorizationError: 2 },
```

Do you have any idea how can i fix it?

**Comment by sogangCSmaster** [comment]
Could you tell me how you fixed this issue? I am having a same problem

**Comment by ikkhannn** [comment]
Can you please tell how did you fix it?

**Comment by ikkhannn** [comment]
@sogangCSmaster have you found a solution?

**Comment by sogangCSmaster** [comment]
@ikkhannn login_customer_id is your google ads MCC account (xxx-xxx-xxxx)
and customer_account_id is google ads account (xxx-xxx-xxxx)

make sure your customer_account_id is under your mcc account

**Comment by ikkhannn** [comment]
@sogangCSmaster thank you so much. However, is there any way we could programmatically get the mcc account id (login_customer_id) of a google ads account? Thanks in advance.
