### ISSUE TITLE
Excludes third party ads from AdGroupAd fetching. 

### ISSUE THREAD

**Issue by noudadrichem** [Opteo/google-ads-api#98]
### I'm submitting a ...

-   [x] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [ ] question about how to use this project

### Summary

When fetching ad group ads the third party ads are excluded. Literally every type of ad is there except third party. Is this a bug or is there a specific reason?

**Comment by avermeil** [comment]
I'm not sure that I know what you mean by third party ad. This library is a reflection of the official API docs, and I can't find any third party ads there: https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.resources#google.ads.googleads.v2.resources.Ad ?

Perhaps these are only available via the old AdWords API?

**Comment by BannerwiseMZL** [comment]
@noudadrichem The API doesn't support 3PAS ads because they have a completely different acceptance policy handled by a different team (the 3PAS team). They manually add 3PAS ads to a Google Ads Account. For that reason you can also not copy 3PAS ads for example.

**Comment by avermeil** [comment]
Closing this issue for now. Feel free to reopen if anything comes up!
