### ISSUE TITLE
Video_quartile_xx_rate not found in adgroup resource (using customer.query)

### ISSUE THREAD

**Issue by ronnapatb** [Opteo/google-ads-api#99]
### I'm submitting a ...

-   [ ] bug report
-   [ ] feature request
-   [ ] question about the decisions made in the repository
-   [* ] question about how to use this project

I'm using this query: 
const data = await customer.query(`
              SELECT 
                campaign.id,
                ad_group.id,
                ad_group_ad.ad.device_preference,
                metrics.impressions,
                metrics.clicks,
                metrics.ctr,
                metrics.average_cpc,
                metrics.cost_micros,
                metrics.conversions,
                metrics.average_cpm,
                metrics.cost_per_conversion,
                metrics.conversions_from_interactions_rate,
                metrics.video_views,
                metrics.video_view_rate,
                metrics.view_through_conversions,
                metrics.video_quartile_100_rate,
                metrics.video_quartile_75_rate,
                metrics.video_quartile_50_rate,
                metrics.video_quartile_25_rate,
                segments.date
              FROM ad_group_ad
              WHERE segments.date DURING LAST_30_DAYS
            `)
then when I get the result other the metrics was appear but only group of video_quartile_xx_rate not found. I have compare the value in the google ads other value are the same and Video_quartile_xx_rate is exist but it don't have the value in query api.

**Comment by kritzware** [comment]
Apgoloes for the delay on this one. I've just created a PR which resolves this issue in [opteo/google-ads-node](https://github.com/opteo/google-ads-node). When it's merged in, we'll pull the change into google-ads-api asap.

Fix here: https://github.com/Opteo/google-ads-node/pull/42

**Comment by kritzware** [comment]
This has since been fixed in `v3.6.2` 👌
